-- Animals for Wood Elves (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc16_group_drycha
    {"rory_wef_lake_dragon", "rare", 3},
    {"rory_welf_bear", "special", 2},
    {"rory_welf_boar", "special", 1},
    {"rory_welf_elk", "special", 1},
    {"rory_welf_giant_boar", "special", 2},
    {"rory_welf_great_stag", "special", 1},
    {"rory_welf_grey_wolf", "special", 2},
    {"rory_welf_griffon", "rare", 3},
    {"rory_welf_pegasus", "special", 1},
    {"rory_welf_quest_beast", "rare", 2},
    {"rory_welf_small_wolf", "special", 1},
    {"rory_welf_tiger", "special", 2},
    {"rory_welf_wildcat", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
