-- SCM: Tribes of the North (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_norsca
    {"dead_drenok_ice_golem", "special", 2},
    {"deco_nor_huskarls", "special", 1},
    {"deco_nor_maidens", "special", 1},
    {"hkrul_bearmen", "special", 2},
    {"hkrul_beorg_bear_sem", "rare", 3},
    {"hkrul_beorg_brown_feral", "special", 2},
    {"hkrul_beorg_brown_feral_marked", "special", 2},
    {"hkrul_beorg_ice_feral", "special", 2},
    {"hkrul_godi", "rare", 2},
    {"hkrul_norsca_harpoon_ror", "special", 2},
    {"hkrul_norsca_whalers", "core"},
    {"hkrul_norsca_ymir_ror", "rare", 2},
    {"hkrul_sarl_hunters", "special", 1},
    {"hkrul_sarl_hunters_ror", "special", 2},
    {"hkrul_shark_1", "rare", 2},
    {"hkrul_skeggi_giant_ror", "rare", 2},
    {"hkrul_skeggi_inf_marauder_champions_0", "special", 2},
    {"rhox_bjornling_huscarl", "special", 2},
    {"rhox_bjornling_huscarl_ror", "special", 2},
    {"rhox_graeling_werekin_of_fijgard", "special", 2},
    {"rhox_skeggi_dodvakt", "special", 2},
    {"wolftribe_nor_inf_wolf_champions_ror_0", "special", 2},
    {"wolftribe_nor_inf_wolfguard_honorguard", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
