-- The Jade-Blooded Vampires: Curse of Nongchang (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_jade_vampires_IotM_group
    {"cth_jiangshi_p_ror", "special", 2},
    {"cth_jiangshi_summoned", "special", 2},
    {"cth_revenant_ror", "core"},
    {"jbv_blood_lions", "special", 2},
    {"jbv_carriage", "rare", 2},
    {"jbv_devil", "rare", 2},
    {"jbv_diaosigui", "special", 2},
    {"jbv_faithfuls_ancient", "core", 1},
    {"jbv_faithfuls_ancient_summoned", "core", 1},
    {"jbv_gateguardian", "rare", 3},
    {"jbv_gateguardian_summoned", "rare", 3},
    {"jbv_ghost_host", "core"},
    {"jbv_ghost_host_ror", "core"},
    {"jbv_ghost_host_summoned", "core"},
    {"jbv_ghost_host_summoned_2", "core"},
    {"jbv_mogwai", "special", 2},
    {"jbv_newbloods", "special", 1},
    {"jbv_newbloods_summoned", "special", 1},
    {"jbv_pale_lady", "special", 2},
    {"jbv_skeleton_spear", "core", 1},
    {"jbv_undead_hag", "core", 1},
    {"jbv_warriors_0", "special", 1},
    {"jbv_warriors_1", "core", 1},
    {"jbv_warriors_ror", "special", 1},
    {"jbv_xiang_men", "core"},
    {"jbv_xiang_men_summoned", "core"},
    {"jbv_yaoguai", "rare", 2},
    {"jbv_youxia", "special", 2},
    {"jbv_youxia_guandao", "special", 2},
    {"jbv_youxia_guandao_ror", "special", 2},
    -- wh3_jade_vampires_group
    {"jbv_faithfuls", "core", 1},
    {"jbv_faithfuls_dagger", "core", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
