-- Vanilla + DLC (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- dust_gutrot_military_group
    {"wh3_main_nur_inf_forsaken_0_warriors", "core"},
    -- wh2_dlc09_tomb_kings
    {"wh3_dlc29_tmb_mon_khemric_titan", "rare", 3},
    {"wh3_dlc29_tmb_mon_khemric_titan_ror", "rare", 3},
    {"wh3_dlc29_tmb_mon_ushabti_ror_sepulchrex", "special", 2},
    -- wh2_dlc09_tomb_kings_arkhan
    {"wh2_dlc09_tmb_inf_cairn_wraiths", "special", 2},
    {"wh2_dlc09_tmb_inf_spirit_host", "core"},
    {"wh2_dlc09_tmb_mon_crypt_horrors", "special", 2},
    {"wh2_dlc09_tmb_mon_morghast_archai", "rare", 2},
    {"wh2_dlc09_tmb_mon_morghast_harbingers", "special", 2},
    -- wh2_dlc11_group_vampire_coast
    {"wh2_dlc11_cst_cav_knights_errant_2", "special", 1},
    {"wh2_dlc14_skv_inf_stormvermin_1_summoned", "special", 1},
    -- wh2_main_hef_imrik
    {"wh2_dlc15_hef_mon_forest_dragon_0", "rare", 3},
    -- wh2_main_skv
    {"wh2_dlc11_cst_mon_rotting_prometheans_summoned_0", "special", 1},
    {"wh3_dlc29_skv_art_plagueclaw_catapult_ror", "rare", 2},
    {"wh3_dlc29_skv_art_warp_doom_magma_cannon", "rare", 2},
    {"wh3_dlc29_skv_inf_deathvermin_ror", "special", 1},
    {"wh3_dlc29_skv_inf_pusbags", "core"},
    {"wh3_dlc29_skv_mon_stormfiend_doomflayer_gauntlets", "special", 2},
    {"wh3_dlc29_skv_mon_stormfiend_grinderfists", "special", 2},
    {"wh3_dlc29_skv_mon_stormfiend_ratling_cannons", "special", 2},
    {"wh3_dlc29_skv_mon_stormfiend_shock_gauntlets", "special", 2},
    {"wh3_dlc29_skv_mon_stormfiend_warpfire_projectors", "special", 2},
    {"wh3_dlc29_skv_mon_stormfiend_windlaunchers", "special", 2},
    {"wh3_dlc29_skv_mon_stormfiends_ratling_cannons_ror", "special", 2},
    {"wh3_dlc29_skv_veh_cauldron_of_a_thousand_poxes", "special", 2},
    -- wh3_dlc20_group_chs_azazel
    {"wh3_dlc29_chs_inf_flayerkin", "core"},
    {"wh3_dlc29_chs_mon_basilisk", "rare", 2},
    {"wh3_dlc29_chs_mon_chaos_siege_giant", "rare", 3},
    {"wh3_dlc29_chs_mon_giant_spined_chaos_beast", "rare", 2},
    {"wh3_dlc29_chs_mon_giant_spined_chaos_beast_ror", "rare", 2},
    -- wh3_dlc20_group_chs_festus_glottkin
    {"wh3_dlc29_chs_inf_chosen_mnur_ror", "special", 2},
    {"wh3_dlc29_chs_inf_putrid_blightkings_axe_shield", "special", 2},
    {"wh3_dlc29_chs_inf_putrid_blightkings_dual_axe", "special", 2},
    {"wh3_dlc29_chs_inf_putrid_blightkings_dual_axe_ror", "rare", 2},
    {"wh3_dlc29_chs_inf_putrid_blightkings_great_weapons", "special", 2},
    -- wh3_dlc20_group_chs_valkia
    {"wh3_main_pro_kho_inf_flesh_hounds_of_khorne_simaergul_0", "special", 2},
    -- wh3_dlc23_group_chaos_dwarfs
    {"wh3_dlc29_chd_mon_chaos_siege_giant", "rare", 3},
    -- wh3_dlc25_group_elspeth
    {"wh3_dlc29_emp_cav_knights_of_the_white_wolf", "special", 2},
    {"wh3_dlc29_emp_cav_knights_of_the_white_wolf_ror", "special", 2},
    {"wh3_dlc29_emp_cav_knights_panther", "special", 2},
    {"wh3_dlc29_emp_inf_hunting_hounds", "core"},
    {"wh3_dlc29_emp_inf_hunting_hounds_ror", "special", 1},
    {"wh3_dlc29_emp_inf_teutogen_guard", "special", 2},
    {"wh3_dlc29_emp_inf_teutogen_guard_ror", "special", 2},
    {"wh3_dlc29_emp_inf_warriors_of_ulric", "core"},
    {"wh3_dlc29_emp_inf_wolf_kin", "core"},
    {"wh3_dlc29_emp_veh_celestial_hurricanum_0", "rare", 1},
    -- wh3_dlc29_group_endgame_skaven
    {"wh3_dlc29_skv_inf_clanrat_spearmen_vermintide", "core"},
    {"wh3_dlc29_skv_inf_clanrats_vermintide", "core"},
    {"wh3_dlc29_skv_inf_skavenslave_slingers_vermintide", "core"},
    {"wh3_dlc29_skv_inf_skavenslave_spearmen_vermintide", "core"},
    {"wh3_dlc29_skv_inf_skavenslaves_vermintide", "core"},
    -- wh3_dlc29_nag_group_undead_legions
    {"wh3_dlc29_vmp_cav_drakenhof_templars", "special", 2},
    {"wh3_dlc29_vmp_inf_lahmian_handmaidens_death", "special", 2},
    {"wh3_dlc29_vmp_inf_lahmian_handmaidens_shadow", "special", 2},
    {"wh3_dlc29_vmp_inf_spirit_host", "core"},
    {"wh3_dlc29_vmp_mon_morghast_archai", "special", 3},
    {"wh3_dlc29_vmp_mon_morghast_archai_ror", "rare", 2},
    {"wh3_dlc29_vmp_mon_morghast_harbingers", "rare", 2},
    {"wh3_dlc29_vmp_mon_zombie_dragon", "rare", 3},
    {"wh3_dlc29_vmp_veh_coven_throne", "rare", 2},
    -- wh_dlc03_group_beastmen
    {"wh3_dlc29_bst_mon_basilisk", "rare", 2},
    {"wh3_dlc29_bst_mon_giant_spined_chaos_beast", "rare", 2},
    {"wh3_dlc29_bst_mon_giant_spined_chaos_beast_ror", "rare", 2},
    -- wh_main_group_norsca
    {"wh3_dlc27_nor_mon_chimera_monst_arcanum_reward", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
