-- Singe's Unit Compilation (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings
    {"singe_tmb_nehek_archers", "core"},
    {"singe_tmb_nehek_bowhorse", "special", 1},
    {"singe_tmb_nehek_spearhorse", "special", 1},
    {"singe_tmb_nehek_spearknights", "special", 2},
    {"singe_tmb_nehek_swordknights", "special", 2},
    {"singe_tmb_skelly_swordhorse", "core"},
    {"singe_tmb_tmbguard_archers", "special", 1},
    -- wh2_dlc11_group_vampire_coast
    {"singe_zpotvc_bat_mortar", "special", 2},
    {"singe_zpotvc_corpse_cannon", "special", 2},
    {"singe_zpotvc_deck_burners", "special", 1},
    {"singe_zpotvc_deck_droppers_handcannons", "special", 1},
    {"singe_zpotvc_deck_snatchers", "special", 1},
    {"singe_zpotvc_depth_guard_pistols", "special", 2},
    {"singe_zpotvc_depthknight", "special", 2},
    {"singe_zpotvc_necrofex_rockets", "rare", 3},
    {"singe_zpotvc_necrofex_shrapnel", "rare", 3},
    -- wh2_dlc16_group_drycha
    {"singe_we_huntsmen_glaive", "special", 2},
    {"singe_we_huntsmen_spear", "special", 2},
    {"singe_we_huntsmen_sword", "special", 2},
    {"singe_we_sisters_oak", "special", 2},
    {"singe_we_sky_riders", "special", 2},
    -- wh2_main_def
    {"singe_def_cauldron", "special", 2},
    {"singe_def_darkstriders", "core"},
    {"singe_def_dreadfoot", "special", 2},
    {"singe_def_dreadlancers", "core"},
    {"singe_def_nightwitches", "rare", 2},
    {"singe_def_pegasilancers", "special", 2},
    {"singe_def_witchspears", "special", 1},
    -- wh2_main_hef
    {"singe_hef_dragonguard", "special", 2},
    {"singe_hef_maidenguard", "special", 2},
    {"singe_hef_swordsmen", "core"},
    {"singe_hef_watchsisters", "rare", 1},
    -- wh2_main_lzd
    {"singe_lzd_ancient_razordon", "rare", 2},
    {"singe_lzd_chameleon_slayers", "core", 1},
    {"singe_lzd_hornedone_riders", "special", 1},
    {"singe_lzd_redcrest_cohort", "core"},
    {"singe_lzd_temple_cohort", "special", 1},
    {"singe_lzd_temple_maces", "special", 2},
    {"singe_lzd_temple_riders", "special", 2},
    -- wh2_main_skv
    {"singe_sk_stormvermin_bonebreakers", "special", 2},
    {"singe_skv_plague_furnace", "rare", 3},
    {"singe_skv_plague_staves", "special", 1},
    {"singe_skv_screaming_bell", "special", 2},
    -- wh3_dlc20_group_chs_azazel
    {"singe_chs_chosen_knights", "special", 2},
    {"singe_chs_dual_chosen", "special", 2},
    {"singe_chs_dual_warrior", "special", 1},
    {"singe_chs_gorebeasts", "special", 1},
    {"singe_chs_manticore_knights", "rare", 2},
    -- wh3_dlc23_group_chaos_dwarfs
    {"singe_chd_infernal_bazuka", "rare", 2},
    {"singe_chd_infernal_magma", "rare", 2},
    {"singe_chd_rifles", "core"},
    {"singe_chd_trackers", "core"},
    {"singe_chd_zealot_berzerker", "special", 1},
    -- wh3_dlc25_group_elspeth
    {"singe_emp_arm_halberd", "core", 1},
    {"singe_emp_arm_halshield", "special", 1},
    {"singe_emp_arm_spears", "special", 1},
    {"singe_emp_arm_swords", "core", 1},
    {"singe_emp_freecom_dual", "core", 1},
    {"singe_emp_grenadiers", "special", 1},
    {"singe_emp_griffon_knight", "rare", 2},
    {"singe_emp_knight_grtswrd", "special", 1},
    {"singe_emp_light_lancers", "core"},
    {"singe_emp_pegasus_knights", "special", 2},
    {"singe_emp_state_halshield", "core", 1},
    -- wh3_dlc25_nur_tamurkhan
    {"singe_nur_monstrous_toad", "special", 2},
    {"singe_nur_plague_palanquin", "rare", 1},
    {"singe_nur_plague_riders", "special", 2},
    {"singe_nur_plague_spewers", "core"},
    {"singe_nur_plague_walkers", "core"},
    -- wh3_main_cth
    {"singe_cth_burningthunder_gunners", "core"},
    {"singe_cth_celestial_lancers", "special", 2},
    {"singe_cth_celestial_swords", "core"},
    -- wh3_main_dae
    {"singe_dae_chaos_bears", "special", 2},
    {"singe_kho_exalted_doggo", "special", 2},
    {"singe_sla_exalted_fiend", "rare", 2},
    {"singe_tze_exalted_screamer", "special", 2},
    {"singe_tze_horror_knights", "special", 2},
    {"singe_tze_screaming_chariot", "rare", 2},
    -- wh3_main_kho
    {"singe_kho_cult_blades", "core", 1},
    {"singe_kho_cult_hunters", "core"},
    {"singe_kho_cult_reavers", "special", 1},
    -- wh3_main_ksl
    {"singe_ksl_ice_riders", "special", 2},
    {"singe_ksl_tzar_halberds", "special", 2},
    -- wh3_main_pro_tze
    {"singe_tze_cultists_foot", "core"},
    {"singe_tze_cultists_horse", "core"},
    -- wh3_main_sla
    {"singe_sla_blissbarb_archers", "special", 1},
    {"singe_sla_cultist_hedonites", "core"},
    -- wh_dlc03_group_beastmen
    {"singe_bm_bestigor_shield", "special", 1},
    {"singe_bm_bestigor_spear", "special", 1},
    {"singe_bm_razorgor_behemoth", "rare", 2},
    {"singe_bm_tuskgor_herd", "special", 1},
    {"singe_bm_ungor_shard", "core"},
    {"singe_bm_ungor_vile", "core"},
    {"singe_bm_vile_manticore", "special", 1},
    -- wh_main_group_bretonnia
    {"brt_spirits_fay", "rare", 1},
    {"singe_brt_menpole_shield", "core", 1},
    {"singe_brt_serjeant_polearm", "special", 1},
    {"singe_brt_serjeant_shield", "special", 1},
    {"singe_brt_serjeant_sword", "special", 1},
    {"singe_brt_unicorn_knights", "special", 2},
    {"singe_brt_yeomen_flame", "core"},
    {"singe_brt_yeomen_pox", "core"},
    -- wh_main_group_dwarfs
    {"singe_dwf_bugman_thrower", "special", 1},
    {"singe_dwf_gyro_flame", "special", 2},
    {"singe_dwf_irondrake_drakefire", "special", 2},
    {"singe_dwf_ranger_gunners", "special", 1},
    {"singe_dwf_warriors_thrwaxe", "core"},
    -- wh_main_group_greenskins
    {"singe_grn_dung_flinga", "rare", 1},
    {"singe_grn_giant_spiders", "special", 1},
    {"singe_grn_gore_grunta", "special", 2},
    {"singe_grn_idol_hurla", "rare", 2},
    {"singe_grn_night_ladz", "core"},
    {"singe_grn_spider_chariot", "special", 1},
    {"singe_grn_wolf_pack", "special", 1},
    {"singe_grn_wyvern_black", "rare", 2},
    {"singe_grn_wyvern_savage", "rare", 2},
    -- wh_main_group_norsca
    {"singe_nor_armoured_icetroll", "special", 2},
    {"singe_nor_coldone_marauders", "special", 1},
    {"singe_nor_manticore_reavers", "rare", 2},
    {"singe_nor_marauder_riders", "core"},
    -- wh_main_group_vampire_counts
    {"singe_vc_blood_foot_duel", "special", 2},
    {"singe_vc_blood_foot_shield", "special", 2},
    {"singe_vc_graveguard_scythe", "special", 1},
    {"singe_vc_hell_knights", "special", 2},
    {"singe_vc_skelly_scythe", "core"},
    {"singe_vc_spirit_host", "special", 2},
    {"singe_vc_strigoi_terrors", "special", 2},
    {"singe_vc_zombie_dragon", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
