-- Landmarks of Legend (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- AK_kraka
    {"gutbusters_gutbusters", "rare", 2},
    {"twelve_arms_assassins", "special", 1},
    -- borders
    {"HUM_miners_0", "core"},
    {"HUM_miners_1", "core"},
    {"badland_rangers", "special", 1},
    {"colonial_militia", "core"},
    {"dalmark_gunners", "special", 1},
    {"dalmark_militia", "core"},
    {"freebooters", "rare", 1},
    {"garrison_cth_peasant_spearmen_1", "core"},
    {"seafarers", "special", 1},
    -- hol_vmp_group_koros
    {"cuileux_knights", "special", 1},
    {"damned_grail_knights", "special", 2},
    {"dec_inq_lahmian", "special", 1},
    {"ethereal_tsar_guard", "special", 1},
    {"ghost_swordsmen", "core"},
    {"lahmian_ror", "special", 1},
    {"red_abbey_monks", "core"},
    {"undead_ogre", "special", 2},
    {"undead_streltsi", "core"},
    {"undead_tzar_guard", "special", 1},
    {"vmp_bearded_skull_miners", "core"},
    {"vmp_jade_crossbowmen_0", "core"},
    {"vmp_jade_crossbowmen_1", "core"},
    {"vmp_jade_warriors_0", "core"},
    {"vmp_jade_warriors_1", "core"},
    -- mixu_mousillon
    {"vmp_depth_guard_0", "special", 2},
    {"vmp_depth_guard_1", "special", 2},
    {"vmp_swordsmen", "core"},
    -- mixu_skaeling
    {"baerson_warrior", "special", 1},
    {"dwf_nor_marauder_champions_1", "special", 2},
    {"khorne_horsemen", "core"},
    {"nor_champions_khorne", "core"},
    {"nor_shieldman", "core"},
    -- wh2_dlc11_group_vampire_coast
    {"black_gulf_orcs", "special", 1},
    {"exiled_squires", "special", 1},
    -- wh2_dlc11_group_vampire_coast_sartosa
    {"cst_leadbelchers", "special", 2},
    {"cst_maneater_0", "special", 2},
    {"cst_maneater_1", "special", 2},
    {"cst_maneater_2", "special", 2},
    {"cst_maneater_3", "special", 2},
    -- wh2_main_def
    {"def_beast_slaves", "core"},
    {"def_beast_slaves_ungors", "core"},
    {"def_lothern_sea_guard", "core"},
    {"def_raema_huntress", "special", 1},
    {"def_shadow_walkers", "special", 2},
    {"def_wardancers_0", "special", 1},
    {"def_wardancers_1", "special", 1},
    {"imperial_dragon", "rare", 2},
    {"raema_beast", "rare", 3},
    -- wh2_main_hef
    {"hef_eonir_stags", "special", 1},
    {"hef_free_company", "core"},
    {"hef_honour_guard", "rare", 1},
    {"hef_laurelorn_spears", "core"},
    {"mother_flame", "rare", 2},
    {"phoenix_riders", "special", 2},
    -- wh2_main_lzd
    {"lzd_emp_archer_0", "core"},
    {"lzd_emp_crossbowmen", "core"},
    {"lzd_emp_handgunners", "special", 1},
    {"lzd_emp_mortar", "special", 2},
    {"lzd_emp_spearmen_0", "core"},
    {"lzd_emp_spearmen_1", "core"},
    {"lzd_emp_swordsmen", "core"},
    {"lzd_emp_war_wagon", "rare", 1},
    {"sacred_saurian", "rare", 2},
    -- wh2_main_skv
    {"albino_guard", "special", 1},
    {"goblin_slave_archers", "core"},
    {"goblin_slave_spears", "core"},
    {"great_cannon_salvaged", "rare", 2},
    {"hellbeast", "rare", 3},
    {"helstorm_salvaged", "rare", 2},
    {"man_slave", "core"},
    {"mortar_salvaged", "rare", 2},
    {"treecherik_clanrats", "core"},
    {"volley_gun_salvaged", "rare", 2},
    -- wh3_dlc20_group_chs_festus
    {"children_of_doom", "special", 1},
    {"nur_nurgle_devotees", "core"},
    {"ruin_trolls", "special", 2},
    -- wh3_dlc25_group_elspeth
    {"emp_ancient_stegadon", "rare", 3},
    {"emp_carnosaur_0", "rare", 2},
    {"emp_chameleon_skinks_0", "special", 1},
    {"emp_chameleon_stalkers_0", "rare", 1},
    {"emp_cold_ones_1", "special", 1},
    {"emp_gryphon_legion", "special", 2},
    {"emp_ice_guard_1", "rare", 1},
    {"emp_kroxigors", "special", 2},
    {"emp_queen_bess", "rare", 2},
    {"emp_saurus_spearmen_0", "core"},
    {"emp_skink_cohort_0", "core"},
    {"emp_skink_skirmishers_0", "core"},
    {"emp_terradon_riders_0", "special", 1},
    {"expedition_archers", "core"},
    {"westland_hunters", "special", 1},
    {"wlc_guard", "special", 2},
    -- wh3_dlc25_nur_tamurkhan
    {"nur_lepers", "special", 1},
    -- wh3_main_cth
    {"cathay_ogres", "core"},
    -- wh3_main_dae
    {"sla_dryads", "core"},
    {"sla_eternal_guard", "core"},
    {"sla_forest_dragon", "rare", 2},
    {"sla_forsaken", "core"},
    {"sla_treekin", "special", 2},
    {"sla_treeman", "rare", 3},
    {"sla_wardancers", "core"},
    -- wh3_main_def_morathi
    {"def_gor_herd", "core"},
    {"def_minotaurs", "special", 2},
    -- wh3_main_group_belakor
    {"bst_giant_spider", "special", 1},
    {"shadowgor", "core"},
    {"shadowgor_bestigor", "special", 1},
    -- wh3_main_ksl
    {"brother_bears", "special", 2},
    {"brotherhood_ranger_templars", "special", 1},
    {"dolgan_warriors", "rare", 1},
    {"ksl_acolytes", "core"},
    {"ksl_dryads", "core"},
    {"ksl_glade_riders", "core"},
    {"ksl_great_cannon", "special", 2},
    {"ksl_mortar", "special", 2},
    {"ksl_orthodoxy_ror", "special", 1},
    {"ksl_rocket_battery", "rare", 2},
    {"ksl_steam_tank", "rare", 3},
    {"ksl_volley_gun", "rare", 2},
    {"ksl_war_wagon_mortar", "rare", 2},
    {"ksl_wardancers", "special", 1},
    {"ksl_wildwood_rangers", "special", 2},
    -- wh_dlc03_group_beastmen
    {"bst_giant_wolves", "special", 1},
    {"chs_chaos_spawn", "rare", 1},
    {"lakemen", "core"},
    {"lakemen_great_weapons", "rare", 1},
    {"ymir", "special", 2},
    -- wh_dlc05_group_wood_elves
    {"dragonling_pack", "rare", 1},
    {"wef_flamespyre", "rare", 1},
    {"wef_hydra", "rare", 2},
    {"worldroot_serpent", "rare", 3},
    -- wh_main_group_bretonnia
    {"sir_baldrin_reliquae", "rare", 1},
    -- wh_main_group_dwarfs
    {"azul_guard", "core"},
    {"bearded_skull_miners", "special", 1},
    {"sons_of_gunnisson", "special", 1},
    -- wh_main_group_greenskins
    {"blorgar", "rare", 3},
    {"blue_orc", "core"},
    {"feral_arachnarok", "rare", 2},
    -- wh_main_group_vampire_counts
    {"vmp_greastswords", "special", 1},
    {"vmp_reiksguard", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
