-- OvN Lost Factions: Dread King Legions (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- ovn_dread_king
    {"dread_inf_tomb_guard_0", "special", 1},
    {"dread_inf_tomb_guard_1", "special", 1},
    {"dread_mon_ushabti_0", "special", 2},
    {"dread_mon_ushabti_1", "special", 2},
    {"ovn_dk_art_bone_throwers", "special", 2},
    {"ovn_dk_art_polybolos_ror", "special", 2},
    {"ovn_dk_art_screaming_skull_ballista", "rare", 1},
    {"ovn_dk_cav_black_grail_knights_ror", "special", 2},
    {"ovn_dk_cav_ephalian_ror", "special", 1},
    {"ovn_dk_cav_hexwraiths", "special", 2},
    {"ovn_dk_cav_royal_guard_cavalry", "special", 1},
    {"ovn_dk_cav_royal_guard_lancers", "special", 2},
    {"ovn_dk_cav_skeleton_horsemen_0", "core"},
    {"ovn_dk_cav_skeleton_horsemen_archers_0", "core"},
    {"ovn_dk_inf_brigands_ror", "core"},
    {"ovn_dk_inf_cairn_wraiths", "special", 1},
    {"ovn_dk_inf_catacomb_guardians_ror", "special", 2},
    {"ovn_dk_inf_crypt_ghouls", "core"},
    {"ovn_dk_inf_mummies", "special", 1},
    {"ovn_dk_inf_mummies_ror", "special", 2},
    {"ovn_dk_inf_skeleton_hoplites", "special", 1},
    {"ovn_dk_inf_skeleton_javelinmen", "core"},
    {"ovn_dk_inf_skeleton_pikemen", "special", 1},
    {"ovn_dk_inf_spartan_ror", "special", 1},
    {"ovn_dk_inf_thessos_ror", "special", 1},
    {"ovn_dk_inf_tomb_guardian", "special", 1},
    {"ovn_dk_inf_tomb_guardian_great_weapons", "special", 1},
    {"ovn_dk_inf_tomb_guardian_peltasts", "special", 1},
    {"ovn_dk_inf_wights_ror", "special", 1},
    {"ovn_dk_mon_bone_hydra", "rare", 2},
    {"ovn_dk_mon_dire_wolves", "core"},
    {"ovn_dk_mon_fell_bats", "core"},
    {"ovn_dk_mon_skeletal_minotaurs", "special", 2},
    {"ovn_dk_mon_skeleton_elephant", "special", 2},
    {"ovn_dk_mon_skeleton_elephant_ror", "rare", 3},
    {"ovn_dk_mon_skeleton_giant", "rare", 2},
    {"ovn_dk_veh_mortis_engine_0", "rare", 3},
    {"ovn_dk_veh_skeleton_archer_chariot", "core"},
    {"ovn_dk_veh_skeleton_chariot", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
