-- Dawi Gunpowder Units (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_dwarfs
    {"derpy_dwf_chaingunners", "special", 2},
    {"derpy_dwf_eng_tank", "rare", 3},
    {"derpy_dwf_eng_tankette", "rare", 2},
    {"derpy_dwf_gunaxe_slayers_malakai", "special", 2},
    {"derpy_dwf_gunaxe_thunderers", "special", 2},
    {"derpy_dwf_gunaxe_thunderers_malakai", "special", 2},
    {"derpy_dwf_ironhog_repeaters", "special", 2},
    {"derpy_dwf_ironhog_repeaters_malakai", "special", 2},
    {"derpy_dwf_karaklad_ironbulwarks", "special", 2},
    {"derpy_dwf_karaklad_ironbulwarks_malakai", "special", 2},
    {"derpy_dwf_stonebreakers", "special", 1},
    {"derpy_dwf_stonebreakers_malakai", "special", 1},
    {"derpy_dwf_storm_dual_pistol", "special", 2},
    {"derpy_dwf_storm_dual_pistol_malakai", "special", 2},
    {"derpy_dwf_storm_goats_grenade", "special", 2},
    {"derpy_dwf_storm_goats_grenade_malakai", "special", 2},
    {"derpy_dwf_valley_guard", "special", 2},
    {"derpy_gp_25mm", "rare", 2},
    {"derpy_gp_25mm_malakai", "rare", 2},
    {"derpy_gp_8mm", "rare", 2},
    {"derpy_gp_8mm_malakai", "rare", 2},
    {"derpy_gp_combat_engineers", "special", 2},
    {"derpy_gp_drakkfire_piercers", "rare", 2},
    {"derpy_gp_dwf_flame_mortar", "rare", 2},
    {"derpy_gp_dwf_flame_mortar_malakai", "rare", 2},
    {"derpy_gp_dwf_great_mortar", "rare", 2},
    {"derpy_gp_dwf_mortar", "special", 2},
    {"derpy_gp_dwf_mortar_malakai", "special", 2},
    {"derpy_gp_dwf_mountainbreaker", "rare", 2},
    {"derpy_gp_dwf_stonebreaker_malakai", "special", 2},
    {"derpy_gp_gunaxe_slayers", "special", 2},
    {"derpy_gp_homing", "special", 3},
    {"derpy_gp_homing_malakai", "special", 3},
    {"derpy_gp_landship_0", "rare", 3},
    {"derpy_gp_landship_1", "rare", 2},
    {"derpy_gp_landship_1_beer", "rare", 3},
    {"derpy_gp_landship_1_beer_malakai", "rare", 3},
    {"derpy_gp_landship_1_malakai", "rare", 2},
    {"derpy_gp_landship_2", "rare", 3},
    {"derpy_gp_landship_3", "rare", 3},
    {"derpy_gp_landship_3_huge", "rare", 3},
    {"derpy_gp_landship_3_ror", "rare", 3},
    {"derpy_gp_multi_aa", "rare", 2},
    {"derpy_gp_multi_aa_malakai", "rare", 2},
    {"dwf_gp_ironblasters", "rare", 2},
    {"dwf_gp_ironblasters_malakai", "rare", 2},
    {"dwf_gp_quarrelstorm_01", "special", 2},
    {"dwf_gp_quarrelstorm_01_malakai", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
