-- The Phoenix Court (High Elf Politics) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_hef
    {"cr_als_hef_mon_merwyrm_0", "rare", 2},
    {"cr_als_hef_mon_merwyrm_summoned", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
