-- Sigmar's Heirs, an Empire Overhaul (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc25_group_elspeth
    {"dummy_unit_1", "core"},
    {"dummy_unit_2", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
