-- Shunraiki's Cathay Unit Pack (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_cp1_group_cth_bhashiva
    {"shun_azurestone_guardian", "special", 3},
    {"shun_dragon_guard_skirmisher", "special", 2},
    {"shun_eastern_provinces_shieldmaidens", "rare", 1},
    {"shun_longma_skirmisher_ror", "special", 2},
    {"shun_tribe_huntsmen", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
