-- Vampires of Nehekhara (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings_arkhan
    {"lsh_nehekvamp_mummy_zombie_arkhan", "core", 1},
    {"lsh_nehekvamp_scarab_bat2", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
