-- Super Units - All Factions Compilation - End Times Escalation (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings
    {"wh2_dlc09_tmb_mon_tomb_scorpion_0_ete", "rare", 2},
    -- wh2_main_hef
    {"wh3_dlc27_hef_inf_ships_company_ete", "special", 2},
    {"wh3_dlc27_hef_inf_ships_company_ror_ete", "rare", 2},
    {"wh3_dlc27_hef_mon_merwyrm_ror_ete_2", "rare", 3},
    {"wh3_dlc27_hef_mon_sea_elemental_ete_ror", "rare", 3},
    -- wh2_main_lzd
    {"wh2_dlc13_lzd_mon_sacred_kroxigors_0_ete_nakai", "rare", 2},
    -- wh2_main_skv
    {"wh2_dlc16_skv_mon_hell_pit_abomination_ror_0_ete", "rare", 3},
    -- wh3_cp1_group_cth_bhashiva
    {"wh3_cp1_cth_inf_stalkers_throwing_disc_ete", "special", 1},
    {"wh3_dlc24_cth_mon_great_moon_bird_ete", "special", 3},
    -- wh3_dlc20_group_chs_azazel
    {"wh3_dlc20_chs_inf_chaos_marauders_msla_ete_ror", "rare", 2},
    {"wh3_dlc27_nor_cav_kurgan_horsemen_dualweapons_ete_ror", "rare", 2},
    -- wh3_dlc20_group_chs_vilitch
    {"wh3_dlc24_tze_mon_mutalith_vortex_beast_ete", "rare", 3},
    -- wh3_dlc23_group_chaos_dwarfs
    {"wh3_dlc23_chd_inf_infernal_guard_fireglaives_ete_ror", "rare", 2},
    {"wh3_dlc23_chd_mon_kdaai_destroyer_ete_2", "rare", 3},
    -- wh3_dlc25_group_elspeth
    {"wh_dlc04_emp_art_sunmaker_0_ete", "rare", 2},
    {"wh_dlc04_emp_cav_zintlers_reiksguard_0_ete", "rare", 2},
    {"wh_main_emp_cav_reiksguard_ete", "rare", 2},
    -- wh3_main_dae
    {"wh3_dlc20_chs_inf_chaos_marauders_mnur_ete_ror", "rare", 2},
    {"wh3_dlc26_kho_mon_bloodbeast_of_khorne_ete", "rare", 2},
    -- wh_dlc03_group_beastmen
    {"wh2_dlc17_bst_mon_ghorgon_ror_0_ete", "rare", 2},
    {"wh2_dlc17_bst_mon_jabberslythe_ror_0_ete", "rare", 3},
    {"wh3_dlc25_nur_mon_toad_dragon_ete_bst", "rare", 3},
    {"wh3_dlc25_nur_mon_toad_dragon_ete_bst_ror", "rare", 3},
    {"wh3_dlc26_kho_mon_bloodbeast_of_khorne_ete_bst", "rare", 2},
    {"wh3_dlc27_bst_inf_slaangors_ete", "rare", 1},
    {"wh3_dlc27_bst_mon_chimera_ete", "rare", 2},
    {"wh3_dlc27_bst_mon_chimera_ror_ete", "rare", 2},
    {"wh3_dlc27_bst_mon_cockatrice_ete", "rare", 2},
    {"wh3_dlc27_bst_mon_preyton_ete", "rare", 3},
    {"wh3_dlc27_bst_mon_preyton_ror_ete", "rare", 2},
    {"wh_dlc03_bst_inf_bestigor_herd_0_ete", "rare", 1},
    -- wh_main_group_dwarfs
    {"wh3_dlc25_dwf_art_goblin_hewer_ete", "rare", 2},
    {"wh3_dlc25_dwf_art_goblin_hewer_ete_ror", "special", 2},
    {"wh3_dlc25_dwf_inf_slayer_pirates_ete", "rare", 2},
    {"wh3_dlc25_dwf_inf_slayer_pirates_ror_ete", "rare", 1},
    {"wh_dlc06_dwf_art_gob_lobber_0_ete", "rare", 2},
    {"wh_main_dwf_art_organ_gun_ete", "rare", 2},
    {"wh_main_dwf_art_organ_gun_ete_ror", "rare", 2},
    {"wh_main_dwf_veh_gyrocopter_0_ete_ror", "special", 2},
    -- wh_main_group_greenskins
    {"wh2_dlc15_grn_mon_river_trolls_ror_0_ete", "rare", 2},
    {"wh3_dlc26_grn_cav_mangler_squig_ete", "rare", 1},
    {"wh3_dlc26_grn_mon_colossal_squig_ete", "rare", 2},
    {"wh3_dlc26_grn_mon_colossal_squig_ror_ete", "rare", 2},
    -- wh_main_group_norsca
    {"1wyrm_ror", "rare", 2},
    {"wh3_dlc27_nor_cav_kurgan_horsemen_greatweapons_ete", "rare", 2},
    {"wh3_dlc27_nor_inf_marauder_bearmen_ete", "special", 2},
    {"wh3_dlc27_nor_inf_marauder_bearmen_ete_ror", "special", 2},
    {"wh_dlc08_nor_mon_frost_wyrm_0_ete", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
