-- graetor's Bretonnian Holy Orders (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_bretonnia
    {"wh_main_brt_cav_knights_hospital_0", "core"},
    {"wh_main_brt_cav_knights_lazarite_0", "special", 2},
    {"wh_main_brt_cav_knights_sepulchre_0", "special", 1},
    {"wh_main_brt_cav_knights_temple_0", "core"},
    {"wh_main_brt_inf_knights_hospital_0", "special", 2},
    {"wh_main_brt_inf_knights_lazarite_0", "special", 2},
    {"wh_main_brt_inf_knights_sepulchre_0", "special", 1},
    {"wh_main_brt_inf_knights_temple_0", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
