-- 『龙战于野』震旦兵种包(Cathay Units Patch:Dragons Battle in the Field) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_cth
    {"YL_cgs", "core"},
    {"YL_chlw", "special", 1},
    {"YL_hytj", "special", 2},
    {"YL_lycs", "special", 1},
    {"YL_lysw", "special", 3},
    {"YL_pjcw", "rare", 2},
    {"YL_sxdw", "special", 2},
    {"YL_xtw", "special", 1},
    {"YL_yhcf", "rare", 3},
    {"YL_zsyw", "special", 3},
    {"YL_zyxj", "special", 2},
    {"YLlyxw", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
