-- SCM's LCCP, 15 new factions for IEE! (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_hef
    {"hef_calith_gatekeepers", "special", 2},
    -- wh_main_group_vampire_counts
    {"rhox_lccp_vmp_giant", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
