-- Scrambled Eggs' Vampire Coast Unit Expansion (+ Fell Bat Mount) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc11_group_vampire_coast
    {"seggs_cst_art_magic_cannon", "special", 2},
    {"seggs_dlc11_cst_art_bat_mortar", "special", 2},
    {"seggs_dlc11_cst_ghost_helmsmen", "special", 2},
    {"seggs_dlc11_cst_inf_deck_gunners_1", "special", 1},
    {"seggs_dlc11_cst_mon_altar_of_the_abyss", "special", 2},
    {"seggs_dlc11_cst_mon_bloated_corpse_1", "core"},
    {"seggs_dlc11_cst_mon_bloated_corpse_2", "core"},
    {"seggs_suicide_bats", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
