-- Mortal Warriors of Nurgle (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_nur
    {"nrg_jabber", "rare", 2},
    {"pk_plague_blightking", "special", 2},
    {"pk_plague_brethren", "core", 1},
    {"pk_plague_halberds", "special", 1},
    {"pk_plague_halberds_ror", "special", 1},
    {"pk_plague_knights", "special", 2},
    {"pk_plague_knights_ror", "special", 2},
    {"pk_plague_ogres", "special", 2},
    {"pk_plague_ogres_dw", "core", 1},
    {"pk_plague_ogres_dw_ror", "special", 2},
    {"pk_plague_ogres_ror", "special", 2},
    {"pk_plague_scythe", "special", 1},
    {"pk_plague_scythe_ror", "special", 1},
    {"pk_plague_warriors", "core", 1},
    {"pk_plague_warriors_ror", "special", 1},
    {"str_plague_guns", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
