-- Chaos Ogres (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc20_group_chs_azazel
    {"frb_chaos_ogre_brawlers_0", "special", 1},
    {"frb_chaos_ogre_brawlers_1", "special", 1},
    {"frb_chaos_ogre_fighters_0", "special", 1},
    {"frb_chaos_ogre_fighters_1", "special", 1},
    {"frb_chaos_ogre_fighters_2", "special", 2},
    {"frb_chaos_ogre_slaanesh_0", "special", 2},
    {"frb_chaos_ogre_warmongers_0", "special", 2},
    {"frb_chaos_ogre_warmongers_1", "special", 2},
    -- wh3_dlc20_group_chs_festus
    {"frb_chaos_ogre_nurgle_0", "special", 2},
    -- wh3_dlc20_group_chs_valkia
    {"frb_chaos_ogre_khorne_0", "special", 2},
    -- wh3_dlc20_group_chs_vilitch
    {"frb_chaos_ogre_tzeentch_0", "special", 2},
    -- wh3_dlc23_group_chaos_dwarfs
    {"frb_chaos_ogre_brawlers_0_chd", "special", 1},
    {"frb_chaos_ogre_brawlers_1_chd", "special", 1},
    {"frb_chaos_ogre_fighters_0_chd", "special", 1},
    {"frb_chaos_ogre_fighters_1_chd", "special", 1},
    {"frb_chaos_ogre_fighters_2_chd", "special", 2},
    {"frb_chaos_ogre_warmongers_0_chd", "special", 2},
    {"frb_chaos_ogre_warmongers_1_chd", "special", 2},
    -- wh3_main_group_belakor
    {"frb_chaos_wastes_behemoth_0", "rare", 3},
    -- wh_main_group_chaos
    {"frb_forsaken_gnoblars_0", "core", 1},
    {"frb_forsaken_gnoblars_fighters_0", "core", 1},
    {"frb_forsaken_gnoblars_fighters_1", "core", 1},
    {"frb_forsaken_gnoblars_warriors_0", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
