-- Shadowman's Blood-Ragers! (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_dae
    {"dae_blood_rager", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
