-- Nurgle Rotting Monstruosities (New monster units for Nurgle (and Beastmen too) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc20_group_chs_festus
    {"nurgle_abomination", "rare", 2},
    {"nurgle_giant", "rare", 2},
    {"rot_idol", "rare", 3},
    {"withered_omen", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
