-- The Jade-Blooded Vampires: Islanders of the Moon (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_hef
    {"hef_iotm_islanders", "core"},
    {"hef_iotm_islanders_hb", "special", 1},
    -- wh3_jade_vampires_IotM_group
    {"jbv_doctor", "rare", 2},
    {"jbv_islanders", "core"},
    {"jbv_lady_yayi", "rare", 3},
    {"jbv_nurses", "special", 2},
    {"jbv_nurses_2", "special", 2},
    {"jbv_patient_man", "rare", 2},
    {"jbv_patient_mob", "special", 2},
    {"jbv_patient_woman", "rare", 2},
    {"jbv_wraith", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
