-- 【Deer24高等精灵单位包】荣光国度（ HEF UNITS PATCH Glorious Nation） (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc11_cst_shanty_dragon_spine_privateers
    {"DEERHEF_AISAANGQISHI", "special", 2},
    {"DEERHEF_BAISHILIECHANG", "special", 3},
    {"DEERHEF_BAITAJIANSHENG", "rare", 1},
    {"DEERHEF_DIGONGTONGWEI", "special", 3},
    {"DEERHEF_FENGHUANGSHOUWEI", "special", 3},
    {"DEERHEF_HAIMEN", "special", 2},
    {"DEERHEF_LONGZHU", "rare", 3},
    {"DEERHEF_NAJIARUISIHEIWEI", "special", 3},
    {"DEERHEF_NVQISHI", "special", 1},
    {"DEERHEF_NVQISHI1", "special", 2},
    {"DEERHEF_SHOUWANGZHE", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
