-- 万世天朝/Great Harmony Sentinel Overhaul Beta (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings
    {"ghs_main_tmb_cav_ostrich_rider_summon", "core"},
    {"ghs_main_tmb_mon_flying_necrosphinx_usirian", "rare", 3},
    {"ghs_main_tmb_mon_heirotitan_0_summoned", "rare", 3},
    -- wh2_dlc16_group_drycha
    {"ghs_main_wef_inf_sisters_thorn_moonfire_wall_of_thorns", "core"},
    -- wh2_main_hef
    {"ghs_wm_hef_dragonship", "rare", 3},
    -- wh3_cp1_group_cth_bhashiva
    {"ghs_main_cth_inf_iron_dragon_modao", "special", 2},
    {"ghs_main_cth_inf_iron_dragon_modao_ror", "rare", 1},
    -- wh3_dlc20_group_chs_azazel
    {"ghs_main_sla_mon_titan", "rare", 3},
    -- wh3_dlc20_group_chs_valkia
    {"ghs_main_kho_mon_titan", "rare", 3},
    -- wh3_dlc20_group_chs_vilitch
    {"ghs_main_tze_mon_titan", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
