-- The Ten Kingdoms (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_hef
    {"loupi_avelorn_cav", "special", 1},
    {"loupi_avelorn_treeman_ror", "rare", 3},
    {"loupi_chracian_pikes", "special", 1},
    {"loupi_chracian_pikes_ror", "special", 2},
    {"loupi_dragon_gate_guard", "special", 2},
    {"loupi_dragon_prince_foot", "special", 1},
    {"loupi_eagle_claw_ror", "special", 2},
    {"loupi_eagle_riders", "rare", 3},
    {"loupi_ellyrian_lancers", "core"},
    {"loupi_ellyrian_lancers_ror", "special", 2},
    {"loupi_knights_of_anlec", "special", 2},
    {"loupi_knights_of_anlec_ror", "special", 2},
    {"loupi_mistwalkers", "rare", 1},
    {"loupi_saphery_pegasus", "rare", 2},
    {"loupi_sea_ranger", "special", 1},
    {"loupi_shadow_warrior_1", "special", 1},
    {"loupi_shore_riders", "special", 1},
    {"loupi_silverin_ror", "special", 1},
    {"loupi_sisters_avelorn_ror", "rare", 1},
    {"loupi_swordmaster_ror", "special", 2},
    {"loupi_tiranoc_ror", "special", 2},
    {"loupi_ulthane", "rare", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
