-- Bretonnian War Castle (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_bretonnia
    {"gorilla_brt_veh_war_castle", "rare", 3},
    {"gorilla_brt_veh_war_castle_siege", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
