-- Champions Of Undeath: Conquest Of The Blood Dragons (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- hol_vmp_group_koros
    {"damned_knights_of_the_realm", "special", 2},
    -- wh3_dlc25_group_elspeth
    {"bm_db_witch_hunter_kill_squad", "special", 2},
    {"ootww_1h_knight", "special", 2},
    {"ootww_2h_knight", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
