-- Vlad's Dominion Faction Project (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- dom_dominion
    {"dom_nightshade", "special", 1},
    {"dom_shadowfire", "special", 2},
    {"ksl_urbem_eversorem", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
