-- Dead's Cathay Unit Pack (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_cth
    {"bannerman", "special", 1},
    {"battle_turtle", "rare", 2},
    {"cth_juggernaut_crew", "special", 2},
    {"cth_tiger", "core", 1},
    {"cth_war_elephant", "special", 2},
    {"dead_firelancers", "special", 2},
    {"nangau_rifles", "special", 1},
    {"peasant_cav_archers", "core"},
    {"rocket_troops", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
