-- Dead of the Orient - Immortal Empires (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_rogue_the_wandering_dead
    {"cth_cannibal", "special", 2},
    {"cth_jiangshi_p", "special", 2},
    {"cth_revenant", "core"},
    {"cth_skeleton", "core"},
    -- wh3_main_cth
    {"cth_buddha", "rare", 2},
    {"cth_legion", "rare", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
