-- SCM Might of the Maw (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_ogr
    {"motm_hollowbellies_ror", "special", 2},
    {"singe_ogk_irongut_dual", "special", 1},
    {"singe_ogk_irongut_ironfists", "special", 1},
    {"singe_ogk_mournfang_pack", "special", 2},
    {"singe_ogk_rhinox_herd", "core"},
    {"singe_ogk_rocketspitters", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
