-- Imperial Elite || Empire Late Game Unit Mod (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc25_group_elspeth
    {"mod_emp_guard", "special", 2},
    {"mod_emp_priest", "special", 2},
    {"mod_emp_soldier", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
