-- Units of Naggaroth (Dark Elf unit expansion) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_def
    {"hawk_summoned", "core"},
    {"wolf_summoned", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
