-- SCM Marienburg (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- rhox_mar_military
    {"hkrul_burgher", "core"},
    {"hkrul_fooger_ror", "core"},
    {"hkrul_mar_art_paixhan_ror", "special", 2},
    {"hkrul_mar_black_caps", "core"},
    {"hkrul_mar_bordermen_ror", "special", 2},
    {"hkrul_mar_cav_rijders", "core", 1},
    {"hkrul_mar_cav_rijders_crossbow", "core"},
    {"hkrul_mar_culverin", "special", 2},
    {"hkrul_mar_handguns", "core"},
    {"hkrul_mar_hellblaster", "rare", 2},
    {"hkrul_mar_hellstorm", "rare", 2},
    {"hkrul_mar_knights_griffon", "rare", 2},
    {"hkrul_mar_knights_mariner", "core"},
    {"hkrul_mar_mananns_blades_ror", "core"},
    {"hkrul_mar_mortar", "special", 2},
    {"hkrul_mar_naval_paixhan", "special", 2},
    {"hkrul_mar_qual", "core", 1},
    {"hkrul_mar_qual_great", "core"},
    {"hkrul_mar_riverwarden", "core"},
    {"hkrul_mar_riverwarden_ror", "core"},
    {"hkrul_mar_sons_of_manann", "special", 2},
    {"hkrul_mar_talons", "special", 1},
    {"hkrul_mar_teuling", "special", 1},
    {"hkrul_privateers", "special", 1},
    {"hkrul_privateers_dual_swords", "core"},
    {"ovn_mar_inf_knights_mariner_0", "special", 1},
    {"rhox_mar_cst_inf_sartosa_free_company_0", "core"},
    {"rhox_mar_cst_inf_sartosa_militia_0", "core"},
    -- wh2_dlc09_rogue_pilgrims_of_myrmidia
    {"hkrul_mar_inf_crossbow", "core"},
    -- wh2_dlc11_cst_rogue_freebooters_of_port_royale
    {"hkrul_mar_art_scheepskanon", "special", 2},
    {"hkrul_mar_inf_goedendagers", "core"},
    {"hkrul_mar_inf_halberd", "core"},
    {"hkrul_mar_inf_handgun", "core"},
    {"hkrul_mar_inf_swords", "core"},
    -- wh3_dlc25_group_elspeth
    {"hkrul_carriers", "special", 2},
    {"hkrul_carriers_ror", "special", 2},
    {"hkrul_klumpf", "core"},
    {"hkrul_mar_cleansing_flame", "special", 2},
    {"hkrul_mar_defenders", "special", 1},
    {"hkrul_mar_inf_boogschutter", "core"},
    {"hkrul_mar_inf_greatsword", "special", 1},
    {"hkrul_mar_knights_mariner_fmc", "core"},
    {"hkrul_pion", "core"},
    -- wh_main_group_empire
    {"hkrul_manann_flagellant", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
