-- Whc's Cathay unit pack:【War under Heaven】 (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_cp1_group_cth_bhashiva
    {"cth_cav_bayara", "special", 2},
    {"cth_cav_guanning_firelancer", "special", 1},
    {"cth_east_mingqing_gunner_grenadier", "core", 1},
    {"cth_east_mingqing_jade_qijun_1", "core"},
    {"cth_east_mingqing_jade_qijun_2", "special", 1},
    {"cth_east_mingqing_minzu_1", "special", 2},
    {"cth_east_mingqing_peasant_yijun_1", "core", 1},
    {"cth_east_mingqing_peasant_yijun_2", "core"},
    {"cth_inf_beiweijun", "special", 2},
    {"cth_inf_great_bastion_sentinels", "special", 2},
    {"cth_north_suitang_cav_peasant", "core", 1},
    {"cth_north_suitang_jade_shuwei_1", "core", 1},
    {"cth_north_suitang_jade_shuwei_2", "special", 1},
    {"cth_north_suitang_jade_shuwei_4", "special", 1},
    {"cth_north_suitang_longwei_weijun_2", "special", 2},
    {"cth_north_suitang_peasant_shuzu_1", "core"},
    {"cth_north_suitang_peasant_shuzu_2", "core"},
    {"cth_south_songyuan_beast_huban_dog", "special", 1},
    {"cth_south_songyuan_cav_longma", "special", 2},
    {"cth_south_songyuan_jade_xiangbing_1", "core"},
    {"cth_south_songyuan_jade_xiangbing_2", "special", 1},
    {"cth_south_songyuan_jade_xiangbing_4", "special", 1},
    {"cth_south_songyuan_peasant_liehu_1", "core", 1},
    {"cth_south_songyuan_peasant_liehu_2", "core", 1},
    {"cth_west_daqin_peasant_ruishi_1", "core"},
    {"cth_west_daqin_peasant_ruishi_2", "core"},
    {"cth_west_qinhan_cav_jade", "special", 1},
    {"cth_west_qinhan_cav_peasant", "core", 1},
    {"cth_west_qinhan_jade_wuzu_1", "core", 1},
    {"cth_west_qinhan_jade_wuzu_2", "special", 1},
    {"cth_west_qinhan_jade_wuzu_4", "special", 1},
    {"cth_west_qinhan_longwei_pro_liujin_2", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
