-- [Zerooz] 兵种合集 (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc25_group_elspeth
    {"emp_inf_deaths_heads", "core"},
    -- wh_dlc03_group_beastmen
    {"bst_cav_doom_tzaangors", "special", 2},
    {"bst_cav_doom_tzaangors_archer", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
