-- Vanilla + DLC (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- dust_gutrot_military_group
    {"wh3_main_nur_inf_forsaken_0_warriors", "core"},
    -- wh2_dlc11_group_vampire_coast
    {"wh2_dlc11_cst_cav_knights_errant_2", "core"},
    {"wh2_dlc14_skv_inf_stormvermin_1_summoned", "core"},
    -- wh2_main_hef_imrik
    {"wh2_dlc15_hef_mon_forest_dragon_0", "rare", 3},
    -- wh2_main_skv
    {"wh2_dlc11_cst_mon_rotting_prometheans_summoned_0", "special", 1},
    -- wh3_dlc20_group_chs_valkia
    {"wh3_main_pro_kho_inf_flesh_hounds_of_khorne_simaergul_0", "special", 2},
    -- wh3_dlc29_group_endgame_skaven
    {"wh3_dlc29_skv_inf_clanrat_spearmen_vermintide", "core"},
    {"wh3_dlc29_skv_inf_clanrats_vermintide", "core"},
    {"wh3_dlc29_skv_inf_skavenslave_slingers_vermintide", "core"},
    {"wh3_dlc29_skv_inf_skavenslave_spearmen_vermintide", "core"},
    {"wh3_dlc29_skv_inf_skavenslaves_vermintide", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
