-- Nanu's Pirates of Sartosa Overhaul (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc11_cst_rogue_bleak_coast_buccaneers
    {"sartosa_buccaneer_deck_gun_weapon_team", "special", 2},
    {"sartosa_buccaneer_drakefire_cannon", "rare", 2},
    {"sartosa_buccaneer_torpedo_weapon_team", "special", 2},
    {"sartosa_buccaneers_axe_and_pistol", "core"},
    {"sartosa_buccaneers_blunderbuss", "core"},
    {"sartosa_buccaneers_dual_axes", "core"},
    -- wh2_dlc11_cst_rogue_freebooters_of_port_royale
    {"sartosa_pirate_artillery_cannon", "special", 2},
    {"sartosa_pirate_artillery_mortar", "special", 2},
    {"sartosa_pirate_halberds", "core"},
    {"sartosa_pirate_handguns", "special", 1},
    {"sartosa_privateers", "special", 1},
    {"sartosa_privateers_dual_swords", "special", 1},
    {"sartosa_privateers_halberds", "core"},
    -- wh2_dlc11_cst_rogue_the_churning_gulf_raiders
    {"sartosa_norscan_raider_great_weapons", "core", 1},
    {"sartosa_norscan_raiders", "core", 1},
    {"sartosa_norscan_reaver_axe_and_shield", "special", 2},
    {"sartosa_norscan_reaver_dual_axes", "special", 1},
    {"sartosa_norscan_reaver_halberds", "special", 2},
    {"sartosa_norscan_whalers", "core"},
    -- wh2_dlc11_group_vampire_coast_sartosa
    {"sartosa_buccaneer_deck_gun_weapon_team_ror", "special", 2},
    {"sartosa_buccaneer_drakegun_weapon_team", "special", 2},
    {"sartosa_buccaneer_mortar_ror", "special", 2},
    {"sartosa_depth_guard_jenny_ror", "special", 2},
    {"sartosa_leviathan", "rare", 3},
    {"sartosa_norscan_raiders_ror", "core"},
    {"sartosa_norscan_reaver_captain_chariot", "special", 2},
    {"sartosa_norscan_reaver_ror", "special", 2},
    {"sartosa_norscan_warhounds", "core", 1},
    {"sartosa_pirate_halberds_ror", "core"},
    {"sartosa_pirate_handguns_ror", "special", 1},
    {"sartosa_privateers_james_ror", "special", 1},
    {"sartosa_privateers_ror", "special", 2},
    {"sartosa_privateers_roth_ror", "special", 2},
    {"sartosa_promethean_riders", "special", 2},
    {"sartosa_promethean_riders_davey_ror", "special", 2},
    {"sartosa_prometheans", "special", 2},
    {"sartosa_prometheans_ror", "special", 2},
    {"sartosa_saboteurs", "special", 1},
    {"sartosa_smugglers", "core", 1},
    {"sartosa_smugglers_ror", "core"},
    {"sartosa_smugglers_sammy_ror", "special", 2},
    {"sartosa_zombie_carnosaur", "rare", 2},
    {"sartosa_zombie_dragon", "rare", 3},
    {"sartosa_zombie_dread_saurian", "rare", 2},
    {"sartosa_zombie_kharibdyss", "rare", 3},
    {"sartosa_zombie_mammoth", "rare", 2},
    -- wh2_main_rogue_pirates_of_the_far_sea
    {"cathay_pirate_bombard", "special", 2},
    {"cathay_pirate_crossbows", "core"},
    {"cathay_pirate_dual_swords", "core"},
    {"cathay_pirate_fire_rain_rocket_battery", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
