-- Dwarf Mechanized Forces (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_dwarfs
    {"cody_dwf_art_mortar", "special", 2},
    {"cody_dwf_mon_war_bear", "special", 2},
    {"cody_dwf_veh_juggernaut", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
