-- Regiments of Renown - All Factions by Pwner1 (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings
    {"wh2_dlc09_tmb_inf_tomb_guard_1_", "special", 1},
    {"wh2_dlc09_tmb_mon_heirotitan_0_", "rare", 3},
    {"wh2_dlc09_tmb_mon_ushabti_0_", "special", 2},
    -- wh3_dlc20_group_chs_azazel
    {"grn_brutes1", "special", 1},
    {"grn_brutes2", "special", 2},
    {"grn_brutes3", "special", 1},
    {"grn_brutes4", "special", 2},
    {"grn_brutes6", "special", 2},
    {"grn_brutes7", "special", 2},
    {"secrets", "rare", 3},
    {"wh3_main_chs_art_hellcannon_prologue_", "rare", 1},
    {"wh3_main_pro_kho_inf_chaos_furies_0_", "special", 1},
    {"wh3_main_pro_kho_inf_chaos_warhounds_0_", "special", 1},
    -- wh3_dlc20_group_chs_valkia
    {"1blood", "rare", 2},
    {"2blood", "rare", 3},
    {"wh3_main_kho_veh_skullcannon_0_", "rare", 2},
    {"wh3_main_pro_kho_inf_bloodletters_0_", "special", 2},
    {"wh3_main_pro_kho_inf_chaos_warriors_0_", "special", 1},
    {"wh3_main_pro_kho_inf_flesh_hounds_of_khorne_0_", "special", 2},
    -- wh3_dlc20_group_chs_vilitch
    {"2lord", "rare", 3},
    {"wh3_main_pro_tze_cav_chaos_knights_0_", "special", 2},
    {"wh3_main_pro_tze_inf_blue_horrors_0_", "special", 1},
    {"wh3_main_pro_tze_inf_pink_horrors_0_", "special", 2},
    {"wh3_main_pro_tze_mon_screamers_0_", "special", 1},
    -- wh3_main_cth
    {"1rocket", "special", 1},
    {"1rocket_", "special", 1},
    {"2lancers", "special", 1},
    {"3longma", "special", 2},
    {"5dragoncross", "special", 2},
    {"6jadewarr", "special", 1},
    {"7terra", "rare", 3},
    {"8skyjunk", "special", 3},
    {"9jadegun", "special", 2},
    -- wh3_main_dae
    {"3chariot", "rare", 3},
    -- wh3_main_ksl
    {"wh3_main_pro_ksl_cav_war_bear_riders_1_", "special", 3},
    {"wh3_main_pro_ksl_cav_winged_lancers_0_", "special", 1},
    {"wh3_main_pro_ksl_inf_armoured_kossars_0_", "special", 1},
    {"wh3_main_pro_ksl_inf_armoured_kossars_1_", "special", 1},
    {"wh3_main_pro_ksl_inf_kossars_0_", "special", 1},
    {"wh3_main_pro_ksl_inf_kossars_1_", "special", 1},
    {"wh3_main_pro_ksl_inf_streltsi_0_", "special", 1},
    {"wh3_main_pro_ksl_inf_tzar_guard_0_", "special", 2},
    {"wh3_main_pro_ksl_mon_elemental_bear_ror_0_", "rare", 3},
    {"wh3_main_pro_ksl_veh_little_grom_0_", "rare", 2},
    -- wh3_main_ogr
    {"grn_brutes1_gnoblars", "special", 1},
    {"grn_brutes2_ironguts", "special", 2},
    {"grn_brutes2_irongutss", "special", 2},
    {"grn_brutes3_maneaters", "special", 2},
    {"grn_brutes4_gorgers", "special", 1},
    {"grn_brutes5_ironblaster", "rare", 2},
    {"grn_brutes6_crushers", "rare", 2},
    {"grn_brutes7_giant", "rare", 3},
    {"grn_brutes8_leadbelchers", "rare", 1},
    {"grn_brutes9_maneaters", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
