-- Lost & Found Kislev: Hag Mothers (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_ksl
    {"laf_ksl_cav_great_stag_0", "special", 2},
    {"laf_ksl_inf_dryads_0", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
