-- Legendary Characters (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- dust_gutrot_military_group
    {"dust_gutrot_blight_kings", "special", 2},
    -- wh2_dlc12_grn_leaf_cutterz_tribe
    {"hunt_boyz_mob", "core"},
    {"hunt_goblin_mob", "core"},
    {"hunt_savage_mob", "special", 1},
    -- wh2_main_skv
    {"wh2_skv_mors_redguard_ror", "special", 2},
    -- wh3_main_kho
    {"kho_skullreaper_kys", "special", 2},
    {"kys_kho_wrathmonger", "special", 2},
    {"kys_kho_wrathmonger_ror", "rare", 2},
    -- wh_dlc05_group_wood_elves
    {"kou_bowmen_units", "special", 2},
    {"kou_elf_wolf_rider", "special", 2},
    {"kou_eonir_explorers", "special", 1},
    {"kou_laddrielle_wolves", "special", 1},
    {"kou_meadow_chariot_ror", "special", 2},
    {"kou_queen_ror_treekin", "special", 2},
    -- wh_main_group_dwarfs
    {"hunt_dwf_riggers_0", "special", 1},
    {"hunt_dwf_slayer_pirates_0", "special", 1},
    -- wh_main_group_empire
    {"str_chronos_knights", "special", 2},
    -- wh_main_group_kislev
    {"bear_dead_baron", "special", 2},
    {"werebear_werebearus", "special", 2},
    -- wh_main_group_vampire_counts
    {"camera_skelly_bones", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
