-- Agemouk's TOMB KINGS: Extended (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings
    {"ghs_tmb_landing_necrosphinx", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
