-- Dwarf Polearms (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_dwarfs
    {"wh_main_dwf_inf_dwarf_warrior_javelin_rider", "special", 2},
    {"wh_main_dwf_inf_dwarf_warrior_spear", "core"},
    {"wh_main_dwf_inf_dwarf_warrior_spear_javelin", "core"},
    {"wh_main_dwf_inf_dwarf_warrior_spear_rider", "special", 2},
    {"wh_main_dwf_inf_hammerer_rider", "special", 2},
    {"wh_main_dwf_inf_hammerers_polehammer", "special", 2},
    {"wh_main_dwf_inf_ironbreakers_poleaxe", "special", 2},
    {"wh_main_dwf_inf_ironbreakers_poleaxe_rider", "special", 2},
    {"wh_main_dwf_inf_ironbreakers_spear", "special", 2},
    {"wh_main_dwf_inf_ironbreakers_spear_rider", "special", 2},
    {"wh_main_dwf_inf_longbeards_bardiche", "core"},
    {"wh_main_dwf_inf_longbeards_spear", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
