-- Red Host of Tehenhauin (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_lzd
    {"roy_lzd_cav_skink_cold_one_riders", "rare", 1},
    {"roy_lzd_cav_skink_horned_one_riders", "special", 1},
    {"roy_lzd_cav_skink_horned_one_riders_nakai", "special", 1},
    {"roy_lzd_cav_terradons_wing_of_sotek", "rare", 1},
    {"roy_lzd_inf_saurus_of_sotek", "special", 1},
    {"roy_lzd_inf_saurus_of_sotek_nakai", "special", 1},
    {"roy_lzd_inf_skink_red_crests", "core"},
    {"roy_lzd_inf_skink_red_crests_braves_spears", "special", 1},
    {"roy_lzd_inf_skink_red_crests_braves_spears_nakai", "special", 1},
    {"roy_lzd_inf_skink_red_crests_cohort_javelins", "core"},
    {"roy_lzd_inf_skink_red_crests_elite", "core"},
    {"roy_lzd_inf_skink_red_crests_elite_blessed", "special", 1},
    {"roy_lzd_inf_skink_red_crests_elite_nakai", "core"},
    {"roy_lzd_inf_skink_red_crests_skirmishers", "core"},
    {"roy_lzd_inf_skink_red_crests_spears", "core"},
    {"roy_lzd_inf_skink_sotek_cultists", "special", 1},
    {"roy_lzd_inf_skink_sotek_cultists_nakai", "special", 1},
    {"roy_lzd_inf_skink_temple_guard_of_sotek", "special", 1},
    {"roy_lzd_inf_skink_temple_guard_of_sotek_nakai", "special", 1},
    {"roy_lzd_inf_skink_verminbane_cohort", "special", 1},
    {"roy_lzd_mon_kroxigors_mauls_of_sotek", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
