-- graetor's Empire Knightly Orders (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- borders
    {"wh_main_emp_cav_black_guard_0", "special", 2},
    {"wh_main_emp_inf_black_guard_0", "special", 1},
    -- wh3_dlc25_group_elspeth
    {"wh_main_emp_cav_black_bear_0", "special", 2},
    {"wh_main_emp_cav_everlasting_light_0", "special", 2},
    {"wh_main_emp_cav_fiery_heart_0", "special", 2},
    {"wh_main_emp_cav_gold_lion_0", "special", 2},
    {"wh_main_emp_cav_knights_bull_0", "special", 2},
    {"wh_main_emp_cav_knights_griffon_0", "special", 2},
    {"wh_main_emp_cav_knights_raven_0", "special", 2},
    {"wh_main_emp_cav_sacred_scythe_0", "special", 2},
    {"wh_main_emp_inf_knights_manann_0", "special", 1},
    {"wh_main_emp_inf_knights_raven_0", "special", 1},
    {"wh_main_emp_inf_reiksguard_0", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
