-- Dawi Additional GP Units (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_dwarfs
    {"derpy_dwf_hlandship_carrier", "rare", 3},
    {"derpy_dwf_keg_launchers", "special", 2},
    {"derpy_dwf_landship_05", "rare", 3},
    {"derpy_dwf_repeaters", "special", 2},
    {"derpy_dwf_sniper_repeaters", "special", 2},
    {"derpy_dwf_vault_sweepers", "special", 2},
    {"derpy_dwf_vault_sweepers_deploy", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
