-- Lost & Found Dwarfs: Complete Collection (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc23_rogue_karaz_a_karak_expedition
    {"laf_dwf_veh_gyrocopter_drakefire", "special", 2},
    -- wh_main_group_dwarfs
    {"laf_dwf_inf_crank_gunners", "rare", 2},
    {"laf_dwf_inf_ghost_longbeards", "core"},
    {"laf_dwf_inf_irondrakes_1", "rare", 2},
    {"laf_dwf_inf_miners_sappers", "core"},
    {"laf_dwf_inf_miners_steam_drills", "special", 1},
    {"laf_dwf_inf_unrads_excavators", "special", 2},
    {"laf_dwf_summon_ghost_dwarf_warriors", "core"},
    {"laf_dwf_summon_ghost_ironbreakers", "core"},
    {"laf_dwf_veh_earth_borer", "rare", 3},
    {"laf_dwf_veh_juggernaut_bolt_thrower", "special", 2},
    {"laf_dwf_veh_juggernaut_cannon", "special", 2},
    {"laf_dwf_veh_juggernaut_tonnisson", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
