-- OvN Lost Factions: Araby (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- ovn_araby
    {"ovn_arb_inf_arabyan_spearmen_summoned_0", "core"},
    {"ovn_arb_inf_arabyan_spearmen_summoned_1", "core"},
    {"ovn_arb_mon_desert_spirit_summoned", "rare", 3},
    {"ovn_arb_mon_enchanted_rope_summoned", "special", 2},
    {"ovn_arb_mon_fire_efreet_summoned", "rare", 3},
    {"ovn_arb_mon_genie_summoned", "special", 3},
    {"ovn_arb_mon_sea_nymph_summoned", "rare", 3},
    {"ovn_arb_mon_tempest_djinn_summoned", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
