-- Lily's Bretonnia Mod Compilation: All-in-one (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_bretonnia
    {"brt_art_field_trebuchet_carc", "rare", 1},
    {"brt_art_field_trebuchet_flame", "rare", 1},
    {"zayli_brt_men_at_arms_pike", "core"},
    {"zayli_brt_polearm_shield", "core"},
    {"zayli_foot_knight", "special", 1},
    {"zayli_grail_companion", "special", 1},
    {"zayli_knights_of_the_realm_swords", "special", 1},
    {"zayli_men_at_arms_axemen", "core"},
    {"zayli_men_at_arms_longbow_1", "core"},
    {"zayli_men_at_arms_longbow_2", "core"},
    {"zayli_men_at_arms_ror_1", "special", 1},
    {"zayli_men_at_arms_ror_10", "special", 1},
    {"zayli_men_at_arms_ror_11", "special", 1},
    {"zayli_men_at_arms_ror_12", "special", 1},
    {"zayli_men_at_arms_ror_13", "special", 1},
    {"zayli_men_at_arms_ror_2", "special", 1},
    {"zayli_men_at_arms_ror_3", "special", 1},
    {"zayli_men_at_arms_ror_4", "special", 1},
    {"zayli_men_at_arms_ror_5", "special", 1},
    {"zayli_men_at_arms_ror_6", "special", 1},
    {"zayli_men_at_arms_ror_7", "special", 1},
    {"zayli_men_at_arms_ror_8", "special", 1},
    {"zayli_men_at_arms_ror_9", "special", 1},
    {"zayli_mounted_squires", "special", 1},
    {"zayli_paladins", "special", 2},
    {"zayli_paladins_great_weapons", "special", 2},
    {"zayli_peasant_bowmen_armoured", "core"},
    {"zayli_peasant_mob_maces", "core"},
    {"zayli_royal_crossbow", "special", 1},
    {"zayli_royal_longbow", "special", 1},
    {"zayli_royal_men_at_arms_skirmishers", "core"},
    {"zayli_royal_men_at_arms_skirmishers_core", "core"},
    {"zayli_royal_polearm_men_at_arms", "core"},
    {"zayli_royal_poleaxe_men_at_arms", "core"},
    {"zayli_royal_spear_men_at_arms", "core"},
    {"zayli_royal_swords_men_at_arms", "core"},
    {"zayli_royal_yeomen", "special", 1},
    {"zayli_royal_yeomen_archers", "core"},
    {"zayli_trebuchet_ror_1", "rare", 2},
    {"zayli_wh_dlc07_brt_foot_squires", "special", 1},
    {"zayli_yeomen_ror_1", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
