-- Roar of the Jade Sea : Yin-Yin, the Sea Dragon (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_lzd
    {"lzd_pachy_0", "special", 1},
    {"lzd_raptor_0", "core"},
    {"lzd_styracosaur", "rare", 2},
    -- wh3_main_cth
    {"cth_golden_heron", "rare", 3},
    {"cth_golden_heron_upgraded", "rare", 3},
    {"cth_golden_heron_zhuque", "rare", 3},
    {"cth_marines", "special", 1},
    {"cth_marines_ror", "special", 1},
    {"cth_ronin", "special", 1},
    {"cth_sam", "special", 1},
    {"cth_whalers", "rare", 1},
    {"cth_wokou", "core"},
    {"cth_wokou_cannon", "rare", 1},
    {"cth_wokou_ds", "core"},
    {"cth_wokou_guns", "core"},
    {"cth_wokou_spears", "core"},
    {"cth_yicha_fghter", "special", 1},
    {"npn_ansatsu", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
