-- Guns of the Empire (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_rogue_college_of_pyrotechnics
    {"snek_emp_gote_art_clockwork_missile", "rare", 2},
    {"snek_emp_gote_art_grand_cannon", "special", 2},
    {"snek_emp_gote_art_hellhammer", "rare", 2},
    {"snek_emp_gote_art_incendiary_guns", "rare", 2},
    {"snek_emp_gote_art_steamcopter", "special", 2},
    {"snek_emp_gote_art_swivel_guns", "special", 2},
    {"snek_emp_gote_cav_thricepistols", "core"},
    {"snek_emp_gote_inf_dwarf_crank_gunners", "rare", 2},
    {"snek_emp_gote_inf_eisenbombers", "special", 1},
    {"snek_emp_gote_inf_ersatzsolder", "core"},
    {"snek_emp_gote_inf_field_engineers", "special", 1},
    {"snek_emp_gote_inf_hakbutschutzen", "core"},
    {"snek_emp_gote_inf_ironsides", "special", 1},
    {"snek_emp_gote_inf_jaegerkorps", "core"},
    {"snek_emp_gote_inf_leadbelchers", "special", 2},
    {"snek_emp_gote_inf_longrifles", "special", 1},
    {"snek_emp_gote_veh_hellblaster_wagon", "rare", 2},
    {"snek_emp_gote_veh_munitions_wagon", "rare", 2},
    -- wh3_dlc25_group_elspeth
    {"snek_emp_gote_art_war_baloon", "rare", 3},
    {"snek_emp_gote_inf_bergjaeger", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
