-- Dead's Jade Army Expansion (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_cth
    {"jade_archers", "core"},
    {"jade_cataphract", "special", 2},
    {"jade_chariot", "special", 2},
    {"jade_repeaters", "core"},
    {"jade_warriors_glaive", "core"},
    {"jade_warriors_spear", "core"},
    {"jade_warriors_spear_shield", "core"},
    {"jade_zhanmadao", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
