-- Asrai Unit Pack (Wood Elves) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc16_group_drycha
    {"c_glade_rangers", "core"},
    {"c_oak_guardians", "special", 2},
    -- wh_dlc05_group_wood_elves
    {"c_asrai_blademasters", "special", 2},
    {"c_asrai_shieldmaidens", "special", 2},
    {"c_asrai_sunderers", "special", 2},
    {"c_maidens_of_kurnous", "rare", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
