-- Inquisitor's More Ogres! (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_ogr
    {"blood_vultures", "core"},
    {"ogr_feral_mammoth", "rare", 2},
    {"ogr_stonehorn_cannon", "rare", 2},
    {"ogre_bomber", "core"},
    {"ogre_gatebusters", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
