-- Mono God Aspiring Champions (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc20_group_chs_azazel
    {"slaanesh_champions", "special", 2},
    -- wh3_dlc20_group_chs_festus
    {"nurgle_champions", "rare", 2},
    -- wh3_dlc20_group_chs_valkia
    {"khorne_berzerker_champions", "special", 2},
    -- wh3_dlc20_group_chs_vilitch
    {"tzeentch_champions", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
