-- Bertrand the Brigand, Thieves' Honor (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_bretonnia
    {"brt_aspirant_hoods", "special", 2},
    {"brt_brigand_crossbows", "core", 1},
    {"brt_brigand_cutthroats", "special", 1},
    {"brt_brigand_raiders", "core"},
    {"brt_brigand_waylayers", "special", 1},
    {"brt_brigands", "core"},
    {"brt_brigands_axes", "core"},
    {"brt_chasseurs", "special", 1},
    {"brt_herrimaults", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
