-- The Jade-Blooded Vampires: Curse of Nongchang (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_jade_vampires_IotM_group
    {"cth_jiangshi_summoned", "special", 2},
    {"jbv_faithfuls_ancient_summoned", "core"},
    {"jbv_gateguardian_summoned", "rare", 2},
    {"jbv_ghost_host_summoned", "core"},
    {"jbv_ghost_host_summoned_2", "core"},
    {"jbv_mogwai", "special", 2},
    {"jbv_newbloods_summoned", "special", 2},
    {"jbv_warriors_1", "special", 2},
    {"jbv_xiang_men_summoned", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
