-- Mutants and Cults (STS) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc20_group_chs_valkia
    {"stg_chos_unq_mutants_ror_kho", "special", 1},
    -- wh3_main_group_belakor
    {"stg_ch_cult_kho_blacksmiths_of_blood_belakor", "special", 2},
    {"stg_ch_cult_kho_corrupted_belakor", "core", 1},
    {"stg_ch_cult_kho_monnik_pit_fighter_belakor", "core", 1},
    {"stg_ch_cult_nur_carnival_belakor", "special", 1},
    {"stg_ch_cult_nur_children_doom_belakor", "core", 1},
    {"stg_ch_cult_nur_maggot_king_chosen_belakor", "rare", 1},
    {"stg_ch_cult_sla_bleak_society_belakor", "special", 1},
    {"stg_ch_cult_sla_jade_spectre_belakor", "core", 1},
    {"stg_ch_cult_sla_main_sybarites_belakor", "special", 1},
    {"stg_ch_cult_tze_broken_wheel_belakor", "special", 2},
    {"stg_ch_cult_tze_fthaktoi_bkah_belakor", "special", 1},
    {"stg_ch_cult_tze_purple_hand_belakor", "core", 1},
    {"stg_chos_unq_mutants_belakor", "core", 1},
    -- wh_main_group_chaos
    {"stg_ch_cult_kho_blacksmiths_of_blood_kholek", "special", 2},
    {"stg_ch_cult_kho_corrupted_kholek", "core", 1},
    {"stg_ch_cult_kho_monnik_pit_fighter_kholek", "core", 1},
    {"stg_ch_cult_nur_carnival_kholek", "special", 1},
    {"stg_ch_cult_nur_children_doom_kholek", "core", 1},
    {"stg_ch_cult_nur_maggot_king_chosen_kholek", "rare", 1},
    {"stg_ch_cult_sla_bleak_society_kholek", "special", 1},
    {"stg_ch_cult_sla_bleak_society_sigvald", "special", 1},
    {"stg_ch_cult_sla_jade_spectre_kholek", "core", 1},
    {"stg_ch_cult_sla_jade_spectre_sigvald", "core", 1},
    {"stg_ch_cult_sla_main_sybarites_kholek", "special", 1},
    {"stg_ch_cult_sla_main_sybarites_sigvald", "special", 1},
    {"stg_ch_cult_tze_broken_wheel_kholek", "special", 2},
    {"stg_ch_cult_tze_fthaktoi_bkah_kholek", "special", 1},
    {"stg_ch_cult_tze_purple_hand_kholek", "core", 1},
    {"stg_chos_unq_mutants_kholek", "core", 1},
    {"stg_chos_unq_mutants_sigvald", "core", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
