-- Landmarks of Eternity (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc16_group_drycha
    {"Chasslo_Drachenhole_dragon", "rare", 3},
    -- wh2_main_lzd
    {"CLE_lzd_vultures", "special", 1},
    -- wh3_main_cth
    {"Chasslo_Goldtooth_guard", "special", 2},
    -- wh_dlc03_group_beastmen
    {"Chasslo_Blood_seekers", "special", 2},
    -- wh_main_group_chaos
    {"Chasslo_Pale_Maidens", "rare", 1},
    {"Chasslo_dancing_beauties", "special", 2},
    -- wh_main_group_empire
    {"Chasslo_Fireloques_Ferlangen", "special", 1},
    -- wh_main_group_greenskins
    {"Chasslo_Soqotra_Pirates", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
