-- Ruo's Bodyguards & Mounts All-In-One (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc25_group_elspeth
    {"emp_captain_retinue_1", "core"},
    {"emp_captain_retinue_2", "core"},
    {"emp_captain_retinue_3", "special", 1},
    {"emp_captain_retinue_4", "special", 1},
    {"emp_captain_retinue_5", "special", 2},
    {"emp_captain_retinue_6", "special", 2},
    {"emp_captain_retinue_7", "special", 2},
    {"emp_captain_retinue_8", "special", 2},
    {"emp_captain_retinue_9", "special", 2},
    {"emp_engineer_retinue_1", "special", 2},
    {"emp_engineer_retinue_2", "special", 2},
    {"emp_engineer_retinue_3", "special", 2},
    {"emp_engineer_retinue_4", "special", 2},
    {"emp_general_retinue_1", "special", 1},
    {"emp_general_retinue_2", "special", 2},
    {"emp_general_retinue_3", "special", 2},
    {"emp_warrior_priest_retinue_1", "special", 2},
    {"emp_warrior_priest_retinue_2", "special", 1},
    {"emp_warrior_priest_retinue_3", "special", 2},
    {"emp_warrior_priest_retinue_4", "special", 2},
    {"emp_witch_hunter_retinue_1", "special", 2},
    {"emp_witch_hunter_retinue_2", "special", 1},
    {"emp_witch_hunter_retinue_3", "special", 1},
    {"emp_witch_hunter_retinue_4", "special", 2},
    {"emp_witch_hunter_retinue_5", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
