-- vampire coasttt ships (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc11_group_vampire_coast
    {"cst_boarding", "special", 1},
    {"cst_spectral", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
