-- OvN Lost Factions: Fimir (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- ovn_fimir
    {"fim_cav_marsh_hornets_ror", "special", 2},
    {"fim_cav_marsh_reavers", "special", 2},
    {"fim_cav_nuckelavee", "special", 1},
    {"fim_inf_boglar", "core", 1},
    {"fim_inf_death_quest", "special", 1},
    {"fim_inf_fimm_flaithmor", "core"},
    {"fim_inf_fimm_warriors", "core"},
    {"fim_inf_fimm_warriors_axe_throwers_ror", "special", 1},
    {"fim_inf_fimm_warriors_great_weapons", "core"},
    {"fim_inf_killing_eye_ror", "special", 1},
    {"fim_inf_moor_hounds", "core"},
    {"fim_inf_moor_hounds_ror", "special", 1},
    {"fim_inf_shearl", "core"},
    {"fim_inf_shearl_javelineer", "core"},
    {"fim_inf_shearl_spearmen", "core", 1},
    {"fim_inf_swamp_daemons", "core", 1},
    {"fim_inf_swamp_daemons_summon", "core", 1},
    {"fim_mon_balefiend_apprentices", "special", 2},
    {"fim_mon_daemonomaniac", "rare", 3},
    {"fim_mon_daemonomaniac_ror", "rare", 3},
    {"fim_mon_fenbeast", "special", 2},
    {"fim_mon_fianna_fimm", "rare", 1},
    {"fim_mon_fianna_fimm_great_weapons", "rare", 1},
    {"fim_mon_fianna_fimm_shields", "special", 2},
    {"fim_mon_gharnus_daemon_ror", "special", 2},
    {"fim_mon_jabberslythe", "rare", 3},
    {"fim_veh_eye_oculus", "rare", 3},
    {"ovn_fim_mon_bog_octopus_0", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
