-- Dwarf Fortress (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_dwarfs
    {"awp_dwf_land_ship", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
