-- 【Deer24帝国单位包】帝国传奇 ( Units patch：Empire Romance) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc25_group_elspeth
    {"agesiqishi", "rare", 1},
    {"bailang", "rare", 3},
    {"buxingqishi", "special", 1},
    {"buxingqishi1", "special", 1},
    {"diguohuoqiangshou", "special", 1},
    {"diguolong", "rare", 3},
    {"dihuangqishi", "special", 2},
    {"gaositianshi", "special", 2},
    {"huangjinzituan", "special", 2},
    {"jiaozongqishi", "special", 2},
    {"judunnubing", "special", 1},
    {"liebing", "special", 1},
    {"mishenheiwei", "special", 2},
    {"neihuanqishi", "special", 3},
    {"rongyaoqishi", "special", 3},
    {"ruikeqishi", "special", 1},
    {"shenxue", "special", 2},
    {"sheshou", "special", 2},
    {"syr", "special", 2},
    {"xigemachui", "special", 2},
    {"youlikezhanshi", "special", 2},
    {"yulintiewei", "rare", 2},
    {"zhandouxiunv", "rare", 1},
    {"zhenqiqishi", "rare", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
