-- Lost Calm: Jurassic Normal (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_lzd
    {"calm_allosaur", "special", 2},
    {"calm_allosaur_riders", "special", 2},
    {"calm_ankylosaur", "rare", 2},
    {"calm_ankylosaur_artillery", "rare", 2},
    {"calm_arceopteryx", "special", 1},
    {"calm_armoured_proto", "special", 2},
    {"calm_cerapod", "special", 1},
    {"calm_cerapod_riders", "special", 2},
    {"calm_cherupins", "special", 2},
    {"calm_colossodon", "rare", 2},
    {"calm_croc", "special", 2},
    {"calm_croc_cav", "special", 2},
    {"calm_culchan", "core", 1},
    {"calm_culchan_cav", "special", 1},
    {"calm_custodian", "rare", 2},
    {"calm_dilophiraptor", "special", 1},
    {"calm_elite_terradon", "special", 1},
    {"calm_feral_cherupins", "special", 1},
    {"calm_feral_proto", "special", 2},
    {"calm_ictlamimus", "rare", 2},
    {"calm_nuatl", "special", 2},
    {"calm_ornisornis", "special", 2},
    {"calm_pachy", "special", 1},
    {"calm_parasaur", "special", 2},
    {"calm_parasaur_feral", "special", 2},
    {"calm_pirhajara", "core"},
    {"calm_pleuridon", "rare", 2},
    {"calm_quatzelotus", "rare", 3},
    {"calm_rex", "rare", 3},
    {"calm_rodan", "rare", 2},
    {"calm_shield_proto", "special", 2},
    {"calm_spitter_proto", "special", 2},
    {"calm_stegasaur", "rare", 2},
    {"calm_stegasaur_artillery", "rare", 2},
    {"calm_terror_bird", "rare", 2},
    {"calm_thunder_lizard", "rare", 3},
    {"calm_vulture", "special", 2},
    {"calm_xholadocus", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
