-- Regiments of Renown Compilation (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- ovn_dread_king
    {"deco_bhagar", "rare", 3},
    {"deco_emerald", "special", 2},
    {"deco_royal_chariot", "special", 2},
    {"deco_underworld", "special", 1},
    {"deco_wight", "special", 1},
    {"deco_zandri", "special", 1},
    -- wh2_dlc12_grn_leaf_cutterz_tribe
    {"deco_bonebreakers", "special", 2},
    {"deco_bouncers", "special", 2},
    {"deco_drillaz", "special", 2},
    {"deco_frik", "core"},
    {"deco_grokkamobs", "special", 2},
    {"deco_harboth", "core"},
    -- wh2_main_def
    {"deco_burning_dark", "special", 1},
    {"deco_ravenspears", "core"},
    {"deco_rimeshards", "core"},
    {"deco_soulskulls", "core"},
    {"deco_voiceless", "core"},
    {"deco_witchguard", "special", 2},
    -- wh2_main_lzd
    {"roy_lzd_cav_the_wind_that_hungers", "special", 2},
    {"roy_lzd_cav_tichi_huichis_raiders", "special", 1},
    {"roy_lzd_inf_saurus_cohort_of_the_copper_sun", "special", 1},
    {"roy_lzd_inf_skink_eye_of_the_canopy", "core"},
    {"roy_lzd_inf_skink_mist_runners", "core"},
    {"roy_lzd_inf_skink_red_shields", "core"},
    {"roy_lzd_inf_skink_shrouded_cohort", "core"},
    {"roy_lzd_inf_skink_yellow_crested_cohort", "core"},
    {"roy_lzd_inf_temple_guards_of_xlanhuapec", "special", 2},
    {"roy_lzd_mon_kroxigor_shrouded_cohort", "special", 2},
    {"roy_lzd_mon_kroxigor_yellow_crested", "special", 2},
    -- wh3_dlc23_group_chaos_dwarfs
    {"deco_backstabbers", "special", 1},
    {"deco_bahal_guardians", "special", 2},
    {"deco_doombringer", "rare", 3},
    {"deco_kinslayers", "special", 2},
    {"deco_magma_beasts", "special", 2},
    {"deco_warriors_horde", "core"},
    -- wh3_dlc25_group_elspeth
    {"deco_crimson_defiants", "core"},
    {"deco_forest_patrol", "core"},
    {"deco_grof_riders", "special", 2},
    {"deco_von_kragsburg", "core"},
    {"deco_white_reavers", "core"},
    -- wh3_main_ksl
    {"wh3_main_ksl_cav_bolgasgrad_ror", "special", 2},
    {"wh3_main_ksl_cav_dawn_ror", "special", 2},
    {"wh3_main_ksl_inf_alexandronov_ror", "special", 2},
    {"wh3_main_ksl_inf_stalgrad_ror", "core"},
    -- wh_dlc03_group_beastmen
    {"ror_beast_gibberkin", "rare", 1},
    {"ror_beast_gulmoth", "special", 2},
    {"ror_beast_inmates", "core"},
    {"ror_beast_nashara", "special", 1},
    {"ror_beast_redmaw", "special", 1},
    {"ror_beast_shadowg", "special", 1},
    {"ror_beast_toxote", "special", 1},
    {"ror_beast_ungrol", "core"},
    {"ror_beast_ymgir", "special", 2},
    -- wh_main_group_bretonnia
    {"ror_bret_dason", "rare", 1},
    {"ror_bret_elcyd", "special", 2},
    {"ror_bret_ennar", "special", 1},
    {"ror_bret_fastric", "rare", 2},
    {"ror_bret_flame", "special", 1},
    {"ror_bret_fracasse", "special", 2},
    {"ror_bret_mayonne", "core"},
    {"ror_bret_mob", "core"},
    {"ror_bret_rapscallards", "core"},
    {"ror_bret_salles", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
