-- Expanded Roster Compilation (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc11_cst_rogue_boyz_of_the_forbidden_coast
    {"deco_big_uns_shields", "core"},
    {"deco_black_orc_dual", "special", 2},
    -- wh2_dlc12_grn_leaf_cutterz_tribe
    {"deco_armored_colossal_squig", "rare", 2},
    {"deco_forest_goblin_archers", "core"},
    {"deco_forest_goblin_spears", "core"},
    {"deco_forest_goblin_swords", "core"},
    {"deco_hill_goblins", "core"},
    {"deco_night_goblin_spears", "core"},
    {"deco_savage_big_uns_gw", "core"},
    {"deco_savage_orc_spears", "core"},
    {"deco_snotlings", "core"},
    {"str_urgat_wolf_chariot", "special", 2},
    -- wh2_dlc16_group_drycha
    {"deco_dryads_willow_malicious", "core"},
    {"deco_glade_knights", "special", 2},
    {"deco_handmaidens_torothal", "core"},
    {"deco_meadow_chariots", "special", 1},
    {"deco_wildwood_wardens", "special", 2},
    {"deco_wind_riders", "special", 1},
    -- wh2_main_def
    {"dec_hunters_anath_raema", "special", 1},
    {"dec_lords_oblivion", "rare", 2},
    {"dec_magma_dragon", "rare", 3},
    {"dec_tower_masters", "special", 2},
    -- wh2_main_hef
    {"deco_avelorn_maidens", "core"},
    {"deco_bladelords", "special", 2},
    {"deco_griffon_knights", "rare", 2},
    {"deco_high_helms", "special", 2},
    {"deco_skywardens", "core"},
    -- wh2_main_rogue_gerhardts_mercenaries
    {"deco_savage_giant", "rare", 3},
    -- wh3_dlc23_group_chaos_dwarfs
    {"deco_chd_acolytes", "special", 1},
    {"deco_chd_annihilators", "special", 2},
    {"deco_chd_lava_trolls", "special", 2},
    {"deco_chd_naphtha", "special", 1},
    {"deco_chd_ogre_slaves", "special", 1},
    {"deco_chd_quarrellers", "core"},
    {"deco_chd_ravagers", "rare", 1},
    {"deco_chd_siege_giant", "rare", 2},
    {"deco_chd_zealots", "special", 1},
    -- wh3_dlc25_group_elspeth
    {"deco_doom_prophets", "special", 1},
    {"deco_ironsides", "special", 1},
    {"deco_knights_lynx", "special", 1},
    {"deco_roadwardens", "core"},
    {"deco_shielded_halberdiers", "core"},
    -- wh3_main_ogr
    {"dec_ember_drake", "rare", 2},
    {"dec_giantbreakers", "special", 2},
    {"dec_ice_mammoth", "rare", 2},
    {"dec_ogre_bulls_gw", "special", 1},
    {"dec_rhinox_bull", "rare", 2},
    -- wh_dlc03_group_beastmen
    {"dec_bestigor_dual_axe", "special", 1},
    {"dec_gor_great_axe", "core"},
    {"dec_gouge_horns", "special", 2},
    -- wh_dlc05_group_wood_elves
    {"deco_dryads_willow", "core"},
    -- wh_main_group_dwarfs
    {"deco_bugman_thrower", "rare", 2},
    {"deco_hammerers_dual", "special", 2},
    {"deco_irondrakes_drakefire", "special", 2},
    {"deco_old_guard", "special", 2},
    {"deco_prospectors", "special", 1},
    {"dwf_kou_dreadnaught", "rare", 3},
    -- wh_main_group_greenskins
    {"grn_poop", "core"},
    -- wh_main_group_norsca
    {"deco_nor_bondsmen", "core"},
    {"deco_nor_hydra", "rare", 2},
    {"deco_nor_pit", "special", 1},
    {"deco_nor_reavers", "special", 1},
    {"deco_nor_valkyrie", "special", 2},
    {"deco_nor_wolf", "special", 2},
    -- wh_main_group_vampire_counts
    {"dec_hell_knights", "special", 2},
    {"dec_kastellans", "rare", 2},
    {"dec_lahmian", "special", 1},
    {"dec_reapers", "core"},
    {"dec_spirit_host", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
