-- Skaven Esoterica (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_skv
    {"krakback_kill_squad", "special", 2},
    {"krakback_kill_squad_spears", "special", 2},
    {"poxigors", "special", 2},
    {"skaven_cav", "special", 1},
    {"skaven_mech", "rare", 2},
    {"skaven_mech_at", "rare", 2},
    {"skaven_mech_gat", "rare", 2},
    {"warp_bombard", "rare", 3},
    {"warp_bomber", "special", 2},
    {"warp_forged", "special", 1},
    {"warp_gunship", "special", 2},
    {"warp_runners", "special", 1},
    {"warp_tank", "rare", 3},
    {"warp_zeppelin", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
