-- Go Squig or Go Home! (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_greenskins
    {"als_squig_bitey", "core"},
    {"als_squig_flappy", "special", 1},
    {"als_squig_flappy_big", "special", 1},
    {"als_squig_great_cave", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
