-- Cataph's Kraka Drak: the Norse Dwarfs (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- AK_kraka
    {"kraka_braves", "core"},
    {"kraka_drakken", "rare", 2},
    {"kraka_frostgun", "special", 1},
    {"kraka_huskarls", "special", 2},
    {"kraka_marauder_horsemen", "core", 1},
    {"kraka_nor_marauders", "core", 1},
    {"kraka_nor_marauders_spears", "core"},
    {"kraka_pathgrinders", "special", 1},
    {"kraka_rust", "special", 1},
    {"kraka_spikegunners", "core"},
    {"kraka_stormbeards", "core"},
    {"kraka_trollsearers", "special", 1},
    {"kraka_wardbearers", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
