-- Gnoblar Hordes - The Unwashed Masses (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- gnob_gnoblar_hordes
    {"gnob_cav_pigback_riders_javelin", "core"},
    {"gnob_inf_fighters", "core"},
    {"gnob_inf_flingers", "core", 1},
    {"gnob_inf_lucky_gits", "special", 1},
    {"gnob_inf_manbiters", "special", 1},
    {"gnob_inf_ogrebiters", "special", 1},
    {"gnob_mon_rhinox_riders", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
