-- LoW - Dragon Legion (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_hef
    {"low_hef_art_dragon_legion_bolt_thrower", "rare", 1},
    {"low_hef_cav_dragon_legion_caledorian_chariot_0", "special", 2},
    {"low_hef_cav_dragon_legion_corsair_knight_lancer_01", "special", 2},
    {"low_hef_cav_dragon_legion_corsair_knight_swordsman_01", "special", 2},
    {"low_hef_cav_dragon_legion_knights_0", "special", 2},
    {"low_hef_cav_dragon_legion_knights_1", "special", 2},
    {"low_hef_inf_dragon_legion_archers_0", "special", 1},
    {"low_hef_inf_dragon_legion_archers_shielded_0", "special", 1},
    {"low_hef_inf_dragon_legion_corsairs_arbalests_01", "special", 1},
    {"low_hef_inf_dragon_legion_corsairs_crossbow_shield_01", "special", 2},
    {"low_hef_inf_dragon_legion_corsairs_dual_swords_01", "special", 1},
    {"low_hef_inf_dragon_legion_corsairs_handbows_01", "special", 1},
    {"low_hef_inf_dragon_legion_dragon_guard_0", "special", 2},
    {"low_hef_inf_dragon_legion_dragon_guard_archers_0", "special", 2},
    {"low_hef_inf_dragon_legion_spearmen_0", "special", 1},
    {"low_hef_inf_dragon_legion_swordmasters_0", "special", 2},
    {"low_hef_inf_dragon_legion_swordsmen_0", "special", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
