-- 【Deer24 基斯里夫兵种包】厄孙之牙 (Deer24 Kislve Units Patc Ursuns Tooth) (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_ksl
    {"bohaguanjun", "special", 2},
    {"bohajinjun", "special", 2},
    {"fuzuijuntuan", "rare", 1},
    {"jinweijun", "rare", 1},
    {"kaqiusha", "rare", 2},
    {"xianbin", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
