-- [DEER24/巴托尼亚]骑士王国（ BRETONNIA UNITS PATCH Knight Kingdom） (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_bretonnia
    {"BJQS", "special", 2},
    {"BJQS_RIDER", "special", 2},
    {"BT", "special", 1},
    {"BT1", "special", 1},
    {"BTCGS", "special", 1},
    {"CBWD", "special", 1},
    {"CBWD1", "special", 2},
    {"CGS", "core"},
    {"FMQS", "special", 2},
    {"FMQS_RIDER", "special", 2},
    {"QJ1", "special", 1},
    {"QJ2", "special", 1},
    {"SMSW", "special", 2},
    {"SZQS", "special", 2},
    {"SZQS_RIDER", "special", 2},
    {"YEZHUQS", "special", 2},
    {"YEZHUQS_RIDER", "special", 2},
    {"YZQS", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
