-- Dawi Gunpowder Units (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_dwarfs
    {"derpy_dwf_eng_tank", "rare", 2},
    {"derpy_dwf_eng_tankette", "special", 2},
    {"derpy_dwf_ironhog_repeaters_malakai", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
