-- OvN Lost Factions: Albion (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- ovn_albion
    {"alb_cav_noble", "special", 1},
    {"alb_cav_noble_first_ror", "special", 1},
    {"alb_cav_noble_spear", "special", 2},
    {"alb_viridian_champ", "special", 2},
    {"albion_bologs_giant_ror", "rare", 3},
    {"albion_cachtorr_stonethrower", "rare", 2},
    {"albion_centaur_hunter_ror", "special", 2},
    {"albion_centaurs", "special", 1},
    {"albion_centaurs_bows", "special", 2},
    {"albion_chariot", "core", 1},
    {"albion_fenhulk", "rare", 3},
    {"albion_feral_gryphon_summon", "special", 2},
    {"albion_giant", "rare", 3},
    {"albion_half_giants", "special", 1},
    {"albion_hearthguard", "core"},
    {"albion_hearthguard_2h", "special", 1},
    {"albion_hearthguard_halberd", "special", 1},
    {"albion_highlander_ror", "special", 2},
    {"albion_huntresses", "core"},
    {"albion_huntresses_warden_ror", "special", 2},
    {"albion_riders", "core", 1},
    {"albion_riders_javelins", "core", 1},
    {"albion_riders_spear", "core"},
    {"albion_shieldmaiden_ror", "special", 1},
    {"albion_stonethrower", "rare", 1},
    {"albion_swordmaiden", "special", 1},
    {"albion_warriors_lugh", "core"},
    {"albion_woadraider_sworn_ror", "special", 1},
    {"druid_neophytes", "special", 1},
    {"elo_albion_gryphon", "special", 2},
    {"elo_albion_warriors", "core"},
    {"elo_albion_warriors_2h", "core"},
    {"elo_albion_warriors_spears", "core"},
    {"elo_bloodhounds", "core"},
    {"elo_fenbeast", "special", 2},
    {"elo_fly_infested_rotwood", "rare", 3},
    {"elo_woadraider", "special", 1},
    {"elo_youngbloods", "core"},
    {"ovn_alb_inf_stone_throw_giant", "rare", 3},
    {"ovn_barrow_wight", "core", 1},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
