-- Dark Land Orcs (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_greenskins
    {"frb_dark_land_bulwarks", "special", 2},
    {"frb_dark_land_bulwarks_ror", "rare", 2},
    {"frb_dark_land_drake", "rare", 2},
    {"frb_dark_land_drake_ror", "rare", 3},
    {"frb_dark_land_orc_boyz", "core"},
    {"frb_dark_land_orc_boyz_big_uns", "special", 1},
    {"frb_scrap_shooters", "special", 2},
    {"frb_scrap_shooters_ror", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
