-- Patron Gods (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc20_group_chs_azazel
    {"chaos_chosen_of_slaanesh_1", "special", 2},
    {"chaos_warriors_of_slaanesh_1", "core", 1},
    {"slaanesh_marauder_hunters_jav", "core", 1},
    -- wh3_dlc20_group_chs_festus_glottkin
    {"theak_chaos_warriors_nurgle_scythe", "special", 1},
    {"theak_chosen_nurgle_scythe", "special", 2},
    {"theak_marauders_nurgle_throw_axes", "core", 1},
    -- wh3_dlc20_group_chs_valkia
    {"chosen_khorne_hell_halberd", "special", 2},
    {"marauders_khorne_fire_axes", "core", 1},
    -- wh3_dlc20_group_chs_vilitch
    {"chosen_glaives_blaze", "special", 2},
    {"chosen_of_tzeentch_2", "core"},
    {"marauder_hunters_tze", "core", 1},
    -- wh3_main_dae
    {"slaanesh_devoted_marauder_hunters_javs", "core"},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
