-- Eustace's Cathay Artillery Pack (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_cth
    {"bastion_cannon", "rare", 2},
    {"cathay_bolt_thrower", "special", 2},
    {"cathay_mortar", "special", 2},
    {"cathay_mortar_alchemy", "special", 2},
    {"three_dragons", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
