-- Guns of Bretonnia 3 (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh_main_group_bretonnia
    {"bret_art_grand_battery", "rare", 2},
    {"bret_hellwagon", "rare", 2},
    {"bret_musketeers_special", "special", 2},
    {"bret_templars", "special", 2},
    {"bret_templars_crimson", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
