-- Unique Steam Tanks (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_main_skv
    {"zfcr_skv_veh_steam_tank_rat_tank", "rare", 3},
    -- wh3_main_ksl
    {"dead_ksl_steamtank", "rare", 3},
    -- wh_main_group_empire
    {"zfcr_emp_veh_steam_tank_alter_kamerad", "rare", 3},
    {"zfcr_emp_veh_steam_tank_deliverance", "rare", 3},
    {"zfcr_emp_veh_steam_tank_emperors_wrath", "rare", 3},
    {"zfcr_emp_veh_steam_tank_implacable", "rare", 3},
    {"zfcr_emp_veh_steam_tank_invincible", "rare", 3},
    {"zfcr_emp_veh_steam_tank_kathleen", "rare", 3},
    {"zfcr_emp_veh_steam_tank_patriarchs_storm", "rare", 3},
    {"zfcr_emp_veh_steam_tank_sigmars_hammer", "rare", 3},
    {"zfcr_emp_veh_steam_tank_von_zeppels", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
