-- Nurgle Rotting Chargers (and Walkers) - New units for Nurgle and for Beastmen (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc20_group_chs_festus
    {"mutated_beasts", "special", 1},
    {"plague_crusher", "rare", 2},
    {"twisted_behemoth", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
