-- Hashut's Polearms (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_dlc23_group_chaos_dwarfs
    {"chd_inf_chaos_dwarf_warriors_halberd", "core"},
    {"chd_inf_chaos_dwarf_warriors_spears", "core"},
    {"chd_inf_golden_legion_halberd", "special", 2},
    {"chd_inf_golden_legion_spears", "special", 2},
    {"chd_inf_infernal_guard_bardiche", "special", 1},
    {"chd_inf_infernal_guard_spears", "special", 1},
    {"chd_mon_auroch_riders", "special", 2},
    {"chd_mon_bale_auroch_riders", "rare", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
