-- Immortal Landmarks (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh2_dlc09_tomb_kings
    {"tmb_scorpion_summon", "rare", 1},
    -- wh3_main_dae
    {"norscan_bondsmen", "special", 2},
    -- wh3_main_kho
    {"khorne_simaergul", "special", 2},
    -- wh3_main_sla
    {"shadow_guard", "special", 1},
    -- wh3_main_tze
    {"corrupted_sentinel", "rare", 3},
    -- wh_main_group_empire
    {"zerg_emp_zaskar_black_guard_cav", "special", 2},
    {"zerg_emp_zaskar_black_guard_inf", "special", 1},
    -- wh_main_group_kislev
    {"gargantulzan", "rare", 3},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
