-- Calm Kislev Erengrad (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- wh3_main_ksl
    {"calm_erengrad_cannon", "rare", 1},
    {"calm_erengrad_mortar", "special", 1},
    {"calm_kreml_guard", "special", 2},
    {"calm_kvassniks", "core"},
    {"calm_mounted_kirasirs", "special", 2},
    {"calm_ryadniks", "core"},
    {"calm_sarmatyrs", "core"},
    {"calm_storozhi", "special", 2},
    {"calm_straznik_blunderbuss", "core"},
    {"calm_urugan_cannon", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
