-- OvN Lost Factions: Albion (auto-generated by update_ttc_compat.py, do not edit)
local caps = {
    -- ovn_albion
    {"albion_centaurs_bows", "special", 2},
    {"albion_feral_gryphon_summon", "special", 2},
}

local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
