"""Read and write Yet Another Tabletop Caps compat files (`script/ttc/*.lua`)."""

import glob
import os
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Set, Tuple

HAND_DIR = "../warhammer3_mods/!!!!!!!yet_another_tabletopcaps_compat/script/ttc"
ENTRY_PATTERN = re.compile(r'\{\s*"([^"]+)"\s*,\s*"(core|special|rare)"\s*(?:,\s*(\d+))?\s*\}')
FOOTER = """local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(caps, true)
    end)
end
"""


@dataclass
class TtcEntry:
    """One `{key, category, weight}` entry from a compat file."""

    # Unit key from `main_units_tables`.
    key: str
    # `core`, `special` or `rare`.
    category: str
    # Point weight, or None when the entry has none (only `core`).
    weight: Optional[int]
    # 1-based line number in the file.
    line_no: int


def parse_ttc_text(text: str) -> List[TtcEntry]:
    """Parse every cap entry in a compat file's text.

    Args:
        text (str): File contents.

    Returns:
        The entries in file order.
    """
    entries = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        for match in ENTRY_PATTERN.finditer(line):
            weight = int(match.group(3)) if match.group(3) else None
            entries.append(TtcEntry(match.group(1), match.group(2), weight, line_no))
    return entries


def parse_ttc_file(path: str) -> List[TtcEntry]:
    """Parse every cap entry in a compat file.

    Args:
        path (str): Path to the `.lua` file.

    Returns:
        The entries in file order.
    """
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return parse_ttc_text(f.read())


def hand_files() -> List[str]:
    """List the hand-written compat files, excluding generated `_auto.lua` files.

    Returns:
        Paths sorted by filename.
    """
    paths = glob.glob(os.path.join(HAND_DIR, "!!!!!!!*.lua"))
    return sorted((p for p in paths if not p.endswith("_auto.lua")), key=lambda p: os.path.basename(p).lower())


def auto_file_path(package_name: str) -> str:
    """Return the generated compat file path for a mod.

    Args:
        package_name (str): The mod's `.pack` filename.

    Returns:
        Path of `!!!!!!!<name>_auto.lua` inside `HAND_DIR`.
    """
    name = package_name.lstrip("!").removesuffix(".pack")
    return os.path.join(HAND_DIR, f"!!!!!!!{name}_auto.lua")


def _format_entry(key: str, category: str, weight: Optional[int]) -> str:
    """Format one entry line the way the hand files do. `core` entries never get a weight, since TTC treats a missing weight as 1.

    Args:
        key (str): Unit key.
        category (str): `core`, `special` or `rare`.
        weight (Optional[int]): Point weight, or None for a weightless entry.

    Returns:
        The indented Lua line without a newline.
    """
    return f'    {{"{key}", "{category}"}},' if weight is None or category == "core" else f'    {{"{key}", "{category}", {weight}}},'


def render_auto_file(mod_label: str, groups: Dict[str, List[Tuple[str, str, Optional[int]]]]) -> str:
    """Render a generated compat file, with groups and keys sorted so the output is deterministic.

    Args:
        mod_label (str): Mod name for the header comment.
        groups (Dict[str, List[Tuple[str, str, Optional[int]]]]): Group comment to `(key, category, weight)` entries.

    Returns:
        The full file text.
    """
    lines = [f"-- {mod_label} (auto-generated by update_ttc_compat.py, do not edit)", "local caps = {"]
    for group in sorted(groups):
        lines.append(f"    -- {group}")
        lines.extend(_format_entry(*entry) for entry in sorted(groups[group], key=lambda e: e[0]))
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n" + FOOTER


def remove_lines(path: str, keys: Set[str]) -> List[str]:
    """Delete the lines holding entries for the given keys, leaving every other byte untouched.

    Args:
        path (str): Compat file to edit.
        keys (Set[str]): Unit keys whose entry lines should be removed.

    Returns:
        The removed lines, without line endings.
    """
    with open(path, "rb") as f:
        raw_lines = f.read().decode("utf-8").splitlines(keepends=True)
    kept, removed = [], []
    for line in raw_lines:
        match = ENTRY_PATTERN.search(line)
        if match and match.group(1) in keys:
            removed.append(line.rstrip("\r\n"))
        else:
            kept.append(line)
    if removed:
        with open(path, "wb") as f:
            f.write("".join(kept).encode("utf-8"))
    return removed
