--- Army spell pools, written by helper_scripts/generators/update_leapoi_spot_offers.py from generators/leapoi_army_spells.json. Do not edit by
--- hand. Each spell's bundle is land_enc_effect_tower_spell_<id> and its payload line dummy_land_enc_spot_spell_<id>.

local M = {}

--- Pool -> its spells, each { id, name }.
M.pools = {
    army = {
        { id = "army_001", name = "Legionary Barrage" },
        { id = "army_002", name = "Rictus Clanstone" },
        { id = "army_003", name = "Sand Veil" },
        { id = "army_004", name = "Tomb Swarm" },
        { id = "army_005", name = "Norse Roar" },
        { id = "army_006", name = "Rod of the Storm" },
        { id = "army_007", name = "Sartosa Grapeshot" },
        { id = "army_008", name = "Shanty: First Verse" },
        { id = "army_009", name = "Shanty: Second Verse" },
        { id = "army_010", name = "Shanty: Third Verse" },
        { id = "army_011", name = "Wraith Storm" },
        { id = "army_012", name = "Zhufbar 42-Pounders" },
        { id = "army_013", name = "Battlefield Resupply" },
        { id = "army_014", name = "Great Invocation of Sotek" },
        { id = "army_015", name = "Jungle Swarm" },
        { id = "army_016", name = "Warpstorm Doomrocket" },
        { id = "army_017", name = "Man the Cannons!" },
        { id = "army_018", name = "Beasts of Itzl" },
        { id = "army_019", name = "Protection of Quetzl" },
        { id = "army_020", name = "Storm of Xholankha" },
        { id = "army_021", name = "Shield of the Old Ones" },
        { id = "army_022", name = "Mislead" },
        { id = "army_023", name = "Azhag's Big Waaagh!" },
        { id = "army_024", name = "Azhag's Waaagh!" },
        { id = "army_025", name = "Big Waaagh!" },
        { id = "army_026", name = "Doom Diver Strike" },
        { id = "army_027", name = "Envelop in Mist" },
        { id = "army_028", name = "Grimgor's Big Waaagh!" },
        { id = "army_029", name = "Grimgor's Waaagh!" },
        { id = "army_030", name = "Grom's Big Waaagh!" },
        { id = "army_031", name = "Grom's Waaagh!" },
        { id = "army_032", name = "Invocation of Ending" },
        { id = "army_033", name = "Oath of Replenishment" },
        { id = "army_034", name = "Oath of Replenishment" },
        { id = "army_035", name = "Skarsnik's Big Waaagh!" },
        { id = "army_036", name = "Skarsnik's Waaagh!" },
        { id = "army_037", name = "Summon the Sentinels" },
        { id = "army_038", name = "Summon the Sentinels" },
        { id = "army_039", name = "Unleash the Winds" },
        { id = "army_040", name = "Waaagh!" },
        { id = "army_041", name = "Wurrzag's Big Waaagh!" },
        { id = "army_042", name = "Wurrzag's Waaagh!" },
        { id = "army_043", name = "Warden's Cage" },
        { id = "army_044", name = "Call to Ceithin-Har" },
        { id = "army_045", name = "Transformation of Kadon" },
        { id = "army_046", name = "Roused to Wrath" },
        { id = "army_047", name = "Ancestral Rune of Grimnir" },
        { id = "army_048", name = "Ancestral Rune of Grungni" },
        { id = "army_049", name = "Ancestral Rune of Valaya" },
        { id = "army_050", name = "Shatterstone" },
        { id = "army_051", name = "Sotek's Sanctum" },
        { id = "army_052", name = "Touched by the Moon" },
        { id = "army_053", name = "Tzcatli's Sanctum" },
        { id = "army_054", name = "Vile Entropy" },
        { id = "army_055", name = "Viletide" },
        { id = "army_056", name = "Xapati's Sanctum" },
        { id = "army_057", name = "Bloodwrack Cauldron" },
        { id = "army_058", name = "Bolt of Spite" },
        { id = "army_059", name = "Brazen Cauldron" },
        { id = "army_060", name = "Channelling Spire" },
        { id = "army_061", name = "Dark Conduit" },
        { id = "army_062", name = "Eagle Sanctuary" },
        { id = "army_063", name = "Eshin Clanstone" },
        { id = "army_064", name = "Feral Cold Ones" },
        { id = "army_065", name = "Geomantic Nexus" },
        { id = "army_066", name = "Holy Stela" },
        { id = "army_067", name = "Khaine's Flail" },
        { id = "army_068", name = "Khaine's Lash" },
        { id = "army_069", name = "Khaine's Scourge" },
        { id = "army_070", name = "Lure of the Pale Queen" },
        { id = "army_071", name = "Mors Clanstone" },
        { id = "army_072", name = "Moulder Clanstone" },
        { id = "army_073", name = "Pestilens Clanstone" },
        { id = "army_074", name = "Shadows of Anlec" },
        { id = "army_075", name = "Skryre Clanstone" },
        { id = "army_076", name = "Sky Cauldron" },
        { id = "army_077", name = "Soul Rain" },
        { id = "army_078", name = "Soul Storm" },
        { id = "army_079", name = "Soul Torrent" },
        { id = "army_080", name = "Temple of Mists" },
        { id = "army_081", name = "The Menace Below" },
        { id = "army_082", name = "Vaul's Hammer" },
        { id = "army_083", name = "Vortical Blast" },
        { id = "army_084", name = "Vortical Enrichment" },
        { id = "army_085", name = "Warpbomb" },
        { id = "army_086", name = "Iron Reinforcements" },
        { id = "army_087", name = "Armour of Contempt" },
        { id = "army_088", name = "Doom of Hashut" },
        { id = "army_089", name = "Guns of Zharr" },
        { id = "army_090", name = "Dreadquake Battery" },
        { id = "army_091", name = "Dreadquake Battery" },
        { id = "army_092", name = "Wrath of Zharr" },
        { id = "army_093", name = "Blood & Fireborn" },
        { id = "army_094", name = "Bjuna Bombard" },
        { id = "army_095", name = "Call of the Wild" },
        { id = "army_096", name = "Engineer's Gyrocopter Bomb" },
        { id = "army_097", name = "Launch Gyrocopters" },
        { id = "army_098", name = "Pandemicium" },
        { id = "army_099", name = "The Purple Eclipse" },
        { id = "army_100", name = "Spirit Barrage" },
        { id = "army_101", name = "Spirit of Grungni" },
        { id = "army_102", name = "Call the Miners" },
        { id = "army_103", name = "Blood God's Shackles" },
        { id = "army_104", name = "Blood God's Shackles" },
        { id = "army_105", name = "Boiling Cauldron" },
        { id = "army_106", name = "Foot of Gork" },
        { id = "army_107", name = "Gorbad's Big Waaagh!" },
        { id = "army_108", name = "Gorbad's Waaagh!" },
        { id = "army_109", name = "Khorne's Wrath" },
        { id = "army_110", name = "Asur Fire II" },
        { id = "army_111", name = "Asur Fire I" },
        { id = "army_112", name = "Asur Fire III" },
        { id = "army_113", name = "Titanic Exultation" },
        { id = "army_114", name = "Dragonship Assault" },
        { id = "army_115", name = "Dragonship Blitz" },
        { id = "army_116", name = "Dragonship Volley" },
        { id = "army_117", name = "Shamanistic Ritual (Death)" },
        { id = "army_118", name = "Shamanistic Ritual (Fire)" },
        { id = "army_119", name = "Shamanistic Ritual (Metal)" },
        { id = "army_120", name = "Ships of the Line" },
        { id = "army_121", name = "War Supplies" },
        { id = "army_122", name = "Apotheosis" },
        { id = "army_123", name = "Hand of Glory" },
        { id = "army_124", name = "Tempest" },
        { id = "army_125", name = "Mouldering Fortification" },
        { id = "army_126", name = "Mark of the Rot-Forged Legionaries" },
        { id = "army_127", name = "Bubonic Broadside" },
        { id = "army_128", name = "Summon Plague Drones" },
        { id = "army_129", name = "Summon Plague Drones (Death's heads)" },
        { id = "army_130", name = "Ryze: Crypt Horrors" },
        { id = "army_131", name = "Ryze: Grave Guard" },
        { id = "army_132", name = "Ryze: Grave Guard" },
        { id = "army_133", name = "Ryze: Khemrian Warsphinx" },
        { id = "army_134", name = "Ryze: Khemric Titan" },
        { id = "army_135", name = "Ryze: Mournguls" },
        { id = "army_136", name = "Ryze: Necrofex Colossus" },
        { id = "army_137", name = "Ryze: Nehekharan Warriors" },
        { id = "army_138", name = "Ryze: Rotting Prometheans (Gunnery Mob)" },
        { id = "army_139", name = "Ryze: Spirit Host" },
        { id = "army_140", name = "Ryze: Terrorgheist" },
        { id = "army_141", name = "Ryze: Ushabti" },
        { id = "army_142", name = "Ryze: Zombie Pirate Gunnery Mob (Bombers)" },
        { id = "army_143", name = "Scruten Clanstone" },
        { id = "army_144", name = "The Menace Below (Stormvermin)" },
        { id = "army_145", name = "Unleash" },
        { id = "army_146", name = "Oblast Outriders" },
        { id = "army_147", name = "Ancestral Warriors" },
        { id = "army_148", name = "Arcane Surge" },
        { id = "army_149", name = "Blade of Khorne" },
        { id = "army_150", name = "Bolt of Change" },
        { id = "army_151", name = "Celestial Intervention" },
        { id = "army_152", name = "Curse of the Slug" },
        { id = "army_153", name = "Fascination" },
        { id = "army_154", name = "Fecundity" },
        { id = "army_155", name = "Gluttony" },
        { id = "army_156", name = "Horn of Khorne" },
        { id = "army_157", name = "Narcissism" },
        { id = "army_158", name = "Relentless Rage" },
        { id = "army_159", name = "Rot, Glorious Rot" },
        { id = "army_160", name = "Stoneshaker" },
        { id = "army_161", name = "Storm of Fire" },
        { id = "army_162", name = "Summoned from Beyond" },
        { id = "army_163", name = "Sweet Sorrow" },
        { id = "army_164", name = "The Bitterness of Winter" },
        { id = "army_165", name = "The Land Awakened" },
        { id = "army_166", name = "Thunder Charge" },
        { id = "army_167", name = "Wrath of the Bear" },
        { id = "army_168", name = "Merciw's Monstrous Regiment" },
        { id = "army_169", name = "Ashes & Dust" },
        { id = "army_170", name = "Magma Storm" },
        { id = "army_171", name = "Thorsen's Thunderstorm" },
        { id = "army_172", name = "Greater Gate of Khorne" },
        { id = "army_173", name = "Storm of Renewal" },
        { id = "army_174", name = "Time Amok" },
        { id = "army_175", name = "Gehenna's Golden Globe" },
        { id = "army_176", name = "Dance of Despair" },
        { id = "army_177", name = "Meat Feast" },
        { id = "army_178", name = "Dismember" },
        { id = "army_179", name = "Massacre" },
        { id = "army_180", name = "Biting Wind" },
        { id = "army_181", name = "Diabolical Puppetry" },
        { id = "army_182", name = "Inevitable Fate" },
        { id = "army_183", name = "Tempest of Blue Flame" },
    },
    bound = {
        { id = "bound_001", name = "Arnzipal's Black Horror" },
        { id = "bound_002", name = "Assault of Stone" },
        { id = "bound_003", name = "Blast" },
        { id = "bound_004", name = "Lesser Doombolt" },
        { id = "bound_005", name = "Fiery Convocation" },
        { id = "bound_006", name = "Soul Stealer" },
        { id = "bound_007", name = "Soulblight" },
        { id = "bound_008", name = "Word of Pain" },
        { id = "bound_009", name = "The Purple Sun of Xereus" },
        { id = "bound_010", name = "Tidecall" },
        { id = "bound_011", name = "Wind Blast" },
        { id = "bound_012", name = "Warp-Fireball" },
        { id = "bound_013", name = "Gaze of Nagash" },
        { id = "bound_014", name = "Wind of Death" },
        { id = "bound_015", name = "Death Frenzy" },
        { id = "bound_016", name = "Flesh to Stone" },
        { id = "bound_017", name = "Regrowth" },
        { id = "bound_018", name = "Lesser Raise Dead" },
        { id = "bound_019", name = "Lesser Banishment" },
        { id = "bound_020", name = "Lesser Chain Lightning" },
        { id = "bound_021", name = "Savage Dominion" },
        { id = "bound_022", name = "Shield of Thorns" },
        { id = "bound_023", name = "Urannon's Thunderbolt" },
        { id = "bound_024", name = "Klad Brakak" },
        { id = "bound_025", name = "Gilded Horn of Galon Konook" },
        { id = "bound_026", name = "Pestilent Breath" },
        { id = "bound_027", name = "Scorch" },
        { id = "bound_028", name = "Black Staff" },
        { id = "bound_029", name = "Embers of the Phoenix" },
        { id = "bound_030", name = "Hand of Gods" },
        { id = "bound_031", name = "Bound Fiery Convocation" },
        { id = "bound_032", name = "Radiant Gem of Hoeth" },
        { id = "bound_033", name = "Ring of Corin" },
        { id = "bound_034", name = "Rod of the Storm" },
        { id = "bound_035", name = "Rubric of Dark Dimensions" },
        { id = "bound_036", name = "The Gem of Sunfire" },
        { id = "bound_037", name = "The Seerstaff of Saphery" },
        { id = "bound_038", name = "Tome of Furion" },
        { id = "bound_039", name = "Wand of the Kharaidon" },
        { id = "bound_040", name = "Whip of Misery" },
        { id = "bound_041", name = "Reaver Bow" },
        { id = "bound_042", name = "Winged Staff" },
        { id = "bound_043", name = "Ashes & Dust" },
        { id = "bound_044", name = "Dance of Despair" },
        { id = "bound_045", name = "Gehenna's Golden Globe" },
        { id = "bound_046", name = "Magma Storm" },
        { id = "bound_047", name = "Merciw's Monstrous Regiment" },
        { id = "bound_048", name = "Storm of Renewal" },
        { id = "bound_049", name = "Thorsen's Thunderstorm" },
        { id = "bound_050", name = "Time Amok" },
        { id = "bound_051", name = "Fleshy Abundance" },
        { id = "bound_052", name = "Gehenna's Golden Hounds" },
        { id = "bound_053", name = "Infernal Gateway" },
        { id = "bound_054", name = "Pink Fire of Tzeentch" },
        { id = "bound_055", name = "Slicing Shards" },
        { id = "bound_056", name = "Stream of Corruption" },
        { id = "bound_057", name = "The Penumbral Pendulum" },
        { id = "bound_058", name = "Breath of Hatred" },
        { id = "bound_059", name = "Burning Wrath" },
        { id = "bound_060", name = "Hell Hammer" },
        { id = "bound_061", name = "Missile Mirror" },
        { id = "bound_062", name = "The Burning Head" },
        { id = "bound_063", name = "Bonecrusher" },
        { id = "bound_064", name = "Trollguts" },
        { id = "bound_065", name = "Acquiescence" },
        { id = "bound_066", name = "Fireball" },
        { id = "bound_067", name = "Doom & Darkness" },
        { id = "bound_068", name = "Transformation of Kadon" },
        { id = "bound_069", name = "Fog of the Damned" },
        { id = "bound_070", name = "Lesser Awakening from the Grave" },
        { id = "bound_071", name = "Curse of Years" },
        { id = "bound_072", name = "Eye for an Eye" },
        { id = "bound_073", name = "Invocation of Nehek" },
        { id = "bound_074", name = "Okkam's Mindrazor" },
        { id = "bound_075", name = "Irresistible Plague!" },
        { id = "bound_076", name = "Plaguemaster" },
        { id = "bound_077", name = "Ferocious Fury of Ulric" },
        { id = "bound_078", name = "Fury of Ulric" },
        { id = "bound_079", name = "Skitterleap" },
        { id = "bound_080", name = "The Dreaded Thirteenth Spell" },
        { id = "bound_081", name = "The Soulstealer" },
        { id = "bound_082", name = "Breath of Darkness" },
        { id = "bound_083", name = "Breath of Darkness" },
        { id = "bound_084", name = "The Hand of Dust" },
        { id = "bound_085", name = "The Abyssal Swarm" },
        { id = "bound_086", name = "Master of Lightning" },
        { id = "bound_087", name = "Celestial Comet" },
        { id = "bound_088", name = "Celestial Lightning" },
        { id = "bound_089", name = "Ancestral Warriors" },
        { id = "bound_090", name = "Banishment" },
        { id = "bound_091", name = "Cascading Fire Cloak" },
        { id = "bound_092", name = "Comet of Casandora" },
        { id = "bound_093", name = "Earth Blood" },
        { id = "bound_094", name = "The Enfeebling Foe" },
        { id = "bound_095", name = "Flame Storm" },
        { id = "bound_096", name = "Flock of Doom" },
        { id = "bound_097", name = "Harmonic Convergence" },
        { id = "bound_098", name = "Lash of Slaanesh" },
        { id = "bound_099", name = "Pha's Protection" },
        { id = "bound_100", name = "Pit of Shades" },
        { id = "bound_101", name = "Plague of Rust" },
        { id = "bound_102", name = "Rancid Visitations" },
        { id = "bound_103", name = "Spirit Leech" },
        { id = "bound_104", name = "The Curse of Anraheir" },
        { id = "bound_105", name = "The Dwellers Below" },
        { id = "bound_106", name = "The Fate of Bjuna" },
        { id = "bound_107", name = "Transmutation of Lead" },
        { id = "bound_108", name = "Wall of Wind & Fire" },
        { id = "bound_109", name = "Call of Tor" },
        { id = "bound_110", name = "Heart of Winter" },
        { id = "bound_111", name = "Searing Doom" },
        { id = "bound_112", name = "The Withering" },
        { id = "bound_113", name = "The Amber Spear" },
        { id = "bound_114", name = "Viletide" },
        { id = "bound_115", name = "Grand Hammer of Sigmar" },
        { id = "bound_116", name = "Net of Amyntok" },
        { id = "bound_117", name = "Grand Shield of Faith" },
        { id = "bound_118", name = "Grand Soulfire" },
        { id = "bound_119", name = "Vindictive Glare" },
        { id = "bound_120", name = "Birona's Timewarp" },
        { id = "bound_121", name = "Book of Arkhan" },
        { id = "bound_122", name = "Chain Lightning" },
        { id = "bound_123", name = "Fireball" },
        { id = "bound_124", name = "Hammer of Sigmar" },
        { id = "bound_125", name = "Piercing Bolts of Burning" },
        { id = "bound_126", name = "Shield of Faith" },
        { id = "bound_127", name = "Soulfire" },
        { id = "bound_128", name = "Staff of Damnation" },
    },
    lore = {
        { id = "lore_001", name = "Djaf's Incantation of Cursed Blades" },
        { id = "lore_002", name = "Neru's Incantation of Protection" },
        { id = "lore_003", name = "Ptra's Incantation of Righteous Smiting" },
        { id = "lore_004", name = "Sakhmet's Incantation of the Skullstorm" },
        { id = "lore_005", name = "Usekhp's Incantation of Desiccation" },
        { id = "lore_006", name = "Usirian's Incantation of Vengeance" },
        { id = "lore_007", name = "Denizens of the Deep" },
        { id = "lore_008", name = "Vangheist's Revenge" },
        { id = "lore_009", name = "Kraken's Pull" },
        { id = "lore_010", name = "Spiteful Shot" },
        { id = "lore_011", name = "Drowned Dead" },
        { id = "lore_012", name = "Flensing Ruin" },
        { id = "lore_013", name = "Armour of Darkness" },
        { id = "lore_014", name = "Black Whirlwind" },
        { id = "lore_015", name = "Brittle Bone" },
        { id = "lore_016", name = "Veil of Shadows" },
        { id = "lore_017", name = "Warp Stars" },
        { id = "lore_018", name = "Bladewind" },
        { id = "lore_019", name = "Chillwind" },
        { id = "lore_020", name = "Doombolt" },
        { id = "lore_021", name = "Power of Darkness" },
        { id = "lore_022", name = "Apotheosis" },
        { id = "lore_023", name = "Arcane Unforging" },
        { id = "lore_024", name = "Hand of Glory" },
        { id = "lore_025", name = "Soul Quench" },
        { id = "lore_026", name = "Tempest" },
        { id = "lore_027", name = "Bless with Filth" },
        { id = "lore_028", name = "Pestilent Birth" },
        { id = "lore_029", name = "Plague" },
        { id = "lore_030", name = "Vermintide" },
        { id = "lore_031", name = "Wither" },
        { id = "lore_032", name = "Crack's Call" },
        { id = "lore_033", name = "Howling Warpgale" },
        { id = "lore_034", name = "Warp Lightning" },
        { id = "lore_035", name = "Ash Storm" },
        { id = "lore_036", name = "Curse of Hashut" },
        { id = "lore_037", name = "Dark Subjugation" },
        { id = "lore_038", name = "Flames of Azgorh" },
        { id = "lore_039", name = "Curse of the Ancient Witch" },
        { id = "lore_040", name = "Cursed Cauldron" },
        { id = "lore_041", name = "Malediction of Madness" },
        { id = "lore_042", name = "The Forbidden Fens" },
        { id = "lore_043", name = "Vengeance of Spirits" },
        { id = "lore_044", name = "Witchbrew" },
        { id = "lore_045", name = "Flensing Haar" },
        { id = "lore_046", name = "Ladrielle's Shroud" },
        { id = "lore_047", name = "Mathlann’s Spite" },
        { id = "lore_048", name = "Mistress of the Deeps" },
        { id = "lore_049", name = "The Writhing Mist" },
        { id = "lore_050", name = "Walk Between Worlds" },
        { id = "lore_051", name = "Raise Dead (Skeleton Warriors)" },
        { id = "lore_052", name = "The Dark Riders" },
        { id = "lore_053", name = "The Harbinger" },
        { id = "lore_054", name = "Braingobbler" },
        { id = "lore_055", name = "Bullgorger" },
        { id = "lore_056", name = "The Maw" },
        { id = "lore_057", name = "Toothcracker" },
        { id = "lore_058", name = "Crystal Sanctuary" },
        { id = "lore_059", name = "Death Frost" },
        { id = "lore_060", name = "Frost Blades" },
        { id = "lore_061", name = "Ice Maiden's Kiss" },
        { id = "lore_062", name = "Ice Sheet" },
        { id = "lore_063", name = "Curse of the Leper" },
        { id = "lore_064", name = "Miasma of Pestilence" },
        { id = "lore_065", name = "Blight Boil" },
        { id = "lore_066", name = "Hysterical Frenzy" },
        { id = "lore_067", name = "Pavane of Slaanesh" },
        { id = "lore_068", name = "Phantasmagoria" },
        { id = "lore_069", name = "Biting Wind" },
        { id = "lore_070", name = "Blizzard" },
        { id = "lore_071", name = "Gust of True Flight" },
        { id = "lore_072", name = "Hailstorm" },
        { id = "lore_073", name = "Hawks of Miska" },
        { id = "lore_074", name = "Swiftwing" },
        { id = "lore_075", name = "Blue Fire of Tzeentch" },
        { id = "lore_076", name = "Glean Magic" },
        { id = "lore_077", name = "Treason of Tzeentch" },
        { id = "lore_078", name = "Tzeentch's Firestorm" },
        { id = "lore_079", name = "Constellation of the Dragon" },
        { id = "lore_080", name = "Dragon's Breath" },
        { id = "lore_081", name = "Jade Shield" },
        { id = "lore_082", name = "Might of Heaven & Earth" },
        { id = "lore_083", name = "Stone Ground Stance" },
        { id = "lore_084", name = "Blossom Wind" },
        { id = "lore_085", name = "Cloak of Jet" },
        { id = "lore_086", name = "Storm of Shadows" },
        { id = "lore_087", name = "Talons of Night" },
        { id = "lore_088", name = "Pann's Impenetrable Pelt" },
        { id = "lore_089", name = "Wyssan's Wildform" },
        { id = "lore_090", name = "Bray-Scream" },
        { id = "lore_091", name = "Devolve" },
        { id = "lore_092", name = "Mantle of Ghorok" },
        { id = "lore_093", name = "Traitor-Kin" },
        { id = "lore_094", name = "Awakening of the Wood" },
        { id = "lore_095", name = "Melkoth's Mystifying Miasma" },
        { id = "lore_096", name = "Brain Bursta" },
        { id = "lore_097", name = "'Eadbutt" },
        { id = "lore_098", name = "'Ere We Go" },
        { id = "lore_099", name = "Fists of Gork" },
        { id = "lore_100", name = "Foot of Gork" },
        { id = "lore_101", name = "Gaze of Mork" },
        { id = "lore_102", name = "Aspect of the Dread Knight" },
        { id = "lore_103", name = "Flaming Sword of Rhuin" },
        { id = "lore_104", name = "Curse of the Midnight Wind" },
        { id = "lore_105", name = "Light of Battle" },
        { id = "lore_106", name = "Shem's Burning Gaze" },
        { id = "lore_107", name = "Curse of Da Bad Moon" },
        { id = "lore_108", name = "Gork'll Fix It" },
        { id = "lore_109", name = "Itchy Nuisance" },
        { id = "lore_110", name = "Night Shroud" },
        { id = "lore_111", name = "Sneaky Stabbin'" },
        { id = "lore_112", name = "Final Transmutation" },
        { id = "lore_113", name = "Glittering Robe" },
        { id = "lore_114", name = "Raise Dead" },
        { id = "lore_115", name = "Vanhel's Danse Macabre" },
    },
}

return M
