--- Coordinates for all three supported campaigns.
--- Keyed by campaign id ("immortal_empires", "realm_of_chaos", "immortal_empires_expanded").

local M = {}

--- //////////////////////////////////////////////////////////////////////////////////////////////////
--- //////////////////////////////////////////////////////////////////////////////////////////////////
--- immortal_empires

--- Auto generated by algorithm in Apr 30, 2023.
--- Map: im_coordinates.
M.immortal_empires = {
    treasures_and_spots = {
         ["southernchaoswastes"] = {
              --- The Daemonium Hills
              {808, 44},
              {785, 32},
              {738, 42, manual = true},
              --- The Abyssal Glacier
              {693, 32},
              {642, 22},
              {595, 31, manual = true},
              --- The Southern Wastes
              {535, 27},
              {490, 33, disabled = true},
              {473, 71},
              {457, 36},
              {436, 53},
              {385, 51},
              --- The Ice Fire Plains
              {315, 30},
              {299, 23},
              {271, 35},
              {230, 32},
         },
         ["southlands"] = {
              --- Dawn's Landing
              {581, 83},
              {603, 72},
              {627, 85},
              --- The Jungle of the Gods
              {693, 103},
              {701, 131},
              {707, 168},
              --- Southern Jungles
              {591, 103},
              {637, 120, disabled = true},
              {634, 142},
              --- Kingdom of Beasts
              {756, 235, manual = true},
              {801, 229},
              --- The Golden Pass
              {704, 195},
              {732, 167},
              {764, 198, manual = true},
              --- Heart of the Jungle
              {655, 210},
              --- Central Jungles
              {610, 160},
              {647, 177},
              {614, 200},
              {644, 194},
              --- Western Jungles
              {524, 218},
              {530, 196},
              {567, 174, manual = true},
         },
         ["nehekara"] = {
              --- Shifting Sands
              {589, 255},
              {621, 250},
              {661, 258},
              {610, 235},
              {648, 231},
              {668, 227},
              --- Land of the Dervishes
              {572, 233},
              {560, 266},
              --- Great Desert of Araby
              {503, 250},
              {463, 277},
              {505, 280},
              --- Land of Assasins
              {440, 259},
              {440, 304, disabled = true},
              {457, 322},
              --- Crater of the Waking Dead
              {784, 286},
              {806, 268},
              {820, 318},
              {815, 331},
              --- Devil's Backbone
              {693, 314},
              {775, 308, manual = true},
              --- Land of the Dead
              {630, 288, disabled = true},
              {676, 294},
              {615, 311},
              {646, 310},
              --- Great Mortis Delta
              {595, 277},
              --- The Cracked Land
              {528, 273},
              {563, 295},
              {516, 309},
              {556, 313},
              --- Coast of Araby
              {491, 330},
         },
         ["badlands"] = {
              --- The Barrier Idols
              {662, 319},
              {685, 327},
              {704, 327, manual = true},
              {640, 345},
              {681, 341, manual = true},
              {720, 365},
              --- Blightwater
              {778, 380, manual = true},
              {726, 388, manual = true},
              {761, 397},
              --- Marshes of Madness
              {668, 358},
              {701, 383},
              {644, 389},
              {657, 404},
              {697, 405},
              --- Southern Badlands
              {585, 352},
              {565, 355},
              {591, 373},
              {625, 386},
              {607, 392},
              {601, 412},
              --- Eastern Badlands
              {712, 438},
              {765, 428},
              --- Western Badlands
              {676, 413, manual = true},
              {647, 435},
              {665, 437, manual = true},
              {701, 460},
              {649, 471},
              --- Death Pass
              {741, 465},
              {765, 474, disabled = true},
              {711, 481},
              {784, 489},
              --- Blood River Valley
              {650, 496, disabled = true},
              {684, 493},
              {715, 516},
         },
         ["lustria"] = {
              --- The Capes
              {285, 116, manual = true},
              --- Culchan Plains
              {262, 131},
              {219, 145},
              {241, 138},
              {238, 169},
              --- The Night Forest Road
              {267, 102},
              {250, 101, manual = true},
              {209, 117},
              {183, 127},
              {168, 137, manual = true},
              --- Headhunter's Jungle
              {222, 181},
              {218, 215},
              {242, 221},
              --- The Lost Valley
              {204, 172},
              {176, 184},
              {194, 196},
              {165, 198},
              --- Spine of Sotek
              {169, 169, disabled = true},
              {120, 182, manual = true},
              {111, 204},
              --- Copper Desert
              {135, 155},
              {118, 183},
              --- Vampire Coast
              {285, 278},
              {242, 290},
              --- Mosquito Swamps
              {214, 229},
              {203, 240, manual = true},
              {250, 256},
              {215, 281},
              --- River Qurveza
              {153, 216},
              {198, 223},
              {168, 226},
              {131, 225},
              {151, 246},
              {184, 243, disabled = true},
              --- The Turtle Isles
              {89, 228},
              {73, 237},
              {86, 260},
              {58, 269},
              {54, 300},
              --- Piranha Swamps
              {220, 296},
              {163, 330},
              {202, 337},
              --- The Gwangee Valley
              {183, 268},
              {164, 293},
              {126, 310},
              {147, 313},
              {117, 335},
              {145, 336},
              --- Jungle of Green Mist
              {50, 329},
              {70, 366},
              --- The Creeping Jungle
              {117, 352},
              {167, 361},
              {93, 364},
              {136, 369},
              --- Aymara Swamps
              {110, 399},
              --- Jungle of Pahualaxa
              {107, 418},
              {47, 438},
              {127, 441},
              {81, 456},
              {121, 451, manual = true},
              --- The Isthmus Coast
              {87, 480, disabled = true},
              {106, 504},
              {100, 529},
              --- Isthmus of Lustria
              {57, 452},
              {47, 483, manual = true},
              {51, 495},
              {82, 494},
         },
         ["cathay"] = {
              --- Broken Lands of Tian Li
              {1245, 404},
              {1202, 396, disabled = true},
              {1192, 422, manual = true},
              {1171, 431},
              {1144, 455},
              {1210, 464},
              --- The Great Canal
              {1290, 367},
              {1242, 376},
              {1259, 393},
              {1272, 415},
              {1270, 435},
              --- Serpent Stuary
              {1365, 361},
              {1352, 404},
              --- Mount Li
              {1379, 420},
              {1295, 464, manual = true},
              {1382, 447, manual = true},
              --- Nongchang Basin
              {1264, 473},
              {1299, 455},
              {1309, 494},
              {1258, 506},
              --- Celestial Riverlands
              {1233, 477},
              {1175, 485},
              {1219, 484},
              {1154, 494},
              {1207, 521},
              --- Wastelands of Jinshen
              {1140, 467},
              {1113, 485, disabled = true},
              {1135, 500},
              {1154, 517},
              --- Jade River Delta
              {1350, 496, disabled = true},
              {1354, 526, disabled = true},
              {1307, 518},
              {1332, 546, manual = true},
              --- Forest of the Moon
              {1246, 533, manual = true},
              {1308, 544, manual = true},
              {1318, 556},
              {1232, 567, manual = true},
              {1234, 592},
              --- Warpstone Desert
              {1160, 551},
              {1195, 558, manual = true},
              {1128, 576},
              {1152, 584},
              {1124, 607},
              --- Plains of Xen
              {1361, 580},
              {1335, 585},
              {1331, 622},
              --- Imperial Road
              {1296, 607, manual = true},
              {1268, 601},
              {1229, 607, manual = true},
              {1291, 626},
              --- Lands of Stone and Steel
              {1163, 604, manual = true},
              {1210, 626},
              {1177, 635},
              {1252, 639},
              {1196, 647},
              --- Gunpowder Road
              {1143, 618, disabled = true},
              {1135, 635, manual = true},
              {1161, 644},
         },
         ["mountainsofmourn"] = {
              --- Wyrm Pass
              {1057, 450},
              {1087, 502},
              {1065, 531},
              --- Ivory Road
              {1009, 483},
              {1040, 487},
              {1013, 507},
              {1000, 532},
              --- Mountains of Mourn
              {1032, 546},
              {1093, 569, disabled = true},
              {1012, 577},
              --- Bone Road
              {972, 588},
              {1062, 589},
              {1029, 601},
              {984, 607},
              {1049, 613},
              --- Ancient Giant Lands
              {966, 637},
              {996, 646},
              {1038, 641},
              {980, 656},
              {1012, 662},
              --- Gash Kadrak
              {1056, 664},
              {976, 682},
              {1000, 674},
              {1043, 694},
              --- Path to the East
              {997, 705},
              {909, 692},
         },
         ["darklands"] = {
              --- The Dragon Isles
              {979, 365},
              {1009, 379},
              {984, 390},
              {1011, 425},
              --- Gnoblar Country
              {1011, 425},
              {992, 444},
              {1033, 442},
              {1084, 438, manual = true},
              --- Mouth of Ruin
              {941, 443},
              {903, 419},
              --- The Plain of Bones
              {860, 437, manual = true},
              {902, 449, manual = true},
              {852, 461},
              --- The Howling Wastes
              {955, 463},
              {941, 495, manual = true},
              {956, 536, manual = true},
              --- The Desolation of Azgorh
              {849, 483},
              {893, 489},
              {866, 509},
              {901, 507},
              --- The Wolf Lands
              {841, 536},
              {878, 540},
              {933, 535},
              --- The Plain of Zharr
              {948, 560},
              {948, 599},
              {936, 629},
              --- The Blasted Wastes
              {893, 586},
              {871, 608},
              {850, 625},
              {880, 645},
              {847, 650},
              --- Zorn Uzkul
              {919, 647},
              {851, 680},
              {894, 691},
              {854, 706},
         },
         ["worldsedgemountains"] = {
              --- Southlands Worlds Edge Mountains
              {697, 235},
              {709, 258},
              {739, 296, disabled = true},
              --- Broken Teeth
              {830, 395},
              {872, 396},
              --- Eight Peaks
              {719, 450},
              {783, 461},
              --- Southern World's Edge Mountains
              {793, 440, disabled = true},
              {816, 443},
              {796, 459},
              --- The Silver Road
              {793, 527, disabled = true},
              {730, 540},
              {774, 545},
              --- Deadrock Gap
              {804, 573},
              --- Black Water
              {731, 585},
              {711, 599},
              --- Rib Peaks
              {781, 604},
              {802, 613},
              --- Peak Pass
              {783, 639},
              {803, 649},
              --- Northern World's Edge Mountains
              {792, 696},
              {763, 687},
              {749, 665},
         },
         ["empire"] = {
              --- Southern Sylvania
              {668, 592},
              {691, 592},
              {711, 628},
              --- Northern Sylvania
              {686, 637},
              {727, 664, manual = true},
              --- Mootland
              {653, 616},
              --- Solland
              {588, 557},
              {628, 568},
              --- Averland
              {663, 576},
              {585, 599},
              {633, 606},
              --- Stirland
              {574, 623},
              {631, 629},
              {663, 646},
              --- Wissenland
              {575, 578},
              {551, 595, disabled = true},
              {560, 615},
              --- Ostermark
              {679, 651},
              {683, 673},
              {701, 697},
              --- Talabecland
              {565, 645},
              {602, 646},
              {644, 662},
              {598, 675},
              {649, 678},
              {667, 721},
              --- Reikland
              {528, 609},
              {533, 626},
              {496, 636},
              --- Hochland
              {608, 708},
              --- Middenland
              {539, 677},
              {565, 704},
              {551, 717, manual = true},
              --- Wasteland
              {439, 668},
              {476, 679},
              {486, 695},
              {463, 705},
              {473, 721},
              --- Ostland
              {656, 736},
              {606, 765, manual = true},
              {654, 757},
              --- Nordland
              {562, 744},
              {518, 750},
              {561, 765},
              --- The Misty Hills
              {512, 724},
              {496, 737},
         },
         ["kislev"] = {
              --- Eastern Oblast
              {755, 768},
              {779, 775},
              {739, 785, manual = true},
              --- The Cursed City
              {710, 764},
              {729, 783},
              --- River Urskoy
              {707, 750, disabled = true},
              --- Southern Oblast
              {727, 721},
              {693, 728},
              {677, 752},
              --- Rock Pass
              {711, 798},
              --- Troll Country
              {695, 764},
              {679, 779},
              {685, 799},
              --- River Lynsk
              {643, 783, disabled = true},
              --- Western Oblast
              {618, 806},
              {655, 812},
         },
         ["norsca"] = {
              --- Goromadny Mountains
              {842, 737},
              {769, 810},
              {741, 820},
              --- Gianthome Mountains
              {738, 842},
              {704, 861, manual = true},
              --- Mountains of Hel
              {614, 859, manual = true},
              {671, 848, disabled = true},
              {659, 870, manual = true},
              {592, 879},
              --- Trollheim Mountains
              {586, 829},
              {572, 846},
              --- Mountains of Naglfari
              {508, 850},
              {495, 820, disabled = true},
              {547, 844},
              --- Helspire Mountains
              {403, 835, manual = true},
              {525, 875, manual = true},
              {570, 887},
              --- Ice Tooth Mountains
              {445, 764},
              {542, 796, manual = true},
              --- Vanaheim Mountains
              {386, 790},
              {466, 812},
              --- Albion
              {364, 761},
         },
         ["borderprinces"] = {
              --- E. Border Princes
              {623, 502},
              {653, 518, disabled = true},
              {604, 519},
              {692, 534},
              --- W. Border Princes
              {533, 403},
              {553, 435},
              {586, 447},
              {563, 456},
              {581, 475},
              --- Tilea
              {516, 397},
              {527, 417},
              {507, 445, disabled = true},
              {507, 470},
              --- Estalia
              {428, 425, disabled = true},
              {392, 438},
              --- Irrana Mountains
              {391, 459},
              {410, 472},
              {429, 481},
         },
         ["greymountains"] = {
              --- Black Mountains
              {608, 537, disabled = true},
              {635, 544},
              --- The Vaults
              {512, 477, manual = true},
              {578, 532, disabled = true},
              --- Southern Grey Mountains
              {516, 584},
         },
         ["bretonnia"] = {
              --- Forest of Chalons
              {450, 549},
              {486, 564},
              --- Carcassone
              {444, 488, disabled = true},
              {440, 517},
              {481, 525, manual = true},
              {413, 547},
              --- Bastonne
              {456, 590, manual = true},
              {425, 612, disabled = true},
              {448, 612},
              --- River Brienne
              {415, 584},
              {397, 600},
              --- Forest of Arden
              {421, 633},
              --- Coast of Lyonesse
              {375, 611},
              {364, 646},
              {392, 642},
              --- Marches of Couronne
              {403, 660},
              {423, 693},
         },
         ["ulthuan"] = {
              --- Southern Yvresse
              {301, 529},
              {325, 549},
              --- Eataine
              {264, 512, disabled = true},
              {304, 522},
              {264, 544},
              --- Caledor
              {221, 509},
              --- Northern Yvresse
              {345, 574},
              {333, 586, manual = true},
              --- Saphery
              {292, 551},
              {294, 573},
              --- Averlorn
              {275, 591},
              {258, 599, manual = true},
              --- Ellyrion
              {203, 567},
              {220, 592, manual = true},
              --- Tiranoc
              {177, 550, manual = true},
              {178, 562},
              {177, 585},
              --- Cothique
              {318, 614},
              --- Chrace
              {253, 645, manual = true},
              {302, 632, manual = true},
              --- Nagarythe
              {186, 617},
              {215, 624},
              {256, 648},
         },
         ["naggarond"] = {
              --- Deadwood
              {260, 832},
              {246, 843, manual = true},
              {263, 858},
              --- The Road of Skulls
              {206, 836},
              {201, 860},
              {207, 883},
              --- Spiteful Peaks
              {169, 828, manual = true},
              {181, 827},
              {152, 832},
              {145, 878, manual = true},
              --- Iron Foothills
              {99, 834},
              {77, 856, manual = true},
              --- The Black Flood
              {147, 767},
              {91, 767},
              {109, 791},
              {128, 797},
              --- Iron Mountains
              {58, 788},
              {72, 801},
              {81, 817},
              {58, 825},
              --- Iron Coast
              {21, 769},
              {16, 804, manual = true},
              {17, 842},
              {34, 851},
              --- Doom Glades
              {102, 650},
              {130, 675},
              {90, 681, manual = true},
              --- The Bleak Coast
              {114, 565},
              {124, 588},
              {109, 616},
              {95, 633},
              --- Titan Peaks
              {66, 551},
              {95, 548},
              {81, 563},
              --- Ashen Coast
              {33, 519},
              {28, 548},
              {15, 583},
              {18, 609},
              --- Ironsand Desert
              {33, 625},
              {49, 628},
              {85, 643},
              --- The Broken Lands
              {255, 766},
              {266, 782},
              {265, 803, disabled = true},
              --- Granite Hills
              {185, 758},
              {222, 763},
              {199, 776},
              {228, 785},
              --- The Clawed Coast
              {215, 703},
              {195, 707, disabled = true},
              {172, 734},
              {213, 735},
              --- Obsidian Peaks
              {135, 697},
              {46, 699},
              {74, 712},
              {159, 710},
              {88, 732, manual = true},
              {153, 734},
              {72, 747},
              --- Red Desert
              {40, 648},
              {30, 666},
              {45, 697},
              {24, 710},
              {30, 740},
         },
         ["northernchaoswastes"] = {
              --- The Red Wastes
              {1349, 658, disabled = true},
              {1267, 668},
              {1302, 676, manual = true},
              {1175, 686, manual = true},
              {1237, 684},
              --- Eastern Steppes
              {1273, 703, manual = true},
              {1232, 702},
              {1189, 707},
              --- Stonesky Foothills
              {1170, 697},
              {1088, 698},
              {1056, 715},
              {1131, 710},
              --- Chimera Plateau
              {1029, 728},
              {1021, 761},
              {1042, 787},
              {998, 785},
              --- K'datha
              {959, 810},
              {980, 830},
              {1014, 823, disabled = true},
              --- The Skull Road
              {852, 758},
              {874, 773, manual = true},
              {839, 800},
              {868, 808},
              {798, 820},
              --- The Blood Marshes
              {938, 829},
              {866, 834, manual = true},
              {925, 850},
              {827, 856},
              {904, 871},
              --- Bloodfire Falls
              {775, 857},
              {806, 868},
              {838, 893},
              {804, 900, manual = true},
              --- Plain of Illusions
              {728, 906, manual = true},
              {734, 920},
              {770, 924, manual = true},
              {676, 937, manual = true},
              {705, 927, manual = true},
              --- The N. Tumour
              {695, 913},
              {630, 921},
              {605, 937},
              {640, 916, manual = true},
              --- The Eternal Lagoon
              {528, 924, manual = true},
              {591, 931},
              {521, 953},
              --- The Cold Mires
              {458, 899, manual = true},
              {400, 899, disabled = true},
              {467, 925},
              {487, 951, manual = true},
              --- Northern Wastes
              {411, 913, manual = true},
              {406, 926},
              {364, 924},
              {456, 936, manual = true},
              --- The Shard Lands
              {331, 856},
              {380, 882},
              {322, 883},
              {363, 897},
              {317, 907},
              --- The Frigid Wasteland
              {250, 896},
              {160, 896},
              {206, 901},
              {284, 909, manual = true},
              --- Ironfrost Glacier
              {69, 888, manual = true},
              {139, 891},
              {39, 897, manual = true},
              {99, 896},
         },
    },
    points_of_interest = {
        ["southernchaoswastes"] = {
            ["smithies"] = {
                { coordinates = {334, 26}, initial_owner = "wh3_main_tze_oracles_of_tzeentch", owner_if_player = "wh3_main_nur_bubonic_swarm", region = "", manual = true },
                { coordinates = {562, 38}, initial_owner = "wh2_dlc17_lzd_oxyotl", owner_if_player = "wh3_main_tze_flaming_scribes", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {352, 41}, initial_owner = "wh3_main_tze_flaming_scribes", owner_if_player = "wh3_main_tze_flaming_scribes", manual = true },
            },

            ["resources"] = {}
         },
         ["southlands"] = {
            ["smithies"] = {
                { coordinates = {648, 92}, initial_owner = "wh2_main_hef_order_of_loremasters", owner_if_player = "wh3_main_tze_oracles_of_tzeentch", region = "", manual = true },
                { coordinates = {552, 213}, initial_owner = "wh2_main_lzd_tlaqua", owner_if_player = "wh3_main_emp_cult_of_sigmar", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {637, 120}, culture = "lzd", initial_owner = "wh2_main_lzd_zlatan", owner_if_player = "wh2_main_lzd_zlatan", manual = true },
            },

            ["resources"] = {}
         },
         ["nehekara"] = {
            ["smithies"] = {
                { coordinates = {638, 263}, initial_owner = "wh2_dlc09_tmb_khemri", owner_if_player = "wh_main_vmp_vampire_counts", region = "", manual = true },
                { coordinates = {467, 331}, initial_owner = "wh2_dlc09_tmb_followers_of_nagash", owner_if_player = "wh2_main_brt_thegans_crusaders", region = "", manual = true },
                { coordinates = {789, 268}, initial_owner = "wh2_dlc09_tmb_lybaras", owner_if_player = "wh2_main_vmp_the_silver_host", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {630, 288}, culture = "tmb", initial_owner = "wh2_dlc09_tmb_khemri", owner_if_player = "wh2_dlc09_tmb_khemri", manual = true },
                { coordinates = {440, 304}, initial_owner = "wh2_main_brt_knights_of_the_flame", owner_if_player = "wh2_main_brt_knights_of_the_flame", manual = true },
            },

            ["resources"] = {}
         },
         ["badlands"] = {
            ["smithies"] = {
                { coordinates = {606, 321}, initial_owner = "wh2_dlc09_tmb_khemri", owner_if_player = "wh3_main_kho_exiles_of_khorne", region = "", manual = true },
                { coordinates = {629, 417}, initial_owner = "wh_main_grn_orcs_of_the_bloody_hand", owner_if_player = "wh3_main_ogr_disciples_of_the_maw", region = "", manual = true },
                { coordinates = {809, 364}, initial_owner = "wh2_main_skv_clan_mors", owner_if_player = "wh2_dlc09_tmb_lybaras", region = "", manual = true },
                { coordinates = {717, 521}, initial_owner = "wh_main_dwf_dwarfs", owner_if_player = "wh_main_teb_border_princes", region = "", manual = true },
                { coordinates = {691, 390}, initial_owner = "wh3_main_ie_vmp_sires_of_mourkain", owner_if_player = "wh3_main_ie_vmp_sires_of_mourkain", region = "" }
            },

            ["taverns"] = {
                { coordinates = {650, 496}, initial_owner = "wh_main_grn_scabby_eye", owner_if_player = "wh_main_grn_scabby_eye", manual = true },
                { coordinates = {765, 474}, culture = "grn", initial_owner = "wh3_dlc26_grn_gorbad_ironclaw", owner_if_player = "wh3_dlc26_grn_gorbad_ironclaw", manual = true },
            },

            ["resources"] = {}
         },
         ["lustria"] = {
            ["smithies"] = {
                { coordinates = {87, 438}, initial_owner = "wh2_main_lzd_hexoatl", owner_if_player = "wh2_dlc13_emp_the_huntmarshals_expedition", region = "", manual = true },
                { coordinates = {77, 317}, initial_owner = "wh2_dlc13_emp_the_huntmarshals_expedition", owner_if_player = "wh2_main_def_blood_hall_coven", region = "", manual = true },
                { coordinates = {248, 300}, initial_owner = "wh2_dlc11_cst_vampire_coast", owner_if_player = "wh_main_brt_bordeleaux", region = "", manual = true },
                { coordinates = {220, 230}, initial_owner = "wh2_main_lzd_itza", owner_if_player = "wh2_dlc11_cst_vampire_coast", region = "", manual = true },
                { coordinates = {205, 155}, initial_owner = "wh2_main_skv_clan_pestilens", owner_if_player = "wh2_dlc12_lzd_cult_of_sotek", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {87, 480}, initial_owner = "wh2_main_emp_new_world_colonies", owner_if_player = "wh2_main_emp_new_world_colonies", manual = true },
                { coordinates = {184, 243}, culture = "lzd", initial_owner = "wh2_main_lzd_itza", owner_if_player = "wh2_main_lzd_itza", manual = true },
                { coordinates = {245, 150}, initial_owner = "wh2_main_lzd_southern_sentinels", owner_if_player = "wh2_main_lzd_southern_sentinels", manual = true },
                { coordinates = {126, 341}, initial_owner = "wh2_main_lzd_tlaxtlan", owner_if_player = "wh2_main_lzd_tlaxtlan", manual = true },
            },

            ["resources"] = {}
         },
         ["cathay"] = {
            ["smithies"] = {
                {
                    coordinates = {1214, 644},
                    manual = true,
                    initial_owner = "wh3_main_cth_the_northern_provinces",
                    owner_if_player = "wh3_dlc20_chs_vilitch",
                    region = ""
                },
                {
                    coordinates = {1337, 608},
                    manual = true,
                    initial_owner = "wh2_dlc11_def_the_blessed_dread",
                    owner_if_player = "wh3_main_cth_celestial_loyalists",
                    region = ""
                },
                {
                    coordinates = {1310, 364},
                    manual = true,
                    initial_owner = "wh2_dlc13_lzd_spirits_of_the_jungle",
                    owner_if_player = "wh3_dlc21_wef_spirits_of_shanlin",
                    region = ""
                }
            },

            ["taverns"] = {
                { coordinates = {1113, 485}, initial_owner = "wh3_main_cth_dissenter_lords_of_jinshen", owner_if_player = "wh3_main_cth_dissenter_lords_of_jinshen", manual = true },
                { coordinates = {1143, 618}, culture = "cth", initial_owner = "wh3_main_cth_rebel_lords_of_nan_yang", owner_if_player = "wh3_main_cth_rebel_lords_of_nan_yang", manual = true },
                { coordinates = {1338, 576}, initial_owner = "wh3_dlc21_cst_dead_flag_fleet", owner_if_player = "wh3_dlc21_cst_dead_flag_fleet", manual = true },
                { coordinates = {1234, 393}, initial_owner = "wh3_main_cth_burning_wind_nomads", owner_if_player = "wh3_main_cth_burning_wind_nomads", manual = true },
            },

            ["resources"] = {}
         },
         ["mountainsofmourn"] = {
            ["smithies"] = {
                { coordinates = {1093, 565}, initial_owner = "wh3_main_cth_the_northern_provinces", owner_if_player = "wh3_main_cth_dissenter_lords_of_jinshen", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {1016, 603}, initial_owner = "wh3_main_ogr_blood_guzzlers", owner_if_player = "wh3_main_ogr_blood_guzzlers", manual = true },
                { coordinates = {1014, 501}, initial_owner = "wh3_main_ogr_goldtooth", owner_if_player = "wh3_main_ogr_goldtooth", manual = true },
            },

            ["resources"] = {}
         },
         ["darklands"] = {
            ["smithies"] = {
                { coordinates = {899, 649}, initial_owner = "wh3_main_vmp_lahmian_sisterhood", owner_if_player = "wh3_main_vmp_lahmian_sisterhood", region = "", manual = true },
                { coordinates = {935, 558}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_grn_dark_land_orcs", region = "", manual = true },
                { coordinates = {1012, 461}, initial_owner = "wh3_main_ogr_goldtooth", owner_if_player = "wh3_main_ogr_lazarghs", region = "" },
                { coordinates = {875, 435}, initial_owner = "wh2_dlc15_hef_imrik", owner_if_player = "wh3_main_ogr_thunderguts", region = "", manual = true },
                { coordinates = {1113, 450}, initial_owner = "wh3_main_vmp_caravan_of_blue_roses", owner_if_player = "wh3_main_cth_the_western_provinces", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {931, 477}, initial_owner = "wh3_dlc23_chd_legion_of_azgorh", owner_if_player = "wh3_dlc23_chd_legion_of_azgorh", manual = true },
                { coordinates = {866, 612}, initial_owner = "wh3_main_grn_drippin_fangs", owner_if_player = "wh3_main_grn_drippin_fangs", manual = true },
            },

            ["resources"] = {}

         },
         ["worldsedgemountains"] = {
            ["smithies"] = {
                { coordinates = {844, 555}, initial_owner = "wh3_dlc23_chd_legion_of_azgorh", owner_if_player = "wh_main_dwf_karak_azul", region = "", manual = true },
                { coordinates = {836, 443}, initial_owner = "wh2_dlc15_hef_imrik", owner_if_player = "wh_main_dwf_karak_azul", region = "", manual = true },
                { coordinates = {723, 459}, initial_owner = "wh_main_grn_crooked_moon", owner_if_player = "wh_main_grn_scabby_eye", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {793, 440}, culture = "dwf", initial_owner = "wh_main_dwf_karak_azul", owner_if_player = "wh_main_dwf_karak_azul", manual = true },
            },

            ["resources"] = {}
         },
         ["empire"] = {
            ["smithies"] = {
                { coordinates = {545, 768}, initial_owner = "wh_dlc03_bst_beastmen", owner_if_player = "wh_main_emp_nordland", region = "", manual = true },
                { coordinates = {589, 718}, initial_owner = "wh3_dlc20_chs_festus", owner_if_player = "wh_main_emp_empire", region = "", manual = true },
                { coordinates = {657, 622}, initial_owner = "wh_main_vmp_schwartzhafen", owner_if_player = "wh_main_emp_stirland", region = "", manual = true },
                { coordinates = {709, 661}, initial_owner = "wh_main_vmp_schwartzhafen", owner_if_player = "wh_main_emp_ostland", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {558, 592}, culture = "emp", initial_owner = "wh_main_emp_wissenland", owner_if_player = "wh_main_emp_wissenland", manual = true },
                { coordinates = {615, 657}, initial_owner = "wh_main_emp_talabecland", owner_if_player = "wh_main_emp_talabecland", manual = true },
                { coordinates = {536, 661}, initial_owner = "wh_main_emp_empire", owner_if_player = "wh_main_emp_empire", manual = true },
            },

            ["resources"] = {}

         },
         ["kislev"] = {
            ["smithies"] = {
                { coordinates = {723, 697}, initial_owner = "wh3_main_ksl_the_ice_court", owner_if_player = "wh_dlc08_nor_goromadny_tribe", region = "", manual = true },
                { coordinates = {612, 798}, initial_owner = "wh3_main_ksl_the_great_orthodoxy", owner_if_player = "wh3_main_ksl_the_great_orthodoxy", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {643, 783}, initial_owner = "wh3_main_ksl_ungol_kindred", owner_if_player = "wh3_main_ksl_ungol_kindred", manual = true },
                { coordinates = {707, 750}, culture = "ksl", initial_owner = "wh3_main_ksl_the_ice_court", owner_if_player = "wh3_main_ksl_the_ice_court", manual = true },
            },

            ["resources"] = {}

         },
         ["norsca"] = {
            ["smithies"] = {
                { coordinates = {677, 817}, initial_owner = "wh2_main_skv_clan_moulder", owner_if_player = "wh_main_dwf_kraka_drak", region = "", manual = true },
                { coordinates = {812, 776}, initial_owner = "wh3_main_ksl_the_ice_court", owner_if_player = "wh_dlc08_nor_goromadny_tribe", region = "", manual = true },
                { coordinates = {433, 855}, initial_owner = "wh_dlc08_nor_norsca", owner_if_player = "wh_main_nor_varg", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {495, 820}, culture = "nor", initial_owner = "wh_main_nor_skaeling", owner_if_player = "wh_main_nor_skaeling", manual = true },
            },

            ["resources"] = {}

         },
         ["borderprinces"] = {
            ["smithies"] = {
                { coordinates = {427, 441}, initial_owner = "wh2_main_skv_clan_skryre", owner_if_player = "wh_main_teb_estalia", region = "", manual = true },
                { coordinates = {664, 537}, initial_owner = "wh_main_teb_border_princes", owner_if_player = "wh_main_teb_border_princes", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {653, 518}, initial_owner = "wh_main_dwf_barak_varr", owner_if_player = "wh_main_dwf_barak_varr", manual = true },
                { coordinates = {507, 445}, culture = "emp", initial_owner = "wh_main_teb_tilea", owner_if_player = "wh_main_teb_tilea", manual = true },
            },

            ["resources"] = {}
         },
         ["greymountains"] = {
            ["smithies"] = {},

            ["taverns"] = {
                { coordinates = {608, 537}, culture = "dwf", initial_owner = "wh_main_dwf_karak_hirn", owner_if_player = "wh_main_dwf_karak_hirn", manual = true },
            },

            ["resources"] = {}
         },
         ["bretonnia"] = {
            ["smithies"] = {
                { coordinates = {484, 502}, initial_owner = "wh_dlc05_wef_wood_elves", owner_if_player = "wh_main_brt_carcassonne", region = "", manual = true },
                { coordinates = {459, 599}, initial_owner = "wh2_dlc15_grn_broken_axe", owner_if_player = "wh2_dlc11_vmp_the_barrow_legion", region = "" },
                { coordinates = {426, 674}, initial_owner = "wh_main_brt_bretonnia", owner_if_player = "wh_main_emp_marienburg", region = "" }
            },

            ["taverns"] = {
                { coordinates = {425, 612}, culture = "brt", initial_owner = "wh_main_brt_bastonne", owner_if_player = "wh_main_brt_bastonne", manual = true },
                { coordinates = {444, 488}, initial_owner = "wh_main_brt_carcassonne", owner_if_player = "wh_main_brt_carcassonne", manual = true },
            },

            ["resources"] = {}
         },
         ["ulthuan"] = {
            ["smithies"] = {
                { coordinates = {214, 635}, initial_owner = "wh3_main_sla_seducers_of_slaanesh", owner_if_player = "wh2_main_def_scourge_of_khaine", region = "", manual = true },
                { coordinates = {331, 595}, initial_owner = "wh3_main_sla_seducers_of_slaanesh", owner_if_player = "wh2_main_hef_yvresse", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {276, 591}, initial_owner = "wh2_main_hef_saphery", owner_if_player = "wh2_main_hef_saphery", manual = true },
                { coordinates = {264, 512}, culture = "hef", initial_owner = "wh2_main_hef_eataine", owner_if_player = "wh2_main_hef_eataine", manual = true },
                { coordinates = {279, 644}, initial_owner = "wh3_main_sla_seducers_of_slaanesh", owner_if_player = "wh3_main_sla_seducers_of_slaanesh", manual = true },
            },

            ["resources"] = {}
         },
         ["naggarond"] = {
            ["smithies"] = {
                { coordinates = {98, 877}, initial_owner = "wh2_main_def_naggarond", owner_if_player = "wh3_dlc20_chs_valkia", region = "", manual = true },
                { coordinates = {293, 859}, initial_owner = "wh2_main_def_har_ganeth", owner_if_player = "wh3_main_grn_da_cage_breakaz", region = "", manual = true },
                { coordinates = {212, 743}, initial_owner = "wh2_dlc11_cst_the_drowned", owner_if_player = "wh2_main_hef_nagarythe", region = "", manual = true },
                { coordinates = {72, 526}, initial_owner = "wh2_main_def_cult_of_pleasure", owner_if_player = "wh2_main_def_ssildra_tor", region = "", manual = true }
            },

            ["taverns"] = {
                { coordinates = {265, 803}, culture = "def", initial_owner = "wh2_main_def_karond_kar", owner_if_player = "wh2_main_def_karond_kar", manual = true },
                { coordinates = {195, 707}, initial_owner = "wh2_dlc11_cst_the_drowned", owner_if_player = "wh2_dlc11_cst_the_drowned", manual = true },
                { coordinates = {26, 626}, initial_owner = "wh2_dlc16_skv_clan_gritus", owner_if_player = "wh2_dlc16_skv_clan_gritus", manual = true },
                { coordinates = {127, 609}, initial_owner = "wh2_main_def_bleak_holds", owner_if_player = "wh2_main_def_bleak_holds", manual = true },
                { coordinates = {114, 795}, initial_owner = "wh2_main_def_naggarond", owner_if_player = "wh2_main_def_naggarond", manual = true },
            },

            ["resources"] = {}
         },
         ["northernchaoswastes"] = {
            ["smithies"] = {
                {
                    coordinates = {558, 939},
                    manual = true,
                    initial_owner = "wh2_main_def_hag_graef",
                    owner_if_player = "wh3_main_tze_broken_wheel",
                    region = ""
                },
                {
                    coordinates = {842, 878},
                    manual = true,
                    initial_owner = "wh3_main_ksl_ursun_revivalists",
                    owner_if_player = "wh_main_chs_chaos",
                    region = ""
                },
                {
                    coordinates = {847, 758},
                    manual = true,
                    initial_owner = "wh_main_grn_greenskins",
                    owner_if_player = "wh3_main_grn_slaves_of_zharr",
                    region = ""
                },
                {
                    coordinates = {1089, 710},
                    manual = true,
                    initial_owner = "wh3_dlc20_chs_kholek",
                    owner_if_player = "wh3_main_ogr_fleshgreeders",
                    region = ""
                },
                {
                    coordinates = {1216, 695},
                    manual = true,
                    initial_owner = "wh3_dlc20_chs_vilitch",
                    owner_if_player = "wh3_main_cth_imperial_wardens",
                    region = ""
                }
            },

            ["taverns"] = {
                { coordinates = {400, 899}, initial_owner = "wh3_main_sla_subtle_torture", owner_if_player = "wh3_main_sla_subtle_torture", manual = true },
                { coordinates = {703, 910}, initial_owner = "wh3_main_tze_all_seeing_eye", owner_if_player = "wh3_main_tze_all_seeing_eye", manual = true },
                { coordinates = {1020, 741}, initial_owner = "wh3_main_ogr_fleshgreeders", owner_if_player = "wh3_main_ogr_fleshgreeders", manual = true },
                { coordinates = {1171, 709}, initial_owner = "wh3_main_chs_khazag", owner_if_player = "wh3_main_chs_khazag", manual = true },
            },

            ["resources"] = {}
         }
    },
}

--- //////////////////////////////////////////////////////////////////////////////////////////////////
--- //////////////////////////////////////////////////////////////////////////////////////////////////
--- realm_of_chaos

--[[
Coordinates for the default campaign of WH3.
Used the 2 coordinates system of a physical image map and the logical map through the script_debug_activator mod whenever one clicks on a character (coordinates log is the logical coordinates on the map).

Things to understand:
- ORDERED BY KNOWN ZONE
[ZONE]
- PROVINCE

Special buildings are maximum 2 per zone only. As such they are specially separated and assigned here once the mod configuration tool is in the workshop, make all this configurable.
--]]
--- Auto generated by algorithm in Jun 29, 2022.
--- Map: Realm Of Chaos
M.realm_of_chaos = {
    treasures_and_spots = {
         ["kislev"] = {
              --- Troll Country
              {284, 231},
              {328, 210},
              {243, 169},
              {243, 220},
              --- Northern Oblast
              {365, 134},
              {319, 169},
              {280, 180},
              --- River Lynsk: Erengrad
              {238, 145, disabled = true},
              {282, 137},
              --- Black Blood Pass
              {367, 218},
              --- The Cursed City: Praag
              {435, 196},
              --- River Urskoy: Kislev
              {439, 135, disabled = true},
              --- Eastern Oblast
              {518, 135},
              {463, 175},
              --- Dukhlys Forest
              {489, 198},
              {514, 178},
              {557, 221},
              --- The Cursed City: Praag
              {407, 164, manual = true},
              --- Black Blood Pass
              {372, 187, manual = true},
              --- Eastern Oblast
              {472, 180, manual = true},
              --- Dukhlys Forest
              {509, 214, manual = true},
         },
         ["darklands"] = {
              --- Zorn Uzkul
              {682, 200},
              {766, 233},
              {734, 168},
              --- The Plain of Zharr
              {720, 144},
              {806, 165},
              {817, 210},
              --- The Blasted Wastes
              {762, 110},
              {776, 83},
              {792, 117},
              {858, 135},
              --- The Wolf Lands
              {848, 75},
              {823, 32},
              {881, 36},
              --- The Howling Wastes
              {873, 161, disabled = true},
              {866, 218},
              {933, 166},
              {941, 188},
              --- The Haunted Forest
              {956, 115},
              {1024, 162},
              --- Zorn Uzkul
              {744, 201, manual = true},
              --- The Blasted Wastes
              {753, 66, manual = true},
              {770, 32, manual = true},
              --- The Haunted Forest
              {932, 69, manual = true},
              --- The Howling Wastes
              {918, 130, manual = true},
              {902, 196, manual = true},
         },
         ["worldsedgemountains"] = {
              --- The High Pass
              {692, 224, disabled = true},
              {603, 228},
              --- Worlds Edge Mountains
              {590, 133},
              --- Peak Pass
              {641, 107},
              {595, 78},
              --- Black Water
              {654, 155, manual = true},
         },
         ["empire"] = {
              --- The Witch's Wood
              {98, 182},
              --- Wasteland
              {86, 126, disabled = true},
              {60, 140},
              {69, 97},
              {93, 77},
              --- Northern Grey Mountains
              --- Southern Grey Mountains
              {79, 33},
              --- Middenland
              {137, 121},
              {161, 97},
              {181, 111},
              --- Nordland
              {157, 182},
              {167, 150},
              {214, 131},
              --- Hochland
              {214, 56},
              {257, 45},
              {287, 63},
              --- Reikland
              {132, 53},
              {161, 41},
              {227, 32},
              --- Wissenland
              {350, 38},
              {355, 20},
              --- Talabecland
              {346, 55},
              --- Ostland
              {327, 137},
              {309, 113, disabled = true},
              {360, 107},
              {337, 88},
              --- Ostermark
              {437, 108},
              {429, 83},
              {472, 77},
              {513, 104},
              --- Stirland
              {381, 37},
              {426, 19},
              {434, 55},
              --- Sylvania
              {457, 18},
              {499, 23},
              {517, 61},
              --- Ostland
              {383, 97, manual = true},
              --- Ostermark
              {429, 89, manual = true},
              {483, 113, manual = true},
              --- The Witch's Wood
              {123, 219, manual = true},
              {66, 177, manual = true},
              {46, 209, manual = true},
              --- Hochland
              {289, 23, manual = true},
         },
         ["norsca"] = {
              --- Vanaheim Mountains
              {67, 457},
              {45, 432},
              {87, 378},
              --- Helspire Mountains
              {164, 381},
              {203, 332},
              {265, 336},
              --- Ice Tooth Mountains
              {129, 338},
              {136, 300},
              {163, 332},
              --- Trollheim Mountains
              {214, 276},
              {260, 252},
              --- Gianthome Mountains
              {292, 305},
              {328, 287},
              {388, 272},
              {474, 280},
              {520, 263},
              --- The Goromadny
              {582, 260},
              {618, 273},
         },
         ["mountainsofmourn"] = {
              --- Path to the East
              {733, 317},
              {768, 366},
              --- Gash Kadrak
              {800, 304},
              {820, 338},
              --- Mountains of Mourn
              {879, 338, disabled = true},
              --- Mist Gorge
              {945, 326},
              --- Wyrm Pass
              {1010, 330},
              {988, 281},
              --- Bone Road
              {863, 465, disabled = true},
              --- Ivory Road
              --- Ice Pass
              --- Ancient Giant Lands
         },
         ["cathay"] = {
              --- Imperial Road
              {1004, 664},
              {959, 656},
              {1058, 642},
              {1028, 631},
              --- Land of Stone and Steel
              {942, 632},
              {914, 560},
              {948, 579},
              {912, 584},
              --- Forests of the Moon
              {1042, 575},
              {1035, 603},
              --- Gunpowder Road
              {909, 516},
              {920, 491},
              {950, 521},
              --- Warpstone Desert
              {930, 461},
              {955, 454},
              {985, 484},
              --- Celestial Riverlands
              {1084, 579},
              {1094, 469},
              --- Wasteland of Jinshen
              {1040, 456},
              {981, 449},
              {1040, 456},
              --- Broken Lands of Tian Li
              {1059, 417},
              --- Warpstone Desert
              {930, 400, manual = true},
              --- Broken Lands of Tian Li
              {1021, 395, manual = true},
              --- Wasteland of Jinshen
              {1042, 512, manual = true},
              --- Land of Stone and Steel
              {934, 615, manual = true},
              {974, 612, manual = true},
         },
         ["chaoswastes"] = {
              --- The Shard Lands
              {105, 577},
              {139, 566},
              {247, 582},
              {244, 533},
              --- Northern Wastes
              {107, 520},
              {137, 477},
              {188, 435},
              {198, 487},
              {216, 515},
              --- The Eternal Lagoon
              {298, 544},
              {338, 524},
              {329, 471},
              --- Bloodfire Falls
              {274, 442},
              {303, 440, disabled = true},
              {338, 442},
              {273, 398},
              --- The Cold Mires
              {291, 372},
              {298, 412},
              --- Plain of Bone
              {409, 474},
              {446, 457},
              {491, 460},
              --- Plain of Illusions
              {442, 401},
              {392, 376},
              {389, 337},
              {436, 357},
              {486, 360},
              {524, 351},
              --- The Blood Marshes
              {487, 410},
              {553, 445},
              {565, 417},
              {552, 382},
              --- K'datha
              {619, 449},
              {605, 417},
              {642, 472},
              {680, 478},
              {741, 470},
              --- The Cliffs of Death
              {607, 320},
              {633, 313},
              --- Road of Skulls
              {677, 316},
              {678, 339},
              {716, 360},
              {679, 391},
              {723, 398},
              {733, 431},
              --- Road to Damnation
              {814, 420},
              {801, 462},
              {788, 490},
              {741, 470},
              --- Eastern Steppes
              {851, 517},
              {850, 572},
              --- The Red Wastes
              {888, 589, disabled = true},
              {862, 612},
              {895, 618},
              {894, 646},
              --- Road to Damnation
              {806, 499, manual = true},
              --- Road of Skulls
              {672, 422, manual = true},
              --- The Eternal Lagoon
              {364, 481, manual = true},
              --- The Shard Lands
              {171, 595, manual = true},
         },
    },
    points_of_interest = {
        ["kislev"] = {
            ["smithies"] = {
                { coordinates = {524, 216}, initial_owner = "wh_main_nor_baersonling", owner_if_player = "wh_main_nor_baersonling", region = "" },
                { coordinates = {229, 203}, initial_owner = "wh3_main_ksl_the_great_orthodoxy", owner_if_player = "wh3_main_ksl_the_great_orthodoxy", region = "wh3_main_chaos_region_castle_alexandronov" } --wh_main_nor_varg
            },

            ["taverns"] = {
                { coordinates = {238, 145}, manual = true },
                { coordinates = {439, 135}, culture = "ksl", manual = true },
            },

            ["resources"] = {}
        },

        ["darklands"] = {
            ["smithies"] = {
                { coordinates = {894, 100}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_grn_drippin_fangs", region = "" },
                { coordinates = {800, 232}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_grn_drippin_fangs", region = "" },
                { coordinates = {832, 148}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_lzd_tepoks_spawn", region = "" }
            },

            ["taverns"] = {
                { coordinates = {740, 135}, manual = true },
                { coordinates = {873, 161}, manual = true },
            },

            ["resources"] = {}
        },

        ["worldsedgemountains"] = {
            ["smithies"] = {
                { coordinates = {663, 178}, initial_owner = "wh2_dlc16_vmp_lahmian_sisterhood", owner_if_player = "wh2_dlc16_vmp_lahmian_sisterhood", region = "" },
            },

            ["taverns"] = {
                { coordinates = {692, 224}, manual = true },
            },

            ["resources"] = {}
        },

        ["empire"] = {
            ["smithies"] = {
                { coordinates = {189, 41}, initial_owner = "wh_main_emp_empire", owner_if_player = "wh_main_emp_middenland", region = "" },
                { coordinates = {485, 54}, initial_owner = "wh_main_vmp_waldenhof", owner_if_player = "wh_main_vmp_waldenhof", region = "" }
            },

            ["taverns"] = {
                { coordinates = {86, 126}, manual = true },
                { coordinates = {309, 113}, culture = "emp", manual = true },
            },

            ["resources"] = {}
        },

        ["norsca"] = {
            ["smithies"] = {
                { coordinates = {168, 275}, initial_owner = "wh2_dlc13_wef_laurelorn_forest", owner_if_player = "wh2_dlc13_wef_laurelorn_forest", region = "" }
            },

            ["taverns"] = {
                { coordinates = {425, 284}, manual = true },
            },

            ["resources"] = {}
        },

        ["mountainsofmourn"] = {
            ["smithies"] = {
                { coordinates = {873, 235}, initial_owner = "wh3_main_dwf_karak_azorn", owner_if_player = "wh3_main_dwf_karak_azorn", region = "" }
            },

            ["taverns"] = {
                { coordinates = {879, 338}, culture = "ogr", manual = true },
                { coordinates = {863, 465}, manual = true },
            },

            ["resources"] = {}
        },

        ["cathay"] = {
            ["smithies"] = {
                { coordinates = {918, 479}, initial_owner = "wh3_main_cth_dissenter_lords_of_jinshen", owner_if_player = "wh3_main_cth_dissenter_lords_of_jinshen", region = "" },
                { coordinates = {913, 621}, initial_owner = "wh3_main_chs_dreaded_wo", owner_if_player = "wh3_main_chs_dreaded_wo", region = "" }
            },

            ["taverns"] = {
                { coordinates = {1016, 486}, manual = true },
                { coordinates = {1018, 595}, manual = true },
            },

            ["resources"] = {}
        },

        ["chaoswastes"] = {
            ["smithies"] = {
                { coordinates = {234, 423}, initial_owner = "wh3_main_sla_exquisite_pain", owner_if_player = "wh3_main_sla_exquisite_pain", region = "" },
                { coordinates = {420, 407}, initial_owner = "wh3_main_nur_maggoth_kin", owner_if_player = "wh3_main_nur_maggoth_kin", region = "" },
                { coordinates = {614, 304}, initial_owner = "wh3_main_chs_tong", owner_if_player = "wh3_main_chs_tong", region = "" },
                { coordinates = {781, 431}, initial_owner = "wh3_main_ogr_mountaineaters", owner_if_player = "wh3_main_ogr_mountaineaters", region = "" }
            },

            ["taverns"] = {
                { coordinates = {303, 440}, manual = true },
                { coordinates = {209, 573}, manual = true },
                { coordinates = {447, 377}, manual = true },
                { coordinates = {653, 458}, manual = true },
                { coordinates = {888, 589}, culture = "chs", manual = true },
                { coordinates = {608, 356}, manual = true },
            },

            ["resources"] = {}
        }
    },
}

--- //////////////////////////////////////////////////////////////////////////////////////////////////
--- //////////////////////////////////////////////////////////////////////////////////////////////////
--- immortal_empires_expanded

--- Manually acquired on 2025-02-03.
M.immortal_empires_expanded = {
    treasures_and_spots = {
        --- These IEEE-specific coordinates will not ever be used with the original system.
        --- In addition, these are intended to be concatenated with the vanilla IE coordinates since they share the same map with the new map additions by IEEE.
        ["placeholder"] = {
            --- The Spice Route
            {1110, 383},
            --- Land of a Thousand Gods
            {1114, 335},
            {1160, 334},
            --- Shambani Foothills
            {1204, 309},
            {1148, 307},
            --- Central Ind
            {1164, 259},
            --- Ind's End
            {1135, 251},
            {1102, 248},
            {1076, 217},
            {1050, 222},
            {1047, 154},
            --- Eastern Colonies
            {1015, 137},
            {1031, 121},
            --- Forest of Broken Fangs
            {1312, 303},
            {1230, 278},
            --- Whispering Jungle
            {1379, 295},
            --- Cochincathay
            {1371, 247},
            {1364, 222},
            {1402, 179},
            --- Bloodied Coast
            {1226, 236},
            {1213, 205},
            {1263, 209},
            --- Kureshi Hills
            {1311, 131},
            {1290, 110},
            {1250, 119},
            {1264, 82},
            {1307, 79},
            {1310, 114},
            --- Hokusei Arc
            {1452, 388},
            {1455, 349},
            --- Hokurikudo
            {1505, 342},
            --- Samurai's Domain
            {1445, 301},
            --- Sun's Origin
            {1455, 273},
            {1441, 259},
            {1506, 216},
            --- Eastern Circuit
            {1497, 278},
            {1522, 269},
            {1513, 252},
            {1521, 202},
            --- North Isle
            {1462, 129},
            --- Lost Isles of Elithis
            {1481, 71},
            {1452, 21},
            --- Green Steppes
            {1157, 793},
            {1204, 769},
            {1233, 753},
            --- Deep Steppes
            {1165, 817},
            {1185, 836},
            {1234, 779},
            {1225, 817},
            {1253, 823},
            --- East Kurgania
            {1286, 793},
            {1259, 754},
            {1294, 744},
            {1315, 762},
            {1341, 734},
            --- Grave of Scythia
            {1388, 743},
            {1378, 778},
            {1401, 742},
            {1437, 764},
            --- The Black Wastes
            {1441, 723},
            {1458, 746},
            --- West Hunguria
            {1469, 782},
            {1493, 747},
            {1530, 762},
            {1539, 814},
            --- North Ilhan
            {1409, 694},
            {1468, 656},
            {1388, 609},
            --- East Ilhan
            {1468, 656},
            {1438, 569},
            --- South Ilhan
            {1417, 588},
            {1385, 566},
        },
    },
    points_of_interest = {
        ["placeholder"] = {
            ["smithies"] = {},
            ["taverns"] = {},
            ["resources"] = {}
         },
    },
}

return M
