-- Coordinates for all three supported campaigns.
-- Keyed by campaign id ("inmortal_empires", "realm_of_chaos", "immortal_empires_expanded").

local M = {}

-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- inmortal_empires

-- Auto generated by algorithm in Apr 30, 2023.
-- Map: im_coordinates.
M.inmortal_empires = {
    treasures_and_spots = {
         ["southernchaoswastes"] = {
              -- The Daemonium Hills
              {808, 44},
              {785, 32},
              {731, 33},
              -- The Abyssal Glacier
              {693, 32},
              {642, 22},
              {609, 24},
              -- The Southern Wastes
              {535, 27},
              {490, 33},
              {473, 71},
              {457, 36},
              {436, 53},
              {385, 51},
              -- The Ice Fire Plains
              {315, 30},
              {299, 23},
              {271, 35},
              {230, 32},
         },
         ["southlands"] = {
              -- Dawn's Landing
              {581, 83},
              {603, 72},
              {627, 85},
              -- The Jungle of the Gods
              {693, 103},
              {701, 131},
              {707, 168},
              -- Southern Jungles
              {591, 103},
              {637, 120},
              {634, 142},
              -- Kingdom of Beasts
              {768, 229},
              {801, 229},
              -- The Golden Pass
              {704, 195},
              {732, 167},
              {751, 193},
              -- Heart of the Jungle
              {655, 210},
              -- Central Jungles
              {610, 160},
              {647, 177},
              {614, 200},
              {644, 194},
              -- Western Jungles
              {524, 218},
              {530, 196},
              {575, 165},
         },
         ["nehekara"] = {
              -- Shifting Sands
              {589, 255},
              {621, 250},
              {661, 258},
              {610, 235},
              {648, 231},
              {668, 227},
              -- Land of the Dervishes
              {572, 233},
              {560, 266},
              -- Great Desert of Araby
              {503, 250},
              {463, 277},
              {505, 280},
              -- Land of Assasins
              {440, 259},
              {440, 304},
              {457, 322},
              -- Crater of the Waking Dead
              {784, 286},
              {806, 268},
              {820, 318},
              {815, 331},
              -- Devil's Backbone
              {693, 314},
              {765, 309},
              -- Land of the Dead
              {630, 288},
              {676, 294},
              {615, 311},
              {646, 310},
              -- Great Mortis Delta
              {595, 277},
              -- The Cracked Land
              {528, 273},
              {563, 295},
              {516, 309},
              {556, 313},
              -- Coast of Araby
              {491, 330},
         },
         ["badlands"] = {
              -- The Barrier Idols
              {662, 319},
              {685, 327},
              {721, 325},
              {640, 345},
              {672, 348},
              {720, 365},
              -- Blightwater
              {764, 380},
              {731, 393},
              {761, 397},
              -- Marshes of Madness
              {668, 358},
              {701, 383},
              {644, 389},
              {657, 404},
              {697, 405},
              -- Southern Badlands
              {585, 352},
              {565, 355},
              {591, 373},
              {625, 386},
              {607, 392},
              {601, 412},
              -- Eastern Badlands
              {712, 438},
              {765, 428},
              -- Western Badlands
              {685, 422},
              {647, 435},
              {669, 452},
              {701, 460},
              {649, 471},
              -- Death Pass
              {741, 465},
              {765, 474},
              {711, 481},
              {784, 489},
              -- Blood River Valley
              {650, 496},
              {684, 493},
              {715, 516},
         },
         ["lustria"] = {
              -- The Capes
              {292, 98},
              -- Culchan Plains
              {262, 131},
              {219, 145},
              {241, 138},
              {238, 169},
              -- The Night Forest Road
              {267, 102},
              {234, 105},
              {209, 117},
              {183, 127},
              {167, 144},
              -- Headhunter's Jungle
              {222, 181},
              {218, 215},
              {242, 221},
              -- The Lost Valley
              {204, 172},
              {176, 184},
              {194, 196},
              {165, 198},
              -- Spine of Sotek
              {169, 169},
              {142, 190},
              {111, 204},
              -- Copper Desert
              {135, 155},
              {118, 183},
              -- Vampire Coast
              {285, 278},
              {242, 290},
              -- Mosquito Swamps
              {214, 229},
              {200, 238},
              {250, 256},
              {215, 281},
              -- River Qurveza
              {153, 216},
              {198, 223},
              {168, 226},
              {131, 225},
              {151, 246},
              {184, 243},
              -- The Turtle Isles
              {89, 228},
              {73, 237},
              {86, 260},
              {58, 269},
              {54, 300},
              -- Piranha Swamps
              {220, 296},
              {163, 330},
              {202, 337},
              -- The Gwangee Valley
              {183, 268},
              {164, 293},
              {126, 310},
              {147, 313},
              {117, 335},
              {145, 336},
              -- Jungle of Green Mist
              {50, 329},
              {70, 366},
              -- The Creeping Jungle
              {117, 352},
              {167, 361},
              {93, 364},
              {136, 369},
              -- Aymara Swamps
              {110, 399},
              -- Jungle of Pahualaxa
              {107, 418},
              {47, 438},
              {127, 441},
              {81, 456},
              {130, 456},
              -- The Isthmus Coast
              {87, 480},
              {106, 504},
              {100, 529},
              -- Isthmus of Lustria
              {57, 452},
              {49, 471},
              {51, 495},
              {82, 494},
         },
         ["cathay"] = {
              -- Broken Lands of Tian Li
              {1245, 404},
              {1202, 396},
              {1216, 414},
              {1171, 431},
              {1144, 455},
              {1210, 464},
              -- The Great Canal
              {1290, 367},
              {1242, 376},
              {1259, 393},
              {1272, 415},
              {1270, 435},
              -- Serpent Stuary
              {1365, 361},
              {1352, 404},
              -- Mount Li
              {1379, 420},
              {1306, 443},
              {1370, 453},
              -- Nongchang Basin
              {1264, 473},
              {1299, 455},
              {1309, 494},
              {1258, 506},
              -- Celestial Riverlands
              {1233, 477},
              {1175, 485},
              {1219, 484},
              {1154, 494},
              {1207, 521},
              -- Wastelands of Jinshen
              {1140, 467},
              {1113, 485},
              {1135, 500},
              {1154, 517},
              -- Jade River Delta
              {1350, 496},
              {1354, 526},
              {1307, 518},
              {1345, 555},
              -- Forest of the Moon
              {1244, 543},
              {1297, 546},
              {1318, 556},
              {1252, 567},
              {1234, 592},
              -- Warpstone Desert
              {1160, 551},
              {1201, 559},
              {1128, 576},
              {1152, 584},
              {1124, 607},
              -- Plains of Xen
              {1361, 580},
              {1335, 585},
              {1331, 622},
              -- Imperial Road
              {1291, 605},
              {1268, 601},
              {1223, 607},
              {1291, 626},
              -- Lands of Stone and Steel
              {1168, 603},
              {1210, 626},
              {1177, 635},
              {1252, 639},
              {1196, 647},
              -- Gunpowder Road
              {1143, 618},
              {1137, 638},
              {1161, 644},
         },
         ["mountainsofmourn"] = {
              -- Wyrm Pass
              {1057, 450},
              {1087, 502},
              {1065, 531},
              -- Ivory Road
              {1009, 483},
              {1040, 487},
              {1013, 507},
              {1000, 532},
              -- Mountains of Mourn
              {1032, 546},
              {1093, 569},
              {1012, 577},
              -- Bone Road
              {972, 588},
              {1062, 589},
              {1029, 601},
              {984, 607},
              {1049, 613},
              -- Ancient Giant Lands
              {966, 637},
              {996, 646},
              {1038, 641},
              {980, 656},
              {1012, 662},
              -- Gash Kadrak
              {1056, 664},
              {976, 682},
              {1000, 674},
              {1043, 694},
              -- Path to the East
              {997, 705},
              {909, 692},
         },
         ["darklands"] = {
              -- The Dragon Isles
              {979, 365},
              {1009, 379},
              {984, 390},
              {1011, 425},
              -- Gnoblar Country
              {1011, 425},
              {992, 444},
              {1033, 442},
              {1091, 442},
              -- Mouth of Ruin
              {941, 443},
              {903, 419},
              -- The Plain of Bones
              {856, 436},
              {906, 456},
              {852, 461},
              -- The Howling Wastes
              {955, 463},
              {964, 490},
              {959, 525},
              -- The Desolation of Azgorh
              {849, 483},
              {893, 489},
              {866, 509},
              {901, 507},
              -- The Wolf Lands
              {841, 536},
              {878, 540},
              {933, 535},
              -- The Plain of Zharr
              {948, 560},
              {948, 599},
              {936, 629},
              -- The Blasted Wastes
              {893, 586},
              {871, 608},
              {850, 625},
              {880, 645},
              {847, 650},
              -- Zorn Uzkul
              {919, 647},
              {851, 680},
              {894, 691},
              {854, 706},
         },
         ["worldsedgemountains"] = {
              -- Southlands Worlds Edge Mountains
              {697, 235},
              {709, 258},
              {739, 296},
              -- Broken Teeth
              {830, 395},
              {872, 396},
              -- Eight Peaks
              {719, 450},
              {783, 461},
              -- Southern World's Edge Mountains
              {793, 440},
              {816, 443},
              {796, 459},
              -- The Silver Road
              {793, 527},
              {730, 540},
              {774, 545},
              -- Deadrock Gap
              {804, 573},
              -- Black Water
              {731, 585},
              {711, 599},
              -- Rib Peaks
              {781, 604},
              {802, 613},
              -- Peak Pass
              {783, 639},
              {803, 649},
              -- Northern World's Edge Mountains
              {792, 696},
              {763, 687},
              {749, 665},
         },
         ["empire"] = {
              -- Southern Sylvania
              {668, 592},
              {691, 592},
              {711, 628},
              -- Northern Sylvania
              {686, 637},
              {730, 658},
              -- Mootland
              {653, 616},
              -- Solland
              {588, 557},
              {628, 568},
              -- Averland
              {663, 576},
              {585, 599},
              {633, 606},
              -- Stirland
              {574, 623},
              {631, 629},
              {663, 646},
              -- Wissenland
              {575, 578},
              {551, 595},
              {560, 615},
              -- Ostermark
              {679, 651},
              {683, 673},
              {701, 697},
              -- Talabecland
              {565, 645},
              {602, 646},
              {644, 662},
              {598, 675},
              {649, 678},
              {667, 721},
              -- Reikland
              {528, 609},
              {533, 626},
              {496, 636},
              -- Hochland
              {608, 708},
              -- Middenland
              {539, 677},
              {565, 704},
              {553, 720},
              -- Wasteland
              {439, 668},
              {476, 679},
              {486, 695},
              {463, 705},
              {473, 721},
              -- Ostland
              {656, 736},
              {610, 771},
              {654, 757},
              -- Nordland
              {562, 744},
              {518, 750},
              {561, 765},
              -- The Misty Hills
              {512, 724},
              {496, 737},
         },
         ["kislev"] = {
              -- Eastern Oblast
              {755, 768},
              {779, 775},
              {748, 789},
              -- The Cursed City
              {710, 764},
              {729, 783},
              -- River Urskoy
              {707, 750},
              -- Southern Oblast
              {727, 721},
              {693, 728},
              {677, 752},
              -- Rock Pass
              {711, 798},
              -- Troll Country
              {695, 764},
              {679, 779},
              {685, 799},
              -- River Lynsk
              {643, 783},
              -- Western Oblast
              {618, 806},
              {655, 812},
         },
         ["norsca"] = {
              -- Goromadny Mountains
              {842, 737},
              {769, 810},
              {741, 820},
              -- Gianthome Mountains
              {738, 842},
              {701, 859},
              -- Mountains of Hel
              {609, 855},
              {671, 848},
              {658, 869},
              {592, 879},
              -- Trollheim Mountains
              {586, 829},
              {572, 846},
              -- Mountains of Naglfari
              {508, 850},
              {495, 820},
              {547, 844},
              -- Helspire Mountains
              {410, 837},
              {524, 881},
              {570, 887},
              -- Ice Tooth Mountains
              {445, 764},
              {549, 795},
              -- Vanaheim Mountains
              {386, 790},
              {466, 812},
              -- Albion
              {364, 761},
         },
         ["borderprinces"] = {
              -- E. Border Princes
              {623, 502},
              {653, 518},
              {604, 519},
              {692, 534},
              -- W. Border Princes
              {533, 403},
              {553, 435},
              {586, 447},
              {563, 456},
              {581, 475},
              -- Tilea
              {516, 397},
              {527, 417},
              {507, 445},
              {507, 470},
              -- Estalia
              {428, 425},
              {392, 438},
              -- Irrana Mountains
              {391, 459},
              {410, 472},
              {429, 481},
         },
         ["greymountains"] = {
              -- Black Mountains
              {608, 537},
              {635, 544},
              -- The Vaults
              {524, 478},
              {578, 532},
              -- Southern Grey Mountains
              {516, 584},
         },
         ["bretonnia"] = {
              -- Forest of Chalons
              {450, 549},
              {486, 564},
              -- Carcassone
              {444, 488},
              {440, 517},
              {481, 530},
              {413, 547},
              -- Bastonne
              {455, 584},
              {425, 612},
              {448, 612},
              -- River Brienne
              {415, 584},
              {397, 600},
              -- Forest of Arden
              {421, 633},
              -- Coast of Lyonesse
              {375, 611},
              {364, 646},
              {392, 642},
              -- Marches of Couronne
              {403, 660},
              {423, 693},
         },
         ["ulthuan"] = {
              -- Southern Yvresse
              {301, 529},
              {325, 549},
              -- Eataine
              {264, 512},
              {304, 522},
              {264, 544},
              -- Caledor
              {221, 509},
              -- Northern Yvresse
              {345, 574},
              {324, 584},
              -- Saphery
              {292, 551},
              {294, 573},
              -- Averlorn
              {275, 591},
              {254, 605},
              -- Ellyrion
              {203, 567},
              {226, 592},
              -- Tiranoc
              {190, 536},
              {178, 562},
              {177, 585},
              -- Cothique
              {318, 614},
              -- Chrace
              {269, 635},
              {291, 633},
              -- Nagarythe
              {186, 617},
              {215, 624},
              {256, 648},
         },
         ["naggarond"] = {
              -- Deadwood
              {260, 832},
              {238, 846},
              {263, 858},
              -- The Road of Skulls
              {206, 836},
              {201, 860},
              {207, 883},
              -- Spiteful Peaks
              {167, 815},
              {181, 827},
              {152, 832},
              {137, 869},
              -- Iron Foothills
              {99, 834},
              {83, 860},
              -- The Black Flood
              {147, 767},
              {91, 767},
              {109, 791},
              {128, 797},
              -- Iron Mountains
              {58, 788},
              {72, 801},
              {81, 817},
              {58, 825},
              -- Iron Coast
              {21, 769},
              {20, 802},
              {17, 842},
              {34, 851},
              -- Doom Glades
              {102, 650},
              {130, 675},
              {100, 682},
              -- The Bleak Coast
              {114, 565},
              {124, 588},
              {109, 616},
              {95, 633},
              -- Titan Peaks
              {66, 551},
              {95, 548},
              {81, 563},
              -- Ashen Coast
              {33, 519},
              {28, 548},
              {15, 583},
              {18, 609},
              -- Ironsand Desert
              {33, 625},
              {49, 628},
              {85, 643},
              -- The Broken Lands
              {255, 766},
              {266, 782},
              {265, 803},
              -- Granite Hills
              {185, 758},
              {222, 763},
              {199, 776},
              {228, 785},
              -- The Clawed Coast
              {215, 703},
              {195, 707},
              {172, 734},
              {213, 735},
              -- Obsidian Peaks
              {135, 697},
              {46, 699},
              {74, 712},
              {159, 710},
              {92, 729},
              {153, 734},
              {72, 747},
              -- Red Desert
              {40, 648},
              {30, 666},
              {45, 697},
              {24, 710},
              {30, 740},
         },
         ["northernchaoswastes"] = {
              -- The Red Wastes
              {1349, 658},
              {1267, 668},
              {1305, 671},
              {1168, 678},
              {1237, 684},
              -- Eastern Steppes
              {1280, 701},
              {1232, 702},
              {1189, 707},
              -- Stonesky Foothills
              {1170, 697},
              {1088, 698},
              {1056, 715},
              {1131, 710},
              -- Chimera Plateau
              {1029, 728},
              {1021, 761},
              {1042, 787},
              {998, 785},
              -- K'datha
              {959, 810},
              {980, 830},
              {1014, 823},
              -- The Skull Road
              {852, 758},
              {883, 775},
              {839, 800},
              {868, 808},
              {798, 820},
              -- The Blood Marshes
              {938, 829},
              {872, 838},
              {925, 850},
              {827, 856},
              {904, 871},
              -- Bloodfire Falls
              {775, 857},
              {806, 868},
              {838, 893},
              {807, 902},
              -- Plain of Illusions
              {738, 898},
              {734, 920},
              {765, 923},
              {677, 943},
              {722, 937},
              -- The N. Tumour
              {695, 913},
              {630, 921},
              {605, 937},
              {645, 940},
              -- The Eternal Lagoon
              {514, 927},
              {591, 931},
              {521, 953},
              -- The Cold Mires
              {458, 903},
              {400, 899},
              {467, 925},
              {495, 951},
              -- Northern Wastes
              {423, 911},
              {406, 926},
              {364, 924},
              {452, 943},
              -- The Shard Lands
              {331, 856},
              {380, 882},
              {322, 883},
              {363, 897},
              {317, 907},
              -- The Frigid Wasteland
              {250, 896},
              {160, 896},
              {206, 901},
              {287, 903},
              -- Ironfrost Glacier
              {70, 892},
              {139, 891},
              {43, 892},
              {99, 896},
         },
    },
    points_of_interest = {
        ["southernchaoswastes"] = {
            ["smithies"] = {
                { coordinates = {332, 28}, initial_owner = "wh3_main_tze_oracles_of_tzeentch", owner_if_player = "wh3_main_nur_bubonic_swarm", region = "" },
                { coordinates = {553, 36}, initial_owner = "wh2_dlc17_lzd_oxyotl", owner_if_player = "wh3_main_tze_flaming_scribes", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["southlands"] = {
            ["smithies"] = {
                { coordinates = {647, 98}, initial_owner = "wh2_main_hef_order_of_loremasters", owner_if_player = "wh3_main_tze_oracles_of_tzeentch", region = "" },
                { coordinates = {553, 217}, initial_owner = "wh2_main_lzd_tlaqua", owner_if_player = "wh3_main_emp_cult_of_sigmar", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["nehekara"] = {
            ["smithies"] = {
                { coordinates = {634, 259}, initial_owner = "wh2_dlc09_tmb_khemri", owner_if_player = "wh_main_vmp_vampire_counts", region = "" },
                { coordinates = {469, 325}, initial_owner = "wh2_dlc09_tmb_followers_of_nagash", owner_if_player = "wh2_main_brt_thegans_crusaders", region = "" },
                { coordinates = {793, 265}, initial_owner = "wh2_dlc09_tmb_lybaras", owner_if_player = "wh2_main_vmp_the_silver_host", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["badlands"] = {
            ["smithies"] = {
                { coordinates = {602, 316}, initial_owner = "wh2_dlc09_tmb_khemri", owner_if_player = "wh3_main_kho_exiles_of_khorne", region = "" },
                { coordinates = {620, 421}, initial_owner = "wh_main_grn_orcs_of_the_bloody_hand", owner_if_player = "wh3_main_ogr_disciples_of_the_maw", region = "" },
                { coordinates = {800, 363}, initial_owner = "wh2_main_skv_clan_mors", owner_if_player = "wh2_dlc09_tmb_lybaras", region = "" },
                { coordinates = {710, 533}, initial_owner = "wh_main_dwf_dwarfs", owner_if_player = "wh_main_teb_border_princes", region = "" },
                { coordinates = {691, 390}, initial_owner = "wh3_main_ie_vmp_sires_of_mourkain", owner_if_player = "wh3_main_ie_vmp_sires_of_mourkain", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["lustria"] = {
            ["smithies"] = {
                { coordinates = {82, 438}, initial_owner = "wh2_main_lzd_hexoatl", owner_if_player = "wh2_dlc13_emp_the_huntmarshals_expedition", region = "" },
                { coordinates = {72, 313}, initial_owner = "wh2_dlc13_emp_the_huntmarshals_expedition", owner_if_player = "wh2_main_def_blood_hall_coven", region = "" },
                { coordinates = {237, 298}, initial_owner = "wh2_dlc11_cst_vampire_coast", owner_if_player = "wh_main_brt_bordeleaux", region = "" },
                { coordinates = {220, 235}, initial_owner = "wh2_main_lzd_itza", owner_if_player = "wh2_dlc11_cst_vampire_coast", region = "" },
                { coordinates = {197, 140}, initial_owner = "wh2_main_skv_clan_pestilens", owner_if_player = "wh2_dlc12_lzd_cult_of_sotek", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["cathay"] = {
            ["smithies"] = {
                {
                    coordinates = {1211, 647},
                    initial_owner = "wh3_main_cth_the_northern_provinces",
                    owner_if_player = "wh3_dlc20_chs_vilitch",
                    region = ""
                },
                {
                    coordinates = {1348, 607},
                    initial_owner = "wh2_dlc11_def_the_blessed_dread",
                    owner_if_player = "wh3_main_cth_celestial_loyalists",
                    region = ""
                },
                {
                    coordinates = {1308, 369},
                    initial_owner = "wh2_dlc13_lzd_spirits_of_the_jungle",
                    owner_if_player = "wh3_dlc21_wef_spirits_of_shanlin",
                    region = ""
                }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["mountainsofmourn"] = {
            ["smithies"] = {
                { coordinates = {1103, 567}, initial_owner = "wh3_main_cth_the_northern_provinces", owner_if_player = "wh3_main_cth_dissenter_lords_of_jinshen", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["darklands"] = {
            ["smithies"] = {
                { coordinates = {892, 651}, initial_owner = "wh3_main_vmp_lahmian_sisterhood", owner_if_player = "wh3_main_vmp_lahmian_sisterhood", region = "" },
                { coordinates = {934, 551}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_grn_dark_land_orcs", region = "" },
                { coordinates = {1012, 461}, initial_owner = "wh3_main_ogr_goldtooth", owner_if_player = "wh3_main_ogr_lazarghs", region = "" },
                { coordinates = {873, 430}, initial_owner = "wh2_dlc15_hef_imrik", owner_if_player = "wh3_main_ogr_thunderguts", region = "" },
                { coordinates = {1105, 453}, initial_owner = "wh3_main_vmp_caravan_of_blue_roses", owner_if_player = "wh3_main_cth_the_western_provinces", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}

         },
         ["worldsedgemountains"] = {
            ["smithies"] = {
                { coordinates = {832, 554}, initial_owner = "wh3_dlc23_chd_legion_of_azgorh", owner_if_player = "wh_main_dwf_karak_azul", region = "" },
                { coordinates = {837, 449}, initial_owner = "wh2_dlc15_hef_imrik", owner_if_player = "wh_main_dwf_karak_azul", region = "" },
                { coordinates = {727, 460}, initial_owner = "wh_main_grn_crooked_moon", owner_if_player = "wh_main_grn_scabby_eye", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["empire"] = {
            ["smithies"] = {
                { coordinates = {540, 765}, initial_owner = "wh_dlc03_bst_beastmen", owner_if_player = "wh_main_emp_nordland", region = "" },
                { coordinates = {585, 715}, initial_owner = "wh3_dlc20_chs_festus", owner_if_player = "wh_main_emp_empire", region = "" },
                { coordinates = {658, 627}, initial_owner = "wh_main_vmp_schwartzhafen", owner_if_player = "wh_main_emp_stirland", region = "" },
                { coordinates = {710, 658}, initial_owner = "wh_main_vmp_schwartzhafen", owner_if_player = "wh_main_emp_ostland", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}

         },
         ["kislev"] = {
            ["smithies"] = {
                { coordinates = {726, 695}, initial_owner = "wh3_main_ksl_the_ice_court", owner_if_player = "wh_dlc08_nor_goromadny_tribe", region = "" },
                { coordinates = {611, 797}, initial_owner = "wh3_main_ksl_the_great_orthodoxy", owner_if_player = "wh3_main_ksl_the_great_orthodoxy", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}

         },
         ["norsca"] = {
            ["smithies"] = {
                { coordinates = {678, 825}, initial_owner = "wh2_main_skv_clan_moulder", owner_if_player = "wh_main_dwf_kraka_drak", region = "" },
                { coordinates = {808, 773}, initial_owner = "wh3_main_ksl_the_ice_court", owner_if_player = "wh_dlc08_nor_goromadny_tribe", region = "" },
                { coordinates = {433, 859}, initial_owner = "wh_dlc08_nor_norsca", owner_if_player = "wh_main_nor_varg", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}

         },
         ["borderprinces"] = {
            ["smithies"] = {
                { coordinates = {435, 439}, initial_owner = "wh2_main_skv_clan_skryre", owner_if_player = "wh_main_teb_estalia", region = "" },
                { coordinates = {675, 549}, initial_owner = "wh_main_teb_border_princes", owner_if_player = "wh_main_teb_border_princes", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["greymountains"] = {
            ["smithies"] = {},

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["bretonnia"] = {
            ["smithies"] = {
                { coordinates = {491, 511}, initial_owner = "wh_dlc05_wef_wood_elves", owner_if_player = "wh_main_brt_carcassonne", region = "" },
                { coordinates = {459, 599}, initial_owner = "wh2_dlc15_grn_broken_axe", owner_if_player = "wh2_dlc11_vmp_the_barrow_legion", region = "" },
                { coordinates = {426, 674}, initial_owner = "wh_main_brt_bretonnia", owner_if_player = "wh_main_emp_marienburg", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["ulthuan"] = {
            ["smithies"] = {
                { coordinates = {216, 630}, initial_owner = "wh3_main_sla_seducers_of_slaanesh", owner_if_player = "wh2_main_def_scourge_of_khaine", region = "" },
                { coordinates = {326, 593}, initial_owner = "wh3_main_sla_seducers_of_slaanesh", owner_if_player = "wh2_main_hef_yvresse", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["naggarond"] = {
            ["smithies"] = {
                { coordinates = {89, 873}, initial_owner = "wh2_main_def_naggarond", owner_if_player = "wh3_dlc20_chs_valkia", region = "" },
                { coordinates = {296, 866}, initial_owner = "wh2_main_def_har_ganeth", owner_if_player = "wh3_main_grn_da_cage_breakaz", region = "" },
                { coordinates = {206, 744}, initial_owner = "wh2_dlc11_cst_the_drowned", owner_if_player = "wh2_main_hef_nagarythe", region = "" },
                { coordinates = {62, 519}, initial_owner = "wh2_main_def_cult_of_pleasure", owner_if_player = "wh2_main_def_ssildra_tor", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
         },
         ["northernchaoswastes"] = {
            ["smithies"] = {
                {
                    coordinates = {554, 935},
                    initial_owner = "wh2_main_def_hag_graef",
                    owner_if_player = "wh3_main_tze_broken_wheel",
                    region = ""
                },
                {
                    coordinates = {837, 882},
                    initial_owner = "wh3_main_ksl_ursun_revivalists",
                    owner_if_player = "wh_main_chs_chaos",
                    region = ""
                },
                {
                    coordinates = {843, 751},
                    initial_owner = "wh_main_grn_greenskins",
                    owner_if_player = "wh3_main_grn_slaves_of_zharr",
                    region = ""
                },
                {
                    coordinates = {1097, 704},
                    initial_owner = "wh3_dlc20_chs_kholek",
                    owner_if_player = "wh3_main_ogr_fleshgreeders",
                    region = ""
                },
                {
                    coordinates = {1221, 692},
                    initial_owner = "wh3_dlc20_chs_vilitch",
                    owner_if_player = "wh3_main_cth_imperial_wardens",
                    region = ""
                }
            },

            ["taverns"] = {},

            ["resources"] = {}
         }
    },
}

-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- realm_of_chaos

--[[
Coordinates for the default campaign of WH3.
Used the 2 coordinates system of a physical image map and the logical map through the script_debug_activator mod whenever one clicks on a character (coordinates log is the logical coordinates on the map).

Things to understand:
- ORDERED BY KNOWN ZONE
[ZONE]
- PROVINCE

Special buildings are maximum 2 per zone only. As such they are specially separated and assigned here once the mod configuration tool is in the workshop, make all this configurable.
--]]
-- Auto generated by algorithm in Jun 29, 2022.
-- Map: Realm Of Chaos
M.realm_of_chaos = {
    treasures_and_spots = {
         ["kislev"] = {
              -- Troll Country
              {284, 231},
              {328, 210},
              {243, 169},
              {243, 220},
              -- Northern Oblast
              {365, 134},
              {319, 169},
              {280, 180},
              -- River Lynsk: Erengrad
              {238, 145},
              {282, 137},
              -- Black Blood Pass
              {367, 218},
              -- The Cursed City: Praag
              {435, 196},
              -- River Urskoy: Kislev
              {439, 135},
              -- Eastern Oblast
              {518, 135},
              {463, 175},
              -- Dukhlys Forest
              {489, 198},
              {514, 178},
              {557, 221},
         },
         ["darklands"] = {
              -- Zorn Uzkul
              {682, 200},
              {766, 233},
              {734, 168},
              -- The Plain of Zharr
              {720, 144},
              {806, 165},
              {817, 210},
              -- The Blasted Wastes
              {762, 110},
              {776, 83},
              {792, 117},
              {858, 135},
              -- The Wolf Lands
              {848, 75},
              {823, 32},
              {881, 36},
              -- The Howling Wastes
              {873, 161},
              {866, 218},
              {933, 166},
              {941, 188},
              -- The Haunted Forest
              {956, 115},
              {1024, 162},
         },
         ["wordlsedgemountains"] = {
              -- The High Pass
              {692, 224},
              {603, 228},
              -- Worlds Edge Mountains
              {590, 133},
              -- Peak Pass
              {641, 107},
              {595, 78},
              -- Black Water
         },
         ["empire"] = {
              -- The Witch's Wood
              {98, 182},
              -- Wasteland
              {86, 126},
              {60, 140},
              {69, 97},
              {93, 77},
              -- Northern Grey Mountains
              -- Southern Grey Mountains
              {79, 33},
              -- Middenland
              {137, 121},
              {161, 97},
              {181, 111},
              -- Nordland
              {157, 182},
              {167, 150},
              {214, 131},
              -- Hochland
              {214, 56},
              {257, 45},
              {287, 63},
              -- Reikland
              {132, 53},
              {161, 41},
              {227, 32},
              -- Wissenland
              {350, 38},
              {355, 20},
              -- Talabecland
              {346, 55},
              -- Ostland
              {327, 137},
              {309, 113},
              {360, 107},
              {337, 88},
              -- Ostermark
              {437, 108},
              {429, 83},
              {472, 77},
              {513, 104},
              -- Stirland
              {381, 37},
              {426, 19},
              {434, 55},
              -- Sylvania
              {457, 18},
              {499, 23},
              {517, 61},
         },
         ["norsca"] = {
              -- Vanaheim Mountains
              {67, 457},
              {45, 432},
              {87, 378},
              -- Helspire Mountains
              {164, 381},
              {203, 332},
              {265, 336},
              -- Ice Tooth Mountains
              {129, 338},
              {136, 300},
              {163, 332},
              -- Trollheim Mountains
              {214, 276},
              {260, 252},
              -- Gianthome Mountains
              {292, 305},
              {328, 287},
              {388, 272},
              {474, 280},
              {520, 263},
              -- The Goromadny
              {582, 260},
              {618, 273},
         },
         ["mountainsofmourn"] = {
              -- Path to the East
              {733, 317},
              {768, 366},
              -- Gash Kadrak
              {800, 304},
              {820, 338},
              -- Mountains of Mourn
              {879, 338},
              -- Mist Gorge
              {945, 326},
              -- Wyrm Pass
              {1010, 330},
              {988, 281},
              -- Bone Road
              {863, 465},
              -- Ivory Road
              -- Ice Pass
              -- Ancient Giant Lands
         },
         ["cathay"] = {
              -- Imperial Road
              {1004, 664},
              {959, 656},
              {1058, 642},
              {1028, 631},
              -- Land of Stone and Steel
              {942, 632},
              {914, 560},
              {948, 579},
              {912, 584},
              -- Forests of the Moon
              {1042, 575},
              {1035, 603},
              -- Gunpowder Road
              {909, 516},
              {920, 491},
              {950, 521},
              -- Warpstone Desert
              {930, 461},
              {955, 454},
              {985, 484},
              -- Celestial Riverlands
              {1084, 579},
              {1094, 469},
              -- Wasteland of Jinshen
              {1040, 456},
              {981, 449},
              {1040, 456},
              -- Broken Lands of Tian Li
              {1059, 417},
         },
         ["chaoswastes"] = {
              -- The Shard Lands
              {105, 577},
              {139, 566},
              {247, 582},
              {244, 533},
              -- Northern Wastes
              {107, 520},
              {137, 477},
              {188, 435},
              {198, 487},
              {216, 515},
              -- The Eternal Lagoon
              {298, 544},
              {338, 524},
              {329, 471},
              -- Bloodfire Falls
              {274, 442},
              {303, 440},
              {338, 442},
              {273, 398},
              -- The Cold Mires
              {291, 372},
              {298, 412},
              -- Plain of Bone
              {409, 474},
              {446, 457},
              {491, 460},
              -- Plain of Illusions
              {442, 401},
              {392, 376},
              {389, 337},
              {436, 357},
              {486, 360},
              {524, 351},
              -- The Blood Marshes
              {487, 410},
              {553, 445},
              {565, 417},
              {552, 382},
              -- K'datha
              {619, 449},
              {605, 417},
              {642, 472},
              {680, 478},
              {741, 470},
              -- The Cliffs of Death
              {607, 320},
              {633, 313},
              -- Road of Skulls
              {677, 316},
              {678, 339},
              {716, 360},
              {679, 391},
              {723, 398},
              {733, 431},
              -- Road to Damnation
              {814, 420},
              {801, 462},
              {788, 490},
              {741, 470},
              -- Eastern Steppes
              {851, 517},
              {850, 572},
              -- The Red Wastes
              {888, 589},
              {862, 612},
              {895, 618},
              {894, 646},
         },
    },
    points_of_interest = {
        ["kislev"] = {
            ["smithies"] = {
                { coordinates = {524, 216}, initial_owner = "wh_main_nor_baersonling", owner_if_player = "wh_main_nor_baersonling", region = "" },
                { coordinates = {229, 203}, initial_owner = "wh3_main_ksl_the_great_orthodoxy", owner_if_player = "wh3_main_ksl_the_great_orthodoxy", region = "wh3_main_chaos_region_castle_alexandronov" } --wh_main_nor_varg
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["darklands"] = {
            ["smithies"] = {
                { coordinates = {894, 100}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_grn_drippin_fangs", region = "" },
                { coordinates = {800, 232}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_grn_drippin_fangs", region = "" },
                { coordinates = {832, 148}, initial_owner = "wh2_dlc09_skv_clan_rictus", owner_if_player = "wh3_main_lzd_tepoks_spawn", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["wordlsedgemountains"] = {
            ["smithies"] = {
                { coordinates = {663, 178}, initial_owner = "wh2_dlc16_vmp_lahmian_sisterhood", owner_if_player = "wh2_dlc16_vmp_lahmian_sisterhood", region = "" },
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["empire"] = {
            ["smithies"] = {
                { coordinates = {189, 41}, initial_owner = "wh_main_emp_empire", owner_if_player = "wh_main_emp_middenland", region = "" },
                { coordinates = {485, 54}, initial_owner = "wh_main_vmp_waldenhof", owner_if_player = "wh_main_vmp_waldenhof", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["norsca"] = {
            ["smithies"] = {
                { coordinates = {168, 275}, initial_owner = "wh2_dlc13_wef_laurelorn_forest", owner_if_player = "wh2_dlc13_wef_laurelorn_forest", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["mountainsofmourn"] = {
            ["smithies"] = {
                { coordinates = {873, 235}, initial_owner = "wh3_main_dwf_karak_azorn", owner_if_player = "wh3_main_dwf_karak_azorn", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["cathay"] = {
            ["smithies"] = {
                { coordinates = {918, 479}, initial_owner = "wh3_main_cth_dissenter_lords_of_jinshen", owner_if_player = "wh3_main_cth_dissenter_lords_of_jinshen", region = "" },
                { coordinates = {913, 621}, initial_owner = "wh3_main_chs_dreaded_wo", owner_if_player = "wh3_main_chs_dreaded_wo", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
        },

        ["chaoswastes"] = {
            ["smithies"] = {
                { coordinates = {234, 423}, initial_owner = "wh3_main_sla_exquisite_pain", owner_if_player = "wh3_main_sla_exquisite_pain", region = "" },
                { coordinates = {420, 407}, initial_owner = "wh3_main_nur_maggoth_kin", owner_if_player = "wh3_main_nur_maggoth_kin", region = "" },
                { coordinates = {614, 304}, initial_owner = "wh3_main_chs_tong", owner_if_player = "wh3_main_chs_tong", region = "" },
                { coordinates = {781, 431}, initial_owner = "wh3_main_ogr_mountaineaters", owner_if_player = "wh3_main_ogr_mountaineaters", region = "" }
            },

            ["taverns"] = {},

            ["resources"] = {}
        }
    },
}

-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- immortal_empires_expanded

-- Manually acquired on 2025-02-03.
M.immortal_empires_expanded = {
    treasures_and_spots = {
        -- These IEEE-specific coordinates will not ever be used with the original system.
        -- In addition, these are intended to be concatenated with the vanilla IE coordinates since they share the same map with the new map additions by IEEE.
        ["placeholder"] = {
            -- The Spice Route
            {1110, 383},
            -- Land of a Thousand Gods
            {1114, 335},
            {1160, 334},
            -- Shambani Foothills
            {1204, 309},
            {1148, 307},
            -- Central Ind
            {1164, 259},
            -- Ind's End
            {1135, 251},
            {1102, 248},
            {1076, 217},
            {1050, 222},
            {1047, 154},
            -- Eastern Colonies
            {1015, 137},
            {1031, 121},
            -- Forest of Broken Fangs
            {1312, 303},
            {1230, 278},
            -- Whispering Jungle
            {1379, 295},
            -- Cochincathay
            {1371, 247},
            {1364, 222},
            {1402, 179},
            -- Bloodied Coast
            {1226, 236},
            {1213, 205},
            {1263, 209},
            -- Kureshi Hills
            {1311, 131},
            {1290, 110},
            {1250, 119},
            {1264, 82},
            {1307, 79},
            {1310, 114},
            -- Hokusei Arc
            {1452, 388},
            {1455, 349},
            -- Hokurikudo
            {1505, 342},
            -- Samurai's Domain
            {1445, 301},
            -- Sun's Origin
            {1455, 273},
            {1441, 259},
            {1506, 216},
            -- Eastern Circuit
            {1497, 278},
            {1522, 269},
            {1513, 252},
            {1521, 202},
            -- North Isle
            {1462, 129},
            -- Lost Isles of Elithis
            {1481, 71},
            {1452, 21},
            -- Green Steppes
            {1157, 793},
            {1204, 769},
            {1233, 753},
            -- Deep Steppes
            {1165, 817},
            {1185, 836},
            {1234, 779},
            {1225, 817},
            {1253, 823},
            -- East Kurgania
            {1286, 793},
            {1259, 754},
            {1294, 744},
            {1315, 762},
            {1341, 734},
            -- Grave of Scythia
            {1388, 743},
            {1378, 778},
            {1401, 742},
            {1437, 764},
            -- The Black Wastes
            {1441, 723},
            {1458, 746},
            -- West Hunguria
            {1469, 782},
            {1493, 747},
            {1530, 762},
            {1539, 814},
            -- North Ilhan
            {1409, 694},
            {1468, 656},
            {1388, 609},
            -- East Ilhan
            {1468, 656},
            {1438, 569},
            -- South Ilhan
            {1417, 588},
            {1385, 566},
        },
    },
    points_of_interest = {
        ["placeholder"] = {
            ["smithies"] = {},
            ["taverns"] = {},
            ["resources"] = {}
         },
    },
}

return M
