--- Crafted (gold, uniqueness 199) items LEAPOI may hand out: every vanilla item of that grouping, including the Forge of Daith pieces, taken
--- from the vanilla database on 2026-10-10. None needs a DLC. Pure data - no runtime logic.
--- Each entry: `key` (ancillary key) and optional `dlc` (ownership product key a player faction must own), as in configs/legendary_items.lua.

return {
    { key = "wh2_dlc16_anc_armour_dragon_cuirass_4" },
    { key = "wh2_dlc16_anc_armour_dreaming_boots_4" },
    { key = "wh2_dlc16_anc_armour_eagle_vambraces_4" },
    { key = "wh2_dlc16_anc_armour_twilight_helm_4" },
    { key = "wh2_dlc16_anc_enchanted_item_dragon_pendant_4" },
    { key = "wh2_dlc16_anc_enchanted_item_dreaming_cloak_4" },
    { key = "wh2_dlc16_anc_enchanted_item_eagle_quiver_4" },
    { key = "wh2_dlc16_anc_enchanted_item_twilight_standard_4" },
    { key = "wh2_dlc16_anc_talisman_dragon_mask_4" },
    { key = "wh2_dlc16_anc_talisman_dreaming_ring_4" },
    { key = "wh2_dlc16_anc_talisman_eagle_mask_4" },
    { key = "wh2_dlc16_anc_talisman_twilight_horn_4" },
    { key = "wh2_dlc16_anc_weapon_dragon_spear_4" },
    { key = "wh2_dlc16_anc_weapon_dreaming_bow_4" },
    { key = "wh2_dlc16_anc_weapon_eagle_bow_4" },
    { key = "wh2_dlc16_anc_weapon_twilight_spear_4" },
    { key = "wh2_main_anc_arcane_item_jewel_of_the_dusk" },
    { key = "wh2_main_anc_arcane_item_staff_of_solidity" },
    { key = "wh2_main_anc_armour_boots_of_bracchus" },
    { key = "wh2_main_anc_armour_chromatic_armour" },
    { key = "wh2_main_anc_armour_crown_of_authority" },
    { key = "wh2_main_anc_armour_enchanted_ithilmar_breastplate" },
    { key = "wh2_main_anc_armour_helm_of_khaine" },
    { key = "wh2_main_anc_armour_rocket_boots" },
    { key = "wh2_main_anc_armour_shroud_of_death" },
    { key = "wh2_main_anc_armour_skull_helmet" },
    { key = "wh2_main_anc_armour_winged_boots" },
    { key = "wh2_main_anc_enchanted_item_blessed_tome" },
    { key = "wh2_main_anc_enchanted_item_box_of_eerie_noises" },
    { key = "wh2_main_anc_enchanted_item_brass_horn" },
    { key = "wh2_main_anc_enchanted_item_chest_of_sustenance" },
    { key = "wh2_main_anc_enchanted_item_enchanted_spyglass" },
    { key = "wh2_main_anc_enchanted_item_enriched_warpstone_dust" },
    { key = "wh2_main_anc_enchanted_item_gilded_horn_of_galon_konook" },
    { key = "wh2_main_anc_enchanted_item_odd_powder_keg" },
    { key = "wh2_main_anc_enchanted_item_ring_of_hukon" },
    { key = "wh2_main_anc_enchanted_item_rod_of_briars" },
    { key = "wh2_main_anc_enchanted_item_satchel_of_potions" },
    { key = "wh2_main_anc_talisman_amulet_of_foresight" },
    { key = "wh2_main_anc_talisman_diamond_guardian_phoenix" },
    { key = "wh2_main_anc_talisman_emerald_collar" },
    { key = "wh2_main_anc_talisman_ruby_guardian_phoenix" },
    { key = "wh2_main_anc_talisman_sapphire_guardian_phoenix" },
    { key = "wh2_main_anc_weapon_aventurine_dagger" },
    { key = "wh2_main_anc_weapon_blade_of_sea_gold" },
    { key = "wh2_main_anc_weapon_mechanical_claw" },
    { key = "wh2_main_anc_weapon_reaver_bow" },
    { key = "wh2_main_anc_weapon_righteous_wrath" },
    { key = "wh2_main_anc_weapon_sea_gold_parrying_blade" },
    { key = "wh2_main_anc_weapon_winged_staff" },
    { key = "wh2_main_anc_weapon_wrath_of_kurnous" },
    { key = "wh3_dlc29_anc_talisman_standard_of_the_white_wolf" },
}
