--- The LEAPOI help pages in index order, each with the record builder of every line. Line n of page `key` reads the
--- `advice_info_texts` record `land_enc_hp_<key>_<nnn>`. Generated by helper_scripts/generators/leapoi_help_pages.py: do not
--- edit by hand.

return {
    { key = "leapoi", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal", "hpr_normal_unfaded", "hpr_normal",
    } },
    { key = "encounters", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal", "hpr_normal_unfaded", "hpr_normal",
    } },
    { key = "battle_events", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_normal", "hpr_normal_unfaded", "hpr_bulleted",
        "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal", "hpr_normal_unfaded",
        "hpr_normal", "hpr_normal_unfaded", "hpr_normal",
    } },
    { key = "treasure", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal",
        "hpr_normal_unfaded", "hpr_normal",
    } },
    { key = "towers", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_normal_unfaded", "hpr_normal", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_normal_unfaded", "hpr_normal",
    } },
    { key = "smithies", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded",
        "hpr_normal", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded",
        "hpr_normal",
    } },
    { key = "taverns", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal",
        "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal",
        "hpr_normal_unfaded", "hpr_normal",
    } },
    { key = "boons_and_curses", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded", "hpr_normal",
        "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded", "hpr_bulleted",
        "hpr_bulleted", "hpr_small",
    } },
    { key = "army_spells", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_bulleted", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_bulleted",
    } },
    { key = "settings", records = {
        "hpr_title", "hpr_leader", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted",
        "hpr_bulleted", "hpr_normal_unfaded", "hpr_bulleted", "hpr_bulleted", "hpr_bulleted", "hpr_normal_unfaded",
        "hpr_bulleted", "hpr_bulleted",
    } },
}
