--- Legendary (purple, uniqueness 198/200) items LEAPOI may hand out: vanilla items not locked to a lord or hero type, quest, ritual, skill,
--- tech, item set or staged chain, and not tied to a lord-specific mechanic, runes, endgame or LEAPOI's own Daemonic Gift rewards. Picked
--- on 2026-09-28 from the vanilla database. Pure data - no runtime logic.
--- Each entry: `key` (ancillary key) and optional `dlc` (ownership product key a player faction must own).

return {
    { key = "wh2_dlc10_anc_enchanted_item_burning_phoenix_pinion" },
    { key = "wh2_dlc10_anc_talisman_carnosaur_skull" },
    { key = "wh2_dlc10_anc_talisman_hydra_head" },
    { key = "wh2_dlc10_anc_weapon_warptech_arsenal" },
    { key = "wh2_dlc10_dwf_anc_armour_starmetal_plate_caravan" },
    { key = "wh2_dlc10_dwf_anc_talisman_the_ankor_chain_caravan" },
    { key = "wh2_dlc13_anc_arcane_item_amplifier" },
    { key = "wh2_dlc13_anc_talisman_stadsraad_key" },
    { key = "wh2_dlc13_anc_talisman_sylvania_journal" },
    { key = "wh2_dlc13_anc_weapon_runefang_averland" },
    { key = "wh2_dlc13_anc_weapon_runefang_hochland" },
    { key = "wh2_dlc13_anc_weapon_runefang_middenland" },
    { key = "wh2_dlc13_anc_weapon_runefang_nordland" },
    { key = "wh2_dlc13_anc_weapon_runefang_ostermark" },
    { key = "wh2_dlc13_anc_weapon_runefang_ostland" },
    { key = "wh2_dlc13_anc_weapon_runefang_reikland" },
    { key = "wh2_dlc13_anc_weapon_runefang_solland" },
    { key = "wh2_dlc13_anc_weapon_runefang_stirland" },
    { key = "wh2_dlc13_anc_weapon_runefang_talabecland" },
    { key = "wh2_dlc13_anc_weapon_runefang_wissenland" },
    { key = "wh2_dlc13_anc_weapon_scar" },
    { key = "wh2_dlc15_anc_arcane_item_blacktoofs_head_in_a_jar" },
    { key = "wh2_dlc16_anc_armour_great_stag_helm" },
    { key = "wh2_dlc16_anc_weapon_witstealer_sword" },
    { key = "wh2_main_anc_weapon_the_fellblade" },
    { key = "wh3_cp1_enchanted_item_heavens_gate", dlc = "TW_WH3_CP1_BHASHIVA" },
    { key = "wh3_dlc23_anc_armour_lesser_relic_of_skavor" },
    { key = "wh3_dlc23_anc_armour_major_relic_of_grungni" },
    { key = "wh3_dlc23_anc_convoy_bones_of_the_maw", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_crown_of_skulls", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_everchanging_shield", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_everlasting_glacier", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_mirror_blade", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_radiating_spike", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_ring_of_thorns", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_convoy_spiked_whip", dlc = "TW_WH3_CHAOS_DWARFS" },
    { key = "wh3_dlc23_anc_enchanted_item_lesser_relic_of_morgrim" },
    { key = "wh3_dlc23_anc_enchanted_item_major_relic_of_valaya" },
    { key = "wh3_dlc23_anc_talisman_lesser_relic_of_thungni" },
    { key = "wh3_dlc23_anc_talisman_major_relic_of_grimnir" },
    { key = "wh3_dlc23_anc_weapon_lesser_relic_of_gazul" },
    { key = "wh3_dlc23_anc_weapon_lesser_relic_of_smednir" },
    { key = "wh3_dlc24_anc_arcane_item_alchemical_notes", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_arcane_item_captains_horn", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_arcane_item_corrupted_flame", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_armour_scavenged_laboratory_materials", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_armour_unknown_champions_cloak", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_corrupted_icon", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_facial_scruff", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_hellforge_flame", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_kraken_fang", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_pilfered_palanquin", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_tree_sap", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_talisman_undead_tome", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_weapon_runefang", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc24_anc_weapon_weeping_blade", dlc = "TW_WH3_SHADOWS_OF_CHANGE_TZE" },
    { key = "wh3_dlc25_anc_enchanted_item_heart_of_malevolence", dlc = "TW_WH3_THRONES_OF_DECAY_DWF" },
    { key = "wh3_dlc25_anc_talisman_crimson_gemstone", dlc = "TW_WH3_THRONES_OF_DECAY_DWF" },
    { key = "wh3_dlc25_anc_weapon_experimental_explosive_caravan" },
    { key = "wh3_dlc26_anc_armour_cloak_of_skulls" },
    { key = "wh3_dlc26_anc_cloak_of_skulls" },
    { key = "wh3_dlc27_anc_arcane_item_azriks_map_star_striding" },
    { key = "wh3_dlc27_anc_arcane_item_stone_of_shyish" },
    { key = "wh3_dlc27_anc_armour_ravagers_chainmail" },
    { key = "wh3_dlc27_anc_banner_of_depravity" },
    { key = "wh3_dlc27_anc_chaos_armour" },
    { key = "wh3_dlc27_anc_enchanted_item_admirals_spyglass" },
    { key = "wh3_dlc27_anc_enchanted_item_bale_taurus_head" },
    { key = "wh3_dlc27_anc_enchanted_item_black_dragon_skull" },
    { key = "wh3_dlc27_anc_enchanted_item_carrion_spine" },
    { key = "wh3_dlc27_anc_enchanted_item_celestial_lion_feathers" },
    { key = "wh3_dlc27_anc_enchanted_item_cockatrice_eye" },
    { key = "wh3_dlc27_anc_enchanted_item_collar_hounds_headsman" },
    { key = "wh3_dlc27_anc_enchanted_item_dread_saurian_tooth" },
    { key = "wh3_dlc27_anc_enchanted_item_fallen_chieftains_jewel" },
    { key = "wh3_dlc27_anc_enchanted_item_feral_manticore_tail" },
    { key = "wh3_dlc27_anc_enchanted_item_ghorgon_blade" },
    { key = "wh3_dlc27_anc_enchanted_item_jabberslythe_blood" },
    { key = "wh3_dlc27_anc_enchanted_item_lammasu_head" },
    { key = "wh3_dlc27_anc_enchanted_item_preyton_horns" },
    { key = "wh3_dlc27_anc_enchanted_item_spikes_chimera" },
    { key = "wh3_dlc27_anc_enchanted_item_toad_dragon_venom_glands" },
    { key = "wh3_dlc27_anc_talisman_charm_of_the_gods" },
    { key = "wh3_dlc27_anc_talisman_eagle_feather_torc" },
    { key = "wh3_dlc27_anc_weapon_axe_of_the_pale_serpent" },
    { key = "wh3_dlc27_anc_weapon_tenebrous_forge_hammer" },
    { key = "wh3_dlc29_anc_arcane_item_morskittar_notes" },
    { key = "wh3_dlc29_anc_bst_talisman_of_dark_gods" },
    { key = "wh3_dlc29_anc_enchanted_item_skaven_war_plans" },
    { key = "wh3_dlc29_anc_enchanted_item_sturdy_boots" },
    { key = "wh3_dlc29_anc_talisman_collar_of_shapesh" },
    { key = "wh3_dlc29_anc_talisman_scholary_aegis" },
    { key = "wh3_main_anc_arcane_item_chalice_of_malfleur" },
    { key = "wh3_main_anc_arcane_item_necromantic_tome" },
    { key = "wh3_main_anc_armour_accursed_armour" },
    { key = "wh3_main_anc_armour_briarsheath" },
    { key = "wh3_main_anc_armour_helm_of_draesca" },
    { key = "wh3_main_anc_armour_scintillating_shield" },
    { key = "wh3_main_anc_caravan_bejewelled_dagger" },
    { key = "wh3_main_anc_caravan_frost_wyrm_skull" },
    { key = "wh3_main_anc_caravan_frozen_pendant" },
    { key = "wh3_main_anc_caravan_gryphon_legion_lance" },
    { key = "wh3_main_anc_caravan_luminark_lens" },
    { key = "wh3_main_anc_caravan_mantle_of_damsel_elena" },
    { key = "wh3_main_anc_caravan_sky_titan_relic" },
    { key = "wh3_main_anc_caravan_statue_of_zharr" },
    { key = "wh3_main_anc_caravan_von_carstein_blade" },
    { key = "wh3_main_anc_enchanted_item_aldreds_casket" },
    { key = "wh3_main_anc_enchanted_item_coin_of_ranald" },
    { key = "wh3_main_anc_enchanted_item_dreamwine" },
    { key = "wh3_main_anc_enchanted_item_idol_zak_aloooog" },
    { key = "wh3_main_anc_enchanted_item_maads_map" },
    { key = "wh3_main_anc_enchanted_item_myrmidia_scroll" },
    { key = "wh3_main_anc_enchanted_item_skaven_map" },
    { key = "wh3_main_anc_weapon_cynatcian" },
    { key = "wh3_main_anc_weapon_elthraician" },
    { key = "wh3_main_anc_weapon_wyrmslayer_sword" },
    { key = "wh_dlc08_anc_enchanted_item_ancient_frost_wyrm_scale" },
    { key = "wh_dlc08_anc_enchanted_item_arachnarok_eggs" },
    { key = "wh_dlc08_anc_enchanted_item_great_horn_of_dragon_ogre" },
    { key = "wh_dlc08_anc_talisman_giant_cygor_eyeball" },
    { key = "wh_dlc08_anc_talisman_terrorgheist_skull" },
    { key = "wh_dlc08_anc_weapon_forest_dragon_fang" },
    { key = "wh_dlc08_anc_weapon_stinky_giant_club" },
    { key = "wh_dlc13_anc_weapon_anguish_of_languille" },
    { key = "wh_main_anc_weapon_the_middenland_runefang" },
}
