--- Lore army compositions for the battle modifiers (configs/battle_modifiers.lua): iconic armies of one faction. A lore army spends
--- `lore_share` of the enemy's gold after the spine on its own units, split by `shares`, and the rest on a normal army from the whole
--- roster. Pure data.

--[[
Fields of each lore army:
- key: the battle modifier key, also the key of its dilemma line and notice.
- faction: the 3-letter faction shorthand it rolls for.
- name, effect: the dilemma line, "Modifier: <name> - <effect>", written by the generator.
- shares: the percent of its lore gold each role gets.
- units: the vanilla land units of the faction it buys its lore part from.
--]]
return {
    { key = "lore_skv_pestilens", faction = "skv", name = "Plague Procession",
      effect = "Plague monks and censer bearers of Clan Pestilens crowd around a Cauldron of a Thousand Poxes.",
      shares = { frontline = 60, missile = 10, monsters = 15, artillery = 15 },
      units = {
          "wh2_main_skv_inf_skavenslaves_0", "wh3_dlc29_skv_inf_pusbags", "wh2_main_skv_inf_plague_monks", "wh2_main_skv_inf_poison_wind_globadiers", "wh2_main_skv_art_plagueclaw_catapult",
          "wh2_main_skv_inf_plague_monk_censer_bearer", "wh3_dlc29_skv_veh_cauldron_of_a_thousand_poxes",
      } },
    { key = "lore_skv_skryre", faction = "skv", name = "Skryre Arsenal",
      effect = "Weapon teams bristle along the clanrat line. Stormfiends lumber out in front of the warp-lightning cannons.",
      shares = { frontline = 30, missile = 40, cavalry = 5, artillery = 25 },
      units = {
          "wh2_main_skv_inf_clanrats_1", "wh2_main_skv_inf_warpfire_thrower", "wh2_dlc14_skv_inf_warp_grinder_0", "wh2_dlc12_skv_inf_ratling_gun_0", "wh2_main_skv_inf_death_globe_bombardiers",
          "wh2_main_skv_art_warp_lightning_cannon", "wh2_dlc12_skv_veh_doom_flayer_0", "wh3_dlc29_skv_mon_stormfiend_grinderfists", "wh2_dlc12_skv_inf_warplock_jezzails_0",
          "wh3_dlc29_skv_mon_stormfiend_warpfire_projectors", "wh3_dlc29_skv_mon_stormfiend_ratling_cannons", "wh2_main_skv_veh_doomwheel",
      } },
    { key = "lore_skv_moulder", faction = "skv", name = "Moulder Menagerie",
      effect = "A hell pit abomination heaves along behind the packmasters, who drive their rat ogres and wolf rats on with whips.",
      shares = { frontline = 40, missile = 10, cavalry = 15, monsters = 35 },
      units = {
          "wh2_main_skv_inf_skavenslaves_0", "wh2_main_skv_inf_skavenslave_slingers_0", "wh2_main_skv_inf_clanrats_0", "wh2_dlc16_skv_mon_wolf_rats_0", "wh2_dlc16_skv_mon_wolf_rats_1",
          "wh2_main_skv_mon_rat_ogres", "wh2_dlc16_skv_mon_brood_horror_0", "wh2_dlc16_skv_mon_rat_ogre_mutant", "wh2_main_skv_mon_hell_pit_abomination",
      } },
    { key = "lore_tmb_chariots", faction = "tmb", name = "Chariot Legion",
      effect = "Skeletal chariots roll forward in long ranks, with the horsemen of Nehekhara riding on their flanks.",
      shares = { frontline = 25, cavalry = 60, monsters = 15 },
      units = {
          "wh2_dlc09_tmb_inf_skeleton_warriors_0", "wh2_dlc09_tmb_inf_skeleton_spearmen_0", "wh2_dlc09_tmb_cav_skeleton_horsemen_0", "wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0",
          "wh2_dlc09_tmb_inf_nehekhara_warriors_0", "wh2_dlc09_tmb_cav_nehekhara_horsemen_0", "wh2_dlc09_tmb_veh_skeleton_chariot_0", "wh2_dlc09_tmb_veh_skeleton_archer_chariot_0",
          "wh2_dlc09_tmb_cav_necropolis_knights_0",
      } },
    { key = "lore_tmb_constructs", faction = "tmb", name = "Mortuary Constructs",
      effect = "Ushabti and warsphinxes march out of the tombs, and a hierotitan raised by the Mortuary Cult towers over them.",
      shares = { frontline = 40, monsters = 50, artillery = 10 },
      units = {
          "wh2_dlc09_tmb_inf_skeleton_warriors_0", "wh2_dlc09_tmb_inf_tomb_guard_0", "wh2_dlc09_tmb_art_screaming_skull_catapult_0", "wh2_dlc09_tmb_mon_ushabti_0",
          "wh2_dlc09_tmb_mon_tomb_scorpion_0", "wh2_dlc09_tmb_mon_ushabti_1", "wh2_dlc09_tmb_mon_sepulchral_stalkers_0", "wh2_pro06_tmb_mon_bone_giant_0",
          "wh2_dlc09_tmb_mon_khemrian_warsphinx_0", "wh2_dlc09_tmb_mon_necrosphinx_0", "wh2_dlc09_tmb_mon_heirotitan_0", "wh3_dlc29_tmb_mon_khemric_titan",
      } },
    { key = "lore_def_khaine", faction = "def", name = "Khainite Cult",
      effect = "Witch elves and the executioners of Har Ganeth fight for Khaine here, dragging a bloodwrack shrine behind them.",
      shares = { frontline = 60, missile = 10, monsters = 15, artillery = 15 },
      units = {
          "wh2_main_def_inf_bleakswords_0", "wh2_main_def_inf_darkshards_0", "wh2_main_def_inf_witch_elves_0", "wh2_dlc10_def_inf_sisters_of_slaughter",
          "wh2_main_def_inf_har_ganeth_executioners_0", "wh2_dlc14_def_mon_bloodwrack_medusa_0", "wh2_dlc14_def_veh_bloodwrack_shrine_0",
      } },
    { key = "lore_def_corsairs", faction = "def", name = "Black Ark Corsairs",
      effect = "Corsairs fresh off a black ark lead this raid, with a kharibdyss hauled up from the deep.",
      shares = { frontline = 40, missile = 30, cavalry = 10, monsters = 10, artillery = 10 },
      units = {
          "wh2_main_def_inf_dreadspears_0", "wh2_main_def_cav_dark_riders_0", "wh2_main_def_inf_harpies", "wh2_main_def_inf_black_ark_corsairs_0", "wh2_main_def_art_reaper_bolt_thrower",
          "wh2_main_def_inf_black_ark_corsairs_1", "wh2_main_def_inf_shades_0", "wh2_dlc14_def_cav_scourgerunner_chariot_0", "wh2_dlc10_def_mon_kharibdyss_0",
      } },
    { key = "lore_dwf_slayers", faction = "dwf", name = "Slayer Host",
      effect = "Every dwarf in these ranks has taken the Slayer oath and is looking for a glorious death.",
      shares = { frontline = 85, missile = 10, artillery = 5 },
      units = {
          "wh3_dlc25_dwf_inf_slayer_pirates", "wh_main_dwf_veh_gyrocopter_0", "wh_main_dwf_inf_slayers", "wh3_dlc25_dwf_inf_slayers_grudge_unit", "wh_dlc06_dwf_inf_dragonback_slayers_0",
          "wh2_dlc10_dwf_inf_giant_slayers", "wh3_dlc25_dwf_inf_doomseekers",
      } },
    { key = "lore_dwf_underway", faction = "dwf", name = "Underway Guard",
      effect = "Ironbreakers and irondrakes have come up from the deep tunnels to hold this ground.",
      shares = { frontline = 55, missile = 40, artillery = 5 },
      units = {
          "wh_main_dwf_inf_miners_0", "wh_main_dwf_inf_miners_1", "wh_dlc06_dwf_inf_rangers_0", "wh_dlc06_dwf_inf_rangers_1", "wh_main_dwf_inf_irondrakes_0",
          "wh_dlc06_dwf_inf_bugmans_rangers_0", "wh_main_dwf_inf_irondrakes_2", "wh_main_dwf_art_flame_cannon", "wh_main_dwf_inf_ironbreakers",
      } },
    { key = "lore_hef_lothern", faction = "hef", name = "Lothern Fleet",
      effect = "Sea guard and ship crews from Lothern have come ashore, and a merwyrm rises out of the surf behind them.",
      shares = { frontline = 35, missile = 35, cavalry = 10, monsters = 15, artillery = 5 },
      units = {
          "wh3_dlc27_hef_inf_ships_company", "wh2_main_hef_inf_spearmen_0", "wh2_main_hef_inf_lothern_sea_guard_0", "wh2_main_hef_art_eagle_claw_bolt_thrower",
          "wh2_main_hef_inf_lothern_sea_guard_1", "wh3_dlc27_hef_inf_oceanids", "wh3_dlc27_hef_veh_skycutter_bows", "wh3_dlc27_hef_veh_skycutter_bolt_thrower",
          "wh3_dlc27_hef_mon_sea_elemental", "wh3_dlc27_hef_mon_merwyrm",
      } },
    { key = "lore_hef_caledor", faction = "hef", name = "Dragon Host",
      effect = "Dragon princes of Caledor ride to battle, and the great dragons fly with them.",
      shares = { frontline = 30, missile = 10, cavalry = 25, monsters = 35 },
      units = {
          "wh2_main_hef_inf_archers_0", "wh2_main_hef_inf_spearmen_0", "wh2_main_hef_art_eagle_claw_bolt_thrower", "wh2_main_hef_cav_silver_helms_0",
          "wh2_main_hef_inf_swordmasters_of_hoeth_0", "wh2_main_hef_cav_dragon_princes", "wh2_main_hef_mon_sun_dragon", "wh2_main_hef_mon_moon_dragon", "wh2_main_hef_mon_star_dragon",
      } },
    { key = "lore_hef_avelorn", faction = "hef", name = "Avelorn Court",
      effect = "The Sisters of Avelorn have marched out of the Everqueen's forests, with dryads and treemen at their side.",
      shares = { frontline = 45, missile = 25, monsters = 30 },
      units = {
          "wh2_main_hef_inf_archers_0", "wh2_main_hef_inf_spearmen_0", "wh2_dlc10_hef_inf_dryads_0", "wh2_main_hef_mon_great_eagle", "wh2_dlc10_hef_mon_treekin_0",
          "wh2_dlc10_hef_inf_sisters_of_avelorn_0", "wh2_dlc10_hef_mon_treeman_0",
      } },
    { key = "lore_lzd_saurus", faction = "lzd", name = "Saurus Warhost",
      effect = "Saurus warriors and temple guard stand in silent ranks while a carnosaur prowls behind them.",
      shares = { frontline = 65, missile = 10, cavalry = 15, monsters = 10 },
      units = {
          "wh2_main_lzd_inf_skink_skirmishers_0", "wh2_main_lzd_inf_saurus_warriors_0", "wh2_main_lzd_inf_saurus_spearmen_0", "wh2_main_lzd_inf_saurus_warriors_1",
          "wh2_main_lzd_mon_kroxigors", "wh2_main_lzd_cav_cold_one_spearriders_1", "wh2_main_lzd_inf_temple_guards", "wh2_dlc13_lzd_mon_sacred_kroxigors_0", "wh2_main_lzd_mon_carnosaur_0",
      } },
    { key = "lore_lzd_skinks", faction = "lzd", name = "Skink Swarm",
      effect = "Skinks of every kind dart through the grass. The stegadons they ride lumber along behind.",
      shares = { frontline = 30, missile = 35, monsters = 35 },
      units = {
          "wh2_main_lzd_inf_skink_cohort_0", "wh2_main_lzd_inf_skink_cohort_1", "wh2_main_lzd_inf_skink_skirmishers_0", "wh2_dlc12_lzd_inf_skink_red_crested_0",
          "wh2_main_lzd_cav_terradon_riders_0", "wh2_main_lzd_inf_chameleon_skinks_0", "wh2_main_lzd_mon_bastiladon_0", "wh2_dlc13_lzd_mon_razordon_pack_0",
          "wh2_dlc12_lzd_mon_salamander_pack_0", "wh2_main_lzd_mon_kroxigors", "wh2_main_lzd_mon_stegadon_0", "wh2_main_lzd_mon_ancient_stegadon",
      } },
    { key = "lore_nor_werekin", faction = "nor", name = "Werekin Pack",
      effect = "Skinwolves and bearmen hunt at the head of this warband, and its berserkers fight like the beasts they follow.",
      shares = { frontline = 60, missile = 10, cavalry = 30 },
      units = {
          "wh_main_nor_inf_chaos_marauders_0", "wh_main_nor_mon_chaos_warhounds_0", "wh_dlc08_nor_inf_marauder_hunters_0", "wh3_dlc27_nor_inf_marauder_bearmen",
          "wh_dlc08_nor_mon_marauder_warwolves_0", "wh3_dlc27_nor_inf_marauder_bearmen_greatweapons", "wh_dlc08_nor_inf_marauder_berserkers_0", "wh_dlc08_nor_mon_skinwolves_0",
          "wh_dlc08_nor_cav_marauder_warwolves_chariot_0", "wh_dlc08_nor_mon_skinwolves_1", "wh_pro04_nor_mon_skinwolves_ror_0",
      } },
    { key = "lore_cst_boarding", faction = "cst", name = "Boarding Party",
      effect = "Deck droppers swoop in from above while zombie deckhands and gunnery mobs spill off the ships.",
      shares = { frontline = 45, missile = 30, cavalry = 15, artillery = 10 },
      units = {
          "wh2_dlc11_cst_inf_zombie_deckhands_mob_0", "wh2_dlc11_cst_inf_zombie_gunnery_mob_0", "wh2_dlc11_cst_inf_zombie_deckhands_mob_1", "wh2_dlc11_cst_cav_deck_droppers_0",
          "wh2_dlc11_cst_cav_deck_droppers_1", "wh2_dlc11_cst_inf_zombie_gunnery_mob_1", "wh2_dlc11_cst_inf_deck_gunners_0", "wh2_dlc11_cst_mon_animated_hulks_0",
          "wh2_dlc11_cst_art_carronade", "wh2_dlc11_cst_inf_depth_guard_0",
      } },
    { key = "lore_cst_drowned", faction = "cst", name = "Drowned Host",
      effect = "Depth guard and syreens have risen from the sea floor, dragging rotting horrors up with them.",
      shares = { frontline = 55, missile = 5, monsters = 40 },
      units = {
          "wh2_dlc11_cst_inf_zombie_deckhands_mob_0", "wh2_dlc11_cst_inf_zombie_gunnery_mob_0", "wh2_dlc11_cst_mon_bloated_corpse_0", "wh2_dlc11_cst_inf_syreens",
          "wh2_dlc11_cst_mon_mournguls_0", "wh2_dlc11_cst_mon_rotting_prometheans_0", "wh2_dlc11_cst_inf_depth_guard_0", "wh2_dlc11_cst_inf_depth_guard_1",
          "wh2_dlc11_cst_mon_necrofex_colossus_0", "wh2_dlc11_cst_mon_rotting_leviathan_0",
      } },
    { key = "lore_vmp_grave", faction = "vmp", name = "Grave Horde",
      effect = "Shambling zombies and skeletons pour out of the graveyards around a creaking corpse cart.",
      shares = { frontline = 60, cavalry = 25, monsters = 15 },
      units = {
          "wh_main_vmp_inf_zombie", "wh_dlc04_vmp_veh_corpse_cart_0", "wh_main_vmp_inf_skeleton_warriors_0", "wh_main_vmp_inf_skeleton_warriors_1", "wh_main_vmp_mon_fell_bats",
          "wh_dlc04_vmp_veh_corpse_cart_1", "wh_main_vmp_mon_dire_wolves", "wh_main_vmp_inf_crypt_ghouls", "wh2_dlc11_vmp_inf_crossbowmen", "wh_main_vmp_mon_crypt_horrors",
          "wh_main_vmp_inf_grave_guard_0", "wh_dlc04_vmp_veh_mortis_engine_0", "wh_main_vmp_mon_varghulf",
      } },
    { key = "lore_vmp_lahmia", faction = "vmp", name = "Lahmian Court",
      effect = "The Lahmian sisterhood rides to war on a coven throne, guarded by its handmaidens and mortal retainers.",
      shares = { frontline = 45, missile = 25, cavalry = 20, monsters = 10 },
      units = {
          "wh_main_vmp_inf_skeleton_warriors_1", "wh2_dlc11_vmp_inf_crossbowmen", "wh2_dlc11_vmp_inf_handgunners", "wh_main_vmp_inf_grave_guard_1", "wh_main_vmp_cav_black_knights_3",
          "wh3_dlc29_vmp_inf_lahmian_handmaidens_death", "wh3_dlc29_vmp_inf_lahmian_handmaidens_shadow", "wh3_dlc29_vmp_veh_coven_throne", "wh_main_vmp_mon_terrorgheist",
      } },
    { key = "lore_emp_state", faction = "emp", name = "State Troops",
      effect = "Halberdiers and handgunners hold the line, backed by great cannons from the Imperial Gunnery School.",
      shares = { frontline = 50, missile = 30, cavalry = 5, artillery = 15 },
      units = {
          "wh_main_emp_inf_spearmen_0", "wh_main_emp_inf_swordsmen", "wh_dlc04_emp_inf_free_company_militia_0", "wh_main_emp_inf_crossbowmen", "wh_main_emp_cav_pistoliers_1",
          "wh_main_emp_inf_halberdiers", "wh_main_emp_inf_handgunners", "wh_main_emp_art_mortar", "wh_main_emp_art_great_cannon", "wh_main_emp_inf_greatswords",
          "wh_main_emp_art_helblaster_volley_gun",
      } },
    { key = "lore_emp_knights", faction = "emp", name = "Knightly Orders",
      effect = "The Reiksguard ride with the Knights of the Blazing Sun and the Black Rose, and demigryph knights guard their flanks.",
      shares = { frontline = 20, cavalry = 65, monsters = 15 },
      units = {
          "wh_main_emp_inf_spearmen_1", "wh_main_emp_cav_pistoliers_1", "wh_main_emp_cav_outriders_0", "wh_main_emp_inf_greatswords", "wh_main_emp_cav_empire_knights",
          "wh_main_emp_cav_reiksguard", "wh_dlc04_emp_cav_knights_blazing_sun_0", "wh3_dlc25_emp_cav_knights_of_the_black_rose", "wh3_dlc29_emp_cav_knights_panther",
          "wh_main_emp_cav_demigryph_knights_0",
      } },
    { key = "lore_emp_ulric", faction = "emp", name = "Wolves of Ulric",
      effect = "The Knights of the White Wolf ride beside their Teutogen Guard, with the wolf-kin of Ulric running at their heels.",
      shares = { frontline = 55, missile = 10, cavalry = 35 },
      units = {
          "wh3_dlc29_emp_inf_hunting_hounds", "wh3_dlc29_emp_inf_warriors_of_ulric", "wh2_dlc13_emp_inf_huntsmen_0", "wh3_dlc29_emp_inf_wolf_kin", "wh3_dlc29_emp_inf_teutogen_guard",
          "wh3_dlc29_emp_cav_knights_of_the_white_wolf", "wh3_dlc29_emp_inf_teutogen_guard_ror",
      } },
    { key = "lore_brt_knights", faction = "brt", name = "Knights of the Realm",
      effect = "Questing and grail knights ride beside the young knights errant, with a few men-at-arms trailing behind.",
      shares = { frontline = 15, missile = 5, cavalry = 60, monsters = 20 },
      units = {
          "wh_main_brt_inf_spearmen_at_arms", "wh_main_brt_inf_peasant_bowmen", "wh_main_brt_inf_men_at_arms", "wh_main_brt_cav_mounted_yeomen_1", "wh_dlc07_brt_cav_knights_errant_0",
          "wh_main_brt_cav_knights_of_the_realm", "wh_dlc07_brt_cav_questing_knights_0", "wh_main_brt_cav_pegasus_knights", "wh_dlc07_brt_cav_royal_pegasus_knights_0",
          "wh_main_brt_cav_grail_knights", "wh_dlc07_brt_cav_royal_hippogryph_knights_0",
      } },
    { key = "lore_brt_grail", faction = "brt", name = "Grail Pilgrimage",
      effect = "Battle pilgrims crowd around a grail reliquae, following knights who have drunk from the Grail.",
      shares = { frontline = 50, missile = 10, cavalry = 25, artillery = 15 },
      units = {
          "wh_dlc07_brt_inf_grail_reliquae_0", "wh_dlc07_brt_inf_peasant_bowmen_2", "wh_dlc07_brt_inf_battle_pilgrims_0", "wh_dlc07_brt_inf_foot_squires_0",
          "wh_dlc07_brt_art_blessed_field_trebuchet_0", "wh_dlc07_brt_cav_questing_knights_0", "wh_main_brt_cav_grail_knights", "wh_dlc07_brt_cav_grail_guardians_0",
      } },
    { key = "lore_grn_nightgobs", faction = "grn", name = "Night Goblin Horde",
      effect = "Night goblins boil up out of the caves with their squigs, and fanatics hide somewhere in the ranks.",
      shares = { frontline = 45, missile = 20, cavalry = 15, monsters = 15, artillery = 5 },
      units = {
          "wh_dlc06_grn_inf_squig_herd_0", "wh_main_grn_inf_night_goblins", "wh_main_grn_inf_night_goblin_archers", "wh_dlc06_grn_inf_nasty_skulkers_0",
          "wh_main_grn_inf_night_goblin_fanatics", "wh_main_grn_inf_night_goblin_fanatics_1", "wh_dlc06_grn_cav_squig_hoppers_0", "wh3_dlc26_grn_cav_mangler_squig",
          "wh_main_grn_art_doom_diver_catapult", "wh3_dlc26_grn_mon_colossal_squig",
      } },
    { key = "lore_grn_savage", faction = "grn", name = "Savage Orc Warband",
      effect = "Warpainted savage orcs and boar boyz stomp along behind a rogue idol.",
      shares = { frontline = 50, missile = 15, cavalry = 20, monsters = 15 },
      units = {
          "wh_main_grn_inf_savage_orcs", "wh_main_grn_inf_savage_orc_arrer_boyz", "wh_main_grn_cav_savage_orc_boar_boyz", "wh_main_grn_inf_savage_orc_big_uns",
          "wh_main_grn_cav_savage_orc_boar_boy_big_uns", "wh2_dlc15_grn_mon_rogue_idol_0",
      } },
    { key = "lore_grn_spiders", faction = "grn", name = "Spider Tribe",
      effect = "Forest goblins come scuttling out of the trees on giant spiders, led by a great arachnarok.",
      shares = { frontline = 35, missile = 15, cavalry = 30, monsters = 20 },
      units = {
          "wh_dlc06_grn_mon_spider_hatchlings_0", "wh3_main_grn_inf_goblins_sword_shield", "wh_main_grn_inf_goblin_spearmen", "wh_main_grn_inf_goblin_archers",
          "wh_main_grn_cav_forest_goblin_spider_riders_0", "wh_main_grn_cav_forest_goblin_spider_riders_1", "wh_main_grn_mon_arachnarok_spider_0",
          "wh3_dlc26_grn_mon_arachnarok_spider_flinger",
      } },
    { key = "lore_wef_wildhunt", faction = "wef", name = "Wild Hunt",
      effect = "Great stag knights and wild riders thunder across the field, with wardancers keeping pace on foot.",
      shares = { frontline = 25, cavalry = 55, monsters = 20 },
      units = {
          "wh2_dlc16_wef_cav_glade_riders_2", "wh_dlc05_wef_cav_glade_riders_0", "wh_dlc05_wef_inf_wardancers_0", "wh_dlc05_wef_inf_wardancers_1", "wh_dlc05_wef_cav_wild_riders_0",
          "wh_dlc05_wef_cav_wild_riders_1", "wh2_dlc16_wef_cav_great_stag_knights_0",
      } },
    { key = "lore_wef_forest", faction = "wef", name = "Wrath of the Forest",
      effect = "Dryads and treekin have come out of the deep woods, and treemen stride among them.",
      shares = { frontline = 55, missile = 15, monsters = 30 },
      units = {
          "wh_dlc05_wef_inf_glade_guard_0", "wh_dlc05_wef_inf_dryads_0", "wh_dlc05_wef_mon_treekin_0", "wh_dlc05_wef_inf_wildwood_rangers_0", "wh_dlc05_wef_mon_treeman_0",
          "wh2_dlc16_wef_mon_zoats",
      } },
    { key = "lore_bst_brayherd", faction = "bst", name = "Brayherd",
      effect = "A mob of gors and ungors surrounds the bestigors, and tuskgor chariots crash along beside them.",
      shares = { frontline = 60, missile = 15, cavalry = 25 },
      units = {
          "wh_dlc03_bst_inf_ungor_spearmen_0", "wh_dlc03_bst_inf_ungor_herd_1", "wh_dlc03_bst_inf_chaos_warhounds_0", "wh_dlc03_bst_inf_ungor_raiders_0", "wh_dlc03_bst_inf_gor_herd_1",
          "wh_dlc03_bst_inf_gor_herd_0", "wh2_dlc17_bst_cav_tuskgor_chariot_0", "wh_dlc03_bst_inf_bestigor_herd_0", "wh_dlc03_bst_cav_razorgor_chariot_0",
      } },
    { key = "lore_bst_warherd", faction = "bst", name = "Warherd",
      effect = "Minotaurs bellow for flesh as a cygor and a ghorgon stamp along in their wake.",
      shares = { frontline = 55, missile = 10, monsters = 35 },
      units = {
          "wh_dlc03_bst_inf_gor_herd_0", "wh_dlc03_bst_inf_minotaurs_0", "wh_dlc03_bst_inf_minotaurs_1", "wh_dlc03_bst_inf_minotaurs_2", "wh_dlc03_bst_mon_giant_0", "wh_dlc03_bst_inf_cygor_0",
          "wh2_dlc17_bst_mon_ghorgon_0",
      } },
    { key = "lore_cth_dragonguard", faction = "cth", name = "Celestial Guard",
      effect = "The Emperor's dragon guard hold the centre with a terracotta sentinel at their back.",
      shares = { frontline = 35, missile = 25, cavalry = 10, monsters = 20, artillery = 10 },
      units = {
          "wh3_main_cth_inf_jade_warriors_1", "wh3_main_cth_cav_jade_lancers_0", "wh3_main_cth_inf_crane_gunners_0", "wh3_main_cth_inf_dragon_guard_0",
          "wh3_main_cth_inf_dragon_guard_crossbowmen_0", "wh3_main_cth_art_fire_rain_rocket_battery_0", "wh3_main_cth_cav_jade_longma_riders_0", "wh3_cp1_cth_inf_iron_claw_guandao",
          "wh3_main_cth_mon_terracotta_sentinel_0",
      } },
    { key = "lore_tze_horrors", faction = "tze", name = "Flux of Horrors",
      effect = "Pink horrors split into blue ones as they die, and flamers spit warpfire from behind them.",
      shares = { frontline = 25, missile = 45, cavalry = 5, monsters = 25 },
      units = {
          "wh3_main_tze_inf_blue_horrors_0", "wh3_main_tze_inf_chaos_furies_0", "wh3_main_tze_mon_screamers_0", "wh3_main_tze_inf_pink_horrors_0", "wh3_main_tze_mon_flamers_0",
          "wh3_main_tze_mon_spawn_of_tzeentch_0", "wh3_main_tze_inf_pink_horrors_1", "wh3_main_tze_mon_exalted_flamer_0", "wh3_main_tze_veh_burning_chariot_0",
          "wh3_main_tze_mon_lord_of_change_0",
      } },
    { key = "lore_tze_arcanites", faction = "tze", name = "Arcanite Cult",
      effect = "Tzaangors and forsaken mutants serve the Changer of Ways here, with doom knights riding at their head.",
      shares = { frontline = 40, missile = 15, cavalry = 25, monsters = 20 },
      units = {
          "wh3_main_tze_inf_blue_horrors_0", "wh3_dlc24_tze_inf_tzaangors", "wh3_main_tze_inf_forsaken_0", "wh3_dlc24_tze_mon_cockatrice", "wh3_dlc24_tze_inf_centigors_great_weapons",
          "wh3_main_tze_cav_chaos_knights_0", "wh3_main_tze_cav_doom_knights_0", "wh3_dlc24_tze_mon_mutalith_vortex_beast",
      } },
    { key = "lore_chs_everchosen", faction = "chs", name = "Everchosen Host",
      effect = "Chaos warriors and chosen march in black iron behind a line of chaos knights.",
      shares = { frontline = 55, cavalry = 25, monsters = 10, artillery = 10 },
      units = {
          "wh_main_chs_inf_chaos_marauders_1", "wh_main_chs_cav_marauder_horsemen_0", "wh_main_chs_inf_chaos_warriors_0", "wh_main_chs_inf_chaos_warriors_1",
          "wh_dlc06_chs_inf_aspiring_champions_0", "wh3_dlc20_chs_mon_warshrine", "wh_main_chs_art_hellcannon", "wh_main_chs_inf_chosen_0", "wh_main_chs_cav_chaos_knights_0",
      } },
    { key = "lore_chs_rotbringers", faction = "chs", name = "Rotbringers",
      effect = "Putrid blightkings shamble at the front, followed by warriors marked by Nurgle.",
      shares = { frontline = 60, cavalry = 25, monsters = 15 },
      units = {
          "wh3_dlc20_chs_inf_chaos_marauders_mnur", "wh3_dlc20_chs_cav_marauder_horsemen_mnur_throwing_axes", "wh3_dlc20_chs_inf_chaos_warriors_mnur", "wh3_dlc20_chs_cav_chaos_chariot_mnur",
          "wh3_dlc20_chs_mon_warshrine_mnur", "wh3_dlc20_chs_inf_chosen_mnur", "wh3_dlc29_chs_inf_putrid_blightkings_axe_shield", "wh3_dlc20_chs_cav_chaos_knights_mnur",
          "wh3_dlc29_chs_inf_putrid_blightkings_great_weapons",
      } },
    { key = "lore_chs_bloodbound", faction = "chs", name = "Bloodbound",
      effect = "Marauders who bear the mark of Khorne rush ahead, and the Blood God's chosen follow in heavy armour.",
      shares = { frontline = 55, cavalry = 30, monsters = 15 },
      units = {
          "wh3_dlc20_chs_inf_chaos_marauders_mkho", "wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons", "wh3_dlc20_chs_cav_marauder_horsemen_mkho_throwing_axes",
          "wh3_dlc20_chs_inf_forsaken_mkho", "wh3_dlc20_chs_cav_chaos_chariot_mkho", "wh3_dlc20_chs_inf_chosen_mkho", "wh3_dlc20_chs_mon_warshrine_mkho",
          "wh3_dlc20_chs_cav_chaos_knights_mkho", "wh3_dlc20_chs_inf_chosen_mkho_dualweapons",
      } },
    { key = "lore_nur_tallyband", faction = "nur", name = "Plague Tallyband",
      effect = "Plaguebearers chant their tally as they march, while nurglings tumble about their feet.",
      shares = { frontline = 55, missile = 5, monsters = 40 },
      units = {
          "wh3_main_nur_inf_nurglings_0", "wh3_main_nur_inf_plaguebearers_0", "wh3_main_nur_mon_rot_flies_0", "wh3_main_nur_mon_beast_of_nurgle_0", "wh3_main_nur_inf_plaguebearers_1",
          "wh3_main_nur_cav_plague_drones_0", "wh3_main_nur_mon_soul_grinder_0", "wh3_main_nur_mon_great_unclean_one_0",
      } },
    { key = "lore_nur_maggoth", faction = "nur", name = "Maggoth Horde",
      effect = "Bile trolls and plague ogres trudge after a Maggoth Lord, with pestigors braying behind them.",
      shares = { frontline = 60, missile = 5, cavalry = 15, monsters = 20 },
      units = {
          "wh3_main_nur_mon_plague_toads_0", "wh3_dlc25_nur_inf_pestigors", "wh3_main_nur_inf_forsaken_0", "wh3_dlc25_nur_mon_bile_trolls", "wh3_dlc25_nur_inf_plague_ogres",
          "wh3_dlc25_nur_cav_rot_knights", "wh3_main_nur_mon_soul_grinder_0", "wh3_dlc25_nur_mon_toad_dragon",
      } },
    { key = "lore_sla_devotees", faction = "sla", name = "Cult of Excess",
      effect = "Devotees of Slaanesh and slaangors throw themselves forward, and hellstriders ride hard on the flanks.",
      shares = { frontline = 55, missile = 10, cavalry = 25, monsters = 10 },
      units = {
          "wh3_main_sla_inf_marauders_0", "wh3_main_sla_inf_marauders_2", "wh3_main_sla_cav_hellstriders_0", "wh3_dlc27_sla_inf_slaangors", "wh3_dlc27_sla_cav_pleasureseekers",
          "wh3_dlc27_sla_inf_devotees_of_slaanesh", "wh3_dlc27_sla_inf_devotees_of_slaanesh_crossbows", "wh3_dlc27_sla_mon_preyton", "wh3_dlc27_sla_mon_champions_of_slaanesh",
      } },
    { key = "lore_chd_daemonsmith", faction = "chd", name = "Daemonsmith Foundry",
      effect = "Infernal guard escort an iron daemon and other daemon-bound engines forged in Hashut's name.",
      shares = { frontline = 35, missile = 10, monsters = 15, artillery = 40 },
      units = {
          "wh3_dlc23_chd_inf_chaos_dwarf_warriors", "wh3_dlc23_chd_inf_infernal_guard", "wh3_dlc23_chd_inf_infernal_guard_great_weapons", "wh3_dlc23_chd_veh_magma_cannon",
          "wh3_dlc23_chd_veh_iron_daemon", "wh3_dlc23_chd_inf_infernal_guard_fireglaives", "wh3_dlc23_chd_veh_deathshrieker_rocket_launcher", "wh3_dlc23_chd_mon_kdaai_fireborn",
          "wh3_dlc23_chd_veh_dreadquake_mortar", "wh3_dlc23_chd_mon_kdaai_destroyer",
      } },
    { key = "lore_ksl_icecourt", faction = "ksl", name = "Ice Court",
      effect = "Ice guard stand shoulder to shoulder with the tzar guard, and an elemental bear pads beside them.",
      shares = { frontline = 30, missile = 40, cavalry = 10, monsters = 20 },
      units = {
          "wh3_main_ksl_inf_kossars_1", "wh3_main_ksl_mon_snow_leopard_0", "wh3_main_ksl_inf_tzar_guard_0", "wh3_main_ksl_inf_ice_guard_1", "wh3_main_ksl_inf_tzar_guard_1",
          "wh3_main_ksl_inf_ice_guard_0", "wh3_main_ksl_veh_heavy_war_sled_0", "wh3_dlc24_ksl_mon_frost_wyrm", "wh3_main_ksl_mon_elemental_bear_0",
      } },
    { key = "lore_ksl_witchwood", faction = "ksl", name = "Witchwood Folk",
      effect = "Akshina ambushers wait in the trees beside Kislevite warriors, and the Things in the Woods are never far away.",
      shares = { frontline = 30, missile = 30, monsters = 40 },
      units = {
          "wh3_main_ksl_inf_kossars_0", "wh3_dlc24_ksl_inf_kislevite_warriors", "wh3_main_ksl_mon_snow_leopard_0", "wh3_dlc24_ksl_mon_the_things_in_the_woods",
          "wh3_dlc24_ksl_inf_akshina_ambushers", "wh3_main_ksl_inf_tzar_guard_0", "wh3_dlc24_ksl_mon_incarnate_elemental_of_beasts",
      } },
    { key = "lore_ogr_maneaters", faction = "ogr", name = "Maneater Company",
      effect = "Maneaters who have fought in every corner of the world march with leadbelchers and a rabble of gnoblars.",
      shares = { frontline = 75, missile = 10, cavalry = 15 },
      units = {
          "wh3_main_ogr_inf_gnoblars_0", "wh3_main_ogr_inf_gnoblars_1", "wh3_main_ogr_inf_ogres_1", "wh3_main_ogr_inf_leadbelchers_0", "wh3_main_ogr_inf_maneaters_0",
          "wh3_main_ogr_inf_maneaters_1", "wh3_main_ogr_inf_maneaters_3", "wh3_dlc26_ogr_inf_golgfags_maneaters", "wh3_main_ogr_veh_ironblaster_0",
      } },
    { key = "lore_ogr_beastriders", faction = "ogr", name = "Beastrider Lodge",
      effect = "Mournfang cavalry have come down from the Mountains of Mourn with a stonehorn in tow.",
      shares = { frontline = 25, missile = 10, cavalry = 10, monsters = 55 },
      units = {
          "wh3_main_ogr_inf_gnoblars_1", "wh3_main_ogr_mon_sabretusk_pack_0", "wh3_main_ogr_inf_ogres_0", "wh3_main_ogr_cav_mournfang_cavalry_0", "wh3_dlc26_ogr_mon_yhetees",
          "wh3_main_ogr_cav_mournfang_cavalry_1", "wh3_main_ogr_mon_stonehorn_0", "wh3_dlc26_ogr_mon_thundertusk",
      } },
}
