--- Vanilla legendary lords per LEAPOI faction shorthand, for the Tower champion offer. Generated from the vanilla agent_subtypes table: a
--- subtype that is not auto-generated and whose onscreen type reads "Legendary Lord". Pure data - no runtime logic.

return {
    brt = { "wh2_dlc14_brt_repanse", "wh_dlc07_brt_alberic", "wh_dlc07_brt_fay_enchantress", "wh_main_brt_louen_leoncouer" },
    bst = { "wh2_dlc17_bst_taurox", "wh_dlc03_bst_khazrak", "wh_dlc03_bst_malagor", "wh_dlc05_bst_morghur" },
    chd = { "wh3_dlc23_chd_astragoth", "wh3_dlc23_chd_drazhoath", "wh3_dlc23_chd_zhatan" },
    chs = { "wh_dlc01_chs_kholek_suneater", "wh_dlc01_chs_prince_sigvald", "wh_main_chs_archaon", "wh_main_chs_lord_of_change" },
    cst = { "wh2_dlc11_cst_aranessa", "wh2_dlc11_cst_cylostra", "wh2_dlc11_cst_harkon", "wh2_dlc11_cst_noctilus" },
    cth = { "wh3_cp1_cth_bhashiva", "wh3_dlc24_cth_yuan_bo", "wh3_main_cth_miao_ying", "wh3_main_cth_zhao_ming" },
    def = { "wh2_dlc10_def_crone_hellebron", "wh2_dlc11_def_lokhir", "wh2_dlc14_def_malus_darkblade", "wh2_main_def_malekith", "wh2_main_def_morathi",
        "wh2_twa03_def_rakarth" },
    dwf = { "wh2_dlc17_dwf_thorek", "wh3_dlc25_dwf_malakai_makaisson", "wh_dlc06_dwf_belegar", "wh_main_dwf_thorgrim_grudgebearer",
        "wh_main_dwf_ungrim_ironfist", "wh_pro01_dwf_grombrindal" },
    emp = { "wh2_dlc13_emp_cha_markus_wulfhart", "wh3_dlc25_emp_elspeth_von_draken", "wh_dlc03_emp_boris_todbringer", "wh_dlc04_emp_volkmar",
        "wh_main_emp_balthasar_gelt", "wh_main_emp_karl_franz" },
    grn = { "wh2_dlc15_grn_grom_the_paunch", "wh_dlc06_grn_skarsnik", "wh_dlc06_grn_wurrzag_da_great_prophet", "wh_main_grn_azhag_the_slaughterer",
        "wh_main_grn_grimgor_ironhide" },
    hef = { "wh2_dlc10_hef_alarielle", "wh2_dlc10_hef_alith_anar", "wh2_dlc15_hef_eltharion", "wh2_dlc15_hef_imrik", "wh2_main_hef_teclis",
        "wh2_main_hef_tyrion", "wh3_dlc27_hef_aislinn" },
    kho = { "wh3_dlc20_kho_valkia", "wh3_main_kho_skarbrand" },
    ksl = { "wh3_dlc24_ksl_mother_ostankya", "wh3_main_ksl_boris", "wh3_main_ksl_katarin", "wh3_main_ksl_kostaltyn" },
    lzd = { "wh2_dlc12_lzd_tehenhauin", "wh2_dlc12_lzd_tiktaqto", "wh2_dlc13_lzd_gor_rok", "wh2_dlc13_lzd_nakai", "wh2_dlc17_lzd_oxyotl",
        "wh2_main_lzd_kroq_gar", "wh2_main_lzd_lord_mazdamundi" },
    nor = { "wh3_dlc27_nor_sayl_the_faithless", "wh_dlc08_nor_throgg", "wh_dlc08_nor_wulfrik" },
    nur = { "wh3_dlc20_nur_festus", "wh3_dlc25_nur_epidemius", "wh3_dlc25_nur_tamurkhan", "wh3_main_nur_kugath" },
    ogr = { "wh3_dlc26_ogr_golgfag", "wh3_dlc26_ogr_golgfag_maneater", "wh3_main_ogr_greasus_goldtooth", "wh3_main_ogr_skrag_the_slaughterer" },
    skv = { "wh2_dlc09_skv_tretch_craventail", "wh2_dlc12_skv_ikit_claw", "wh2_dlc14_skv_deathmaster_snikch", "wh2_dlc16_skv_throt_the_unclean",
        "wh2_main_skv_lord_skrolk", "wh2_main_skv_queek_headtaker", "wh3_dlc29_skv_skreech_verminking_general" },
    sla = { "wh3_dlc20_sla_azazel", "wh3_dlc27_sla_masque_of_slaanesh", "wh3_main_sla_nkari" },
    tmb = { "wh2_dlc09_tmb_arkhan", "wh2_dlc09_tmb_khalida", "wh2_dlc09_tmb_khatep", "wh2_dlc09_tmb_settra" },
    tze = { "wh3_dlc20_tze_vilitch", "wh3_dlc24_tze_the_changeling", "wh3_main_tze_kairos" },
    vmp = { "wh_dlc04_vmp_helman_ghorst", "wh_dlc04_vmp_vlad_con_carstein", "wh_dlc05_vmp_red_duke", "wh_main_vmp_heinrich_kemmler",
        "wh_main_vmp_mannfred_von_carstein", "wh_pro02_vmp_isabella_von_carstein" },
    wef = { "wh2_dlc16_wef_drycha", "wh2_dlc16_wef_sisters_of_twilight", "wh_dlc05_wef_durthu", "wh_dlc05_wef_orion" },
}
