"""Tests for reading and writing TTC compat Lua files."""

import os
import re

import ttc_compat_io as io_

ENTRY = re.compile(r'\{\s*"[^"]+"\s*,\s*"(?:core|special|rare)"')


def test_every_real_hand_file_parses_all_entries():
    paths = io_.hand_files()
    assert paths
    for path in paths:
        text = open(path, encoding="utf-8").read()
        assert len(io_.parse_ttc_file(path)) == len(ENTRY.findall(text)), path


def test_parse_reads_weight_and_optional_weight():
    entries = io_.parse_ttc_text('local caps = {\n    {"a_unit", "special", 2},\n    {"b_unit", "core"},\n}\n')
    assert [(e.key, e.category, e.weight, e.line_no) for e in entries] == [("a_unit", "special", 2, 2), ("b_unit", "core", None, 3)]


def test_render_then_parse_round_trips_sorted():
    text = io_.render_auto_file("my_mod", {"grp_b": [("z_unit", "rare", 3)], "grp_a": [("b_unit", "core", None), ("a_unit", "special", 1)]})
    assert text.startswith("-- my_mod (auto-generated by update_ttc_compat.py, do not edit)\n")
    assert [(e.key, e.category, e.weight) for e in io_.parse_ttc_text(text)] == [("a_unit", "special", 1), ("b_unit", "core", None), ("z_unit", "rare", 3)]
    assert "ttc.add_unit_list(caps, true)" in text


def test_remove_lines_keeps_every_other_byte(tmp_path):
    original = '-- mod\r\nlocal caps = {\r\n    -- Kislev\r\n    {"keep_me", "rare", 1},\r\n    {"drop_me", "special", 2},\r\n}\r\n'
    path = tmp_path / "x.lua"
    path.write_bytes(original.encode())
    removed = io_.remove_lines(str(path), {"drop_me"})
    assert removed == ['    {"drop_me", "special", 2},']
    assert path.read_bytes().decode() == original.replace('    {"drop_me", "special", 2},\r\n', "")


def test_auto_file_path_strips_bangs_and_extension():
    assert os.path.basename(io_.auto_file_path("!!!1a_glf_unit_expansion.pack")) == "!!!!!!!1a_glf_unit_expansion_auto.lua"
